//! op_table! macro - Single source of truth for all semantic operations
//!
//! Generates:
//! - UnifiedMeaningOp enum with all operations
//! - Zone/signature/laws accessors
//! - IR symbol names for LLVM codegen
//!
//! ## 헌법 준수 (P0-1)
//!
//! - 구조 정의만 포함, 실행 코드 없음
//! - op_table! 매크로는 enum과 메서드만 생성
//! - 실제 연산 실행은 pnix-executor-graph에서 수행

use crate::effects::EffectZone;

/// 연산 메타데이터: op_table! 매크로에 의해 생성된 연산 메타데이터
///
/// ## 헌법 준수 (P0-1)
///
/// 구조 정의만, 값 계산 없음
#[derive(Debug, Clone)]
pub struct OpMeta {
  /// 효과 영역
  pub zone: EffectZone,
  /// 타입 시그니처 문자열
  pub signature: &'static str,
  /// 대수 법칙 목록
  pub laws: &'static [&'static str],
  /// IR 심볼 이름 (LLVM 코드 생성용)
  pub ir_symbol: &'static str,
  /// 인자 개수 (arity)
  pub arity: u8,
}

/// op_table! macro
///
/// Usage:
/// ```ignore
/// op_table! {
///     // Pure arithmetic
///     Add { zone: Pure, sig: "Int → Int → Int", laws: ["commutative", "associative"] }
///     Sub { zone: Pure, sig: "Int → Int → Int" }
///
///     // STM
///     AtomNew { zone: STM, sig: "a → Atom a" }
/// }
/// ```
#[macro_export]
macro_rules! op_table {
    // Main entry point
    (
        $(
            $name:ident {
                zone: $zone:ident
                $(, sig: $sig:literal)?
                $(, laws: [$($law:literal),* $(,)?])?
                $(, ir: $ir:literal)?
                $(, arity: $arity:literal)?
            }
        )*
    ) => {
        /// Unified MeaningOp enum (generated by op_table!)
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
        pub enum UnifiedMeaningOp {
            $($name,)*
        }

        impl UnifiedMeaningOp {
            /// Get effect zone
            pub fn zone(&self) -> $crate::effects::EffectZone {
                match self {
                    $(UnifiedMeaningOp::$name => $crate::effects::EffectZone::$zone,)*
                }
            }

            /// Get type signature
            pub fn signature(&self) -> &'static str {
                match self {
                    $(UnifiedMeaningOp::$name => op_table!(@sig $($sig)?),)*
                }
            }

            /// Get algebraic laws
            pub fn laws(&self) -> &'static [&'static str] {
                match self {
                    $(UnifiedMeaningOp::$name => op_table!(@laws $($($law),*)?),)*
                }
            }

            /// Get IR symbol for LLVM codegen
            pub fn ir_symbol(&self) -> &'static str {
                match self {
                    $(UnifiedMeaningOp::$name => op_table!(@ir $name $($ir)?),)*
                }
            }

            /// Get arity (number of arguments)
            pub fn arity(&self) -> u8 {
                match self {
                    $(UnifiedMeaningOp::$name => op_table!(@arity $($arity)?),)*
                }
            }

            /// Get full metadata
            pub fn meta(&self) -> $crate::fx::op_table::OpMeta {
                $crate::fx::op_table::OpMeta {
                    zone: self.zone(),
                    signature: self.signature(),
                    laws: self.laws(),
                    ir_symbol: self.ir_symbol(),
                    arity: self.arity(),
                }
            }

            /// Is this operation optimizable? (Pure zone)
            pub fn is_optimizable(&self) -> bool {
                matches!(
                    self.zone(),
                    EffectZone::Pure | EffectZone::Symbolic | EffectZone::Frp | EffectZone::Animation
                )
            }

            /// All operations
            pub fn all() -> &'static [UnifiedMeaningOp] {
                &[$(UnifiedMeaningOp::$name,)*]
            }

            /// Operation name as string
            pub fn name(&self) -> &'static str {
                match self {
                    $(UnifiedMeaningOp::$name => stringify!($name),)*
                }
            }

            /// Parse from string (convenience method)
            #[allow(clippy::should_implement_trait)]
            pub fn from_str(s: &str) -> Option<Self> {
                match s {
                    $(stringify!($name) => Some(UnifiedMeaningOp::$name),)*
                    _ => None,
                }
            }
        }

        /// Implement FromStr trait for UnifiedMeaningOp
        impl std::str::FromStr for UnifiedMeaningOp {
            type Err = String;

            fn from_str(s: &str) -> Result<Self, Self::Err> {
                match s {
                    $(stringify!($name) => Ok(UnifiedMeaningOp::$name),)*
                    _ => Err(format!("Unknown operation: {}", s)),
                }
            }
        }

        impl std::fmt::Display for UnifiedMeaningOp {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "{}", self.name())
            }
        }
    };

    // Helper: extract signature or default
    (@sig $sig:literal) => { $sig };
    (@sig) => { "" };

    // Helper: extract laws or empty
    (@laws $($law:literal),*) => { &[$($law),*] };
    (@laws) => { &[] };

    // Helper: extract IR symbol or generate from name
    (@ir $name:ident $ir:literal) => { $ir };
    (@ir $name:ident) => { concat!("fx_", stringify!($name)) };

    // Helper: extract arity or default to 0
    (@arity $arity:literal) => { $arity };
    (@arity) => { 0 };
}

// ============================================================
// Unified Operation Table Definition
// ============================================================

op_table! {
    // ========== Pure Arithmetic ==========
    Add { zone: Pure, sig: "Num → Num → Num", laws: ["commutative", "associative"], arity: 2 }
    Sub { zone: Pure, sig: "Num → Num → Num", arity: 2 }
    Mul { zone: Pure, sig: "Num → Num → Num", laws: ["commutative", "associative"], arity: 2 }
    Div { zone: Pure, sig: "Num → Num → Num", arity: 2 }
    Mod { zone: Pure, sig: "Int → Int → Int", arity: 2 }
    Neg { zone: Pure, sig: "Num → Num", arity: 1 }

    // ========== Math Functions ==========
    Floor { zone: Pure, sig: "Float → Int", arity: 1 }
    Ceil { zone: Pure, sig: "Float → Int", arity: 1 }
    Abs { zone: Pure, sig: "Num → Num", arity: 1 }
    Sqrt { zone: Pure, sig: "Float → Float", arity: 1 }
    Sin { zone: Pure, sig: "Float → Float", arity: 1 }
    Cos { zone: Pure, sig: "Float → Float", arity: 1 }
    Tan { zone: Pure, sig: "Float → Float", arity: 1 }
    Exp { zone: Pure, sig: "Float → Float", arity: 1 }
    Ln { zone: Pure, sig: "Float → Float", arity: 1 }
    Pow { zone: Pure, sig: "Float → Float → Float", arity: 2 }

    // ========== Comparison ==========
    Lt { zone: Pure, sig: "Ord a ⇒ a → a → Bool", arity: 2 }
    Gt { zone: Pure, sig: "Ord a ⇒ a → a → Bool", arity: 2 }
    Le { zone: Pure, sig: "Ord a ⇒ a → a → Bool", arity: 2 }
    Ge { zone: Pure, sig: "Ord a ⇒ a → a → Bool", arity: 2 }
    Eq { zone: Pure, sig: "Eq a ⇒ a → a → Bool", laws: ["reflexive", "symmetric", "transitive"], arity: 2 }
    Ne { zone: Pure, sig: "Eq a ⇒ a → a → Bool", arity: 2 }

    // ========== Logic ==========
    And { zone: Pure, sig: "Bool → Bool → Bool", laws: ["commutative", "associative"], arity: 2 }
    Or { zone: Pure, sig: "Bool → Bool → Bool", laws: ["commutative", "associative"], arity: 2 }
    Not { zone: Pure, sig: "Bool → Bool", laws: ["involutive"], arity: 1 }

    // ========== Control Flow ==========
    If { zone: Pure, sig: "Bool → a → a → a", arity: 3 }
    Select { zone: Pure, sig: "Bool → a → a → a", arity: 3 }

    // ========== Core Language ==========
    Literal { zone: Pure, sig: "a", arity: 0 }
    Var { zone: Pure, sig: "a", arity: 0 }
    Lambda { zone: Pure, sig: "(a → b)", arity: 1 }
    Apply { zone: Pure, sig: "(a → b) → a → b", arity: 2 }
    Let { zone: Pure, sig: "a → (a → b) → b", arity: 2 }

    // ========== Data Structures ==========
    List { zone: Pure, sig: "[a]", arity: 0 }
    AttrSet { zone: Pure, sig: "{...}", arity: 0 }
    RecAttrSet { zone: Pure, sig: "rec {...}", arity: 0 }
    SelectAttr { zone: Pure, sig: "{...} → String → a", arity: 2 }
    HasAttr { zone: Pure, sig: "{...} → String → Bool", arity: 2 }
    With { zone: Pure, sig: "{...} → a → a", arity: 2 }

    // ========== List Operations (Builtins) ==========
    Map { zone: Pure, sig: "(a → b) → [a] → [b]", laws: ["functor_identity", "functor_composition"], arity: 2 }
    Filter { zone: Pure, sig: "(a → Bool) → [a] → [a]", arity: 2 }
    Foldl { zone: Pure, sig: "(b → a → b) → b → [a] → b", arity: 3 }
    Length { zone: Pure, sig: "[a] → Int", arity: 1 }
    Head { zone: Pure, sig: "[a] → a", arity: 1 }
    Tail { zone: Pure, sig: "[a] → [a]", arity: 1 }
    ElemAt { zone: Pure, sig: "[a] → Int → a", arity: 2 }
    ListCons { zone: Pure, sig: "a → [a] → [a]", arity: 2 }
    Concat { zone: Pure, sig: "[[a]] → [a]", arity: 1 }

    // ========== AttrSet Operations ==========
    AttrNames { zone: Pure, sig: "{...} → [String]", arity: 1 }
    AttrValues { zone: Pure, sig: "{...} → [a]", arity: 1 }
    GetAttr { zone: Pure, sig: "String → {..} → a", arity: 2 }
    AttrSetUpdate { zone: Pure, sig: "{...} → {...} → {...}", arity: 2 }

    // ========== String/Type Operations ==========
    ToString { zone: Pure, sig: "a → String", arity: 1 }
    TypeOf { zone: Pure, sig: "a → String", arity: 1 }

    // ========== FRP / Time ==========
    SysTime { zone: Pure, sig: "Float", ir: "fx_system_time", arity: 0 }
    DeltaTime { zone: Pure, sig: "Float", ir: "fx_delta_time", arity: 0 }
    SecondsFromTime { zone: Pure, sig: "Float → Int", arity: 0 }
    MinutesFromTime { zone: Pure, sig: "Float → Int", arity: 0 }
    HoursFromTime { zone: Pure, sig: "Float → Int", arity: 0 }
    AngleFromSecond { zone: Pure, sig: "Int → Float", arity: 1 }
    AngleFromMinute { zone: Pure, sig: "Int → Float", arity: 1 }
    AngleFromHour { zone: Pure, sig: "Int → Float", arity: 1 }
    PositionFromAngle { zone: Pure, sig: "Float → Float → Float → (Float, Float)", arity: 3 }

    // FRP Signal Operations
    FrpLift { zone: Pure, sig: "(a → b) → Signal a → Signal b", ir: "frp_lift", arity: 2 }
    FrpStep { zone: World, sig: "Float → IO ()", ir: "frp_step", arity: 1 }
    FrpSample { zone: Pure, sig: "Signal a → a", ir: "frp_sample", arity: 1 }
    FrpInput { zone: Pure, sig: "String → Signal a", ir: "frp_input", arity: 1 }
    FrpConst { zone: Pure, sig: "a → Signal a", ir: "frp_const", arity: 1 }

    // ========== STM Operations ==========
    AtomNew { zone: Stm, sig: "a → Atom a", ir: "stm_atom_new", arity: 1 }
    AtomRead { zone: Stm, sig: "Atom a → STM a", ir: "stm_atom_read", arity: 1 }
    AtomWrite { zone: Stm, sig: "Atom a → a → STM ()", ir: "stm_atom_write", arity: 2 }
    AtomSwap { zone: Stm, sig: "Atom a → (a → a) → STM a", ir: "stm_atom_swap", arity: 2 }
    RefNew { zone: Stm, sig: "a → Ref a", ir: "stm_ref_new", arity: 1 }
    RefRead { zone: Stm, sig: "Ref a → STM a", ir: "stm_ref_read", arity: 1 }
    RefWrite { zone: Stm, sig: "Ref a → a → STM ()", ir: "stm_ref_write", arity: 2 }
    Atomically { zone: Stm, sig: "STM a → IO a", ir: "stm_atomically", arity: 1 }

    // ========== Channel Operations ==========
    ChannelNew { zone: World, sig: "() → Channel a", ir: "chan_new", arity: 0 }
    ChannelSend { zone: World, sig: "Channel a → a → IO ()", ir: "chan_send", arity: 2 }
    ChannelRecv { zone: World, sig: "Channel a → IO a", ir: "chan_recv", arity: 1 }
    ChannelClose { zone: World, sig: "Channel a → IO ()", ir: "chan_close", arity: 1 }

    // ========== Async Operations ==========
    Async { zone: World, sig: "IO a → Future a", ir: "async_spawn", arity: 1 }
    Await { zone: World, sig: "Future a → IO a", ir: "async_await", arity: 1 }

    // ========== IO Operations ==========
    IORead { zone: World, sig: "Path → IO String", ir: "io_read", arity: 1 }
    IOWrite { zone: World, sig: "Path → String → IO ()", ir: "io_write", arity: 2 }
    Print { zone: World, sig: "String → IO ()", ir: "io_print", arity: 1 }

    // ========== Interop Operations ==========
    //
    // **CRITICAL**: Interop 연산은 보안 취약점 가능성이 있음
    // - Python/Clojure/JS 코드가 임의의 코드 실행 가능
    // - 데이터 유출, 파일 시스템 접근 등 가능
    // - 현재는 effect 검증 없이 모든 Interop이 Interop zone으로 설정됨
    //
    // 향후 개선: capability system 구현 필요
    // - Interop 연산에 effect signature 추가
    // - sandboxing 및 capability 제한
    // - effect boundary 검증
    InteropCall { zone: Interop, sig: "String → [a] → b", ir: "interop_call", arity: 2 }
    InteropClj { zone: Interop, sig: "String → a", ir: "interop_clj_eval", arity: 1 }
    InteropCljCall { zone: Interop, sig: "String → [a] → b", ir: "interop_clj_call", arity: 2 }
    InteropCljFn { zone: Interop, sig: "String → (a → b)", ir: "interop_clj_fn", arity: 1 }
    InteropPy { zone: Interop, sig: "String → a", ir: "interop_py_eval", arity: 1 }
    InteropPyCall { zone: Interop, sig: "String → [a] → b", ir: "interop_py_call", arity: 2 }
    InteropPyFn { zone: Interop, sig: "String → (a → b)", ir: "interop_py_fn", arity: 1 }
    InteropNix { zone: Interop, sig: "String → a", ir: "interop_nix_eval", arity: 1 }
    InteropJS { zone: Interop, sig: "String → a", ir: "interop_js_eval", arity: 1 }
    InteropJSCall { zone: Interop, sig: "String → [a] → b", ir: "interop_js_call", arity: 2 }
    InteropJSFn { zone: Interop, sig: "String → (a → b)", ir: "interop_js_fn", arity: 1 }
    InteropTS { zone: Interop, sig: "String → a", ir: "interop_ts_eval", arity: 1 }
    InteropTSCall { zone: Interop, sig: "String → [a] → b", ir: "interop_ts_call", arity: 2 }
    InteropTSFn { zone: Interop, sig: "String → (a → b)", ir: "interop_ts_fn", arity: 1 }

    // ========== CT Operations ==========
    CTFmap { zone: Pure, sig: "(a → b) → F a → F b", laws: ["functor_identity", "functor_composition"], arity: 2 }
    CTPure { zone: Pure, sig: "a → F a", arity: 1 }
    CTAp { zone: Pure, sig: "F (a → b) → F a → F b", arity: 2 }
    CTBind { zone: Pure, sig: "F a → (a → F b) → F b", laws: ["monad_left_identity", "monad_right_identity", "monad_associativity"], arity: 2 }
    CTReturn { zone: Pure, sig: "a → F a", arity: 1 }
    CTCompose { zone: Pure, sig: "(b → c) → (a → b) → (a → c)", laws: ["associative"], arity: 2 }
    CTNatTrans { zone: Pure, sig: "F a → G a", arity: 1 }
    CTId { zone: Pure, sig: "a → a", laws: ["identity"], arity: 1 }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn test_op_zones() {
    assert_eq!(UnifiedMeaningOp::Add.zone(), EffectZone::Pure);
    assert_eq!(UnifiedMeaningOp::AtomNew.zone(), EffectZone::Stm);
  }

  #[test]
  fn test_op_signatures() {
    assert_eq!(UnifiedMeaningOp::Add.signature(), "Num → Num → Num");
  }

  #[test]
  fn test_op_laws() {
    let add_laws = UnifiedMeaningOp::Add.laws();
    assert!(add_laws.contains(&"commutative"));
    assert!(add_laws.contains(&"associative"));
  }

  #[test]
  fn test_op_ir_symbol() {
    assert_eq!(UnifiedMeaningOp::Add.ir_symbol(), "fx_Add");
    assert_eq!(UnifiedMeaningOp::AtomNew.ir_symbol(), "stm_atom_new");
  }

  #[test]
  fn test_op_arity() {
    assert_eq!(UnifiedMeaningOp::Add.arity(), 2);
    assert_eq!(UnifiedMeaningOp::AtomNew.arity(), 1);
  }

  #[test]
  fn test_all_ops() {
    let all = UnifiedMeaningOp::all();
    assert!(all.len() >= 3);
    assert!(all.contains(&UnifiedMeaningOp::Add));

    let meta = UnifiedMeaningOp::Add.meta();
    assert_eq!(meta.arity, 2);
    assert!(UnifiedMeaningOp::Add.is_optimizable());
  }

  #[test]
  fn test_op_from_str() {
    assert_eq!(
      UnifiedMeaningOp::from_str("Add"),
      Some(UnifiedMeaningOp::Add)
    );
    assert_eq!(UnifiedMeaningOp::from_str("Unknown"), None);
  }
}
