//! FxSurface - Language-specific Surface AST
//!
//! Shallow AST generated by language parsers (pnix/clojure).
//! Language differences are handled here, then lowered to FxCoreExpr.
//!
//! ## Layer Design
//!
//! ```text
//! pnix source ─── pnix_parser ──┐
//!                               ├─► FxSurfaceExpr ─► FxCoreExpr
//! clojure source ─── clojure_parser ──┘
//! ```
//!
//! ## 헌법 준수 (P0-1)
//!
//! 순수 AST 구조 정의, 값 계산 없음

use serde::{Deserialize, Serialize};

/// Language-specific surface AST (shallow AST with language flavor)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FxSurfaceExpr {
  // ========== Literals ==========
  /// Integer constant
  ConstInt(i64),
  /// Float constant
  ConstFloat(f64),
  /// Boolean constant
  ConstBool(bool),
  /// String constant
  ConstString(String),

  // ========== Identifiers ==========
  /// Identifier (variable, parameter, builtin reference)
  /// e.g.: "x", "param.system_time", "param/system-time", "hours"
  Ident(String),

  // ========== Operations ==========
  /// 함수 호출
  /// 예: floor(x), sin(x), Math/floor(x)
  Call {
    /// 함수 이름
    func: String,
    /// 인자 표현식 목록
    args: Vec<FxSurfaceExpr>,
  },

  /// 중위 연산자
  /// 예: x + y, a * b, t % 60
  InfixOp {
    /// 연산자 문자열 ("+", "-", "*", "/", "%", "==" 등)
    op: String,
    /// 왼쪽 피연산자
    left: Box<FxSurfaceExpr>,
    /// 오른쪽 피연산자
    right: Box<FxSurfaceExpr>,
  },

  /// 전위 연산자
  /// 예: -x, !cond
  PrefixOp {
    /// 연산자 문자열 ("-", "!" 등)
    op: String,
    /// 피연산자
    arg: Box<FxSurfaceExpr>,
  },

  // ========== Control Flow ==========
  /// 조건문
  If {
    /// 조건 표현식
    cond: Box<FxSurfaceExpr>,
    /// then 절 표현식
    then_: Box<FxSurfaceExpr>,
    /// else 절 표현식
    else_: Box<FxSurfaceExpr>,
  },

  /// Let 바인딩
  Let {
    /// 바인딩 이름
    name: String,
    /// 값 표현식
    value: Box<FxSurfaceExpr>,
    /// 본문 표현식
    body: Box<FxSurfaceExpr>,
  },

  // ========== FX Block ==========
  /// fx 블록 (FRP 표현식을 명시적으로 표시)
  Fx(
    /// 내부 표현식
    Box<FxSurfaceExpr>,
  ),
}

impl FxSurfaceExpr {
  // ========== Constructors ==========

  /// 정수 리터럴 생성
  ///
  /// ## 헌법 준수 (P0-1)
  ///
  /// 구조 생성만, 값 계산 없음
  pub fn int(v: i64) -> Self {
    Self::ConstInt(v)
  }

  /// 실수 리터럴 생성
  ///
  /// ## 헌법 준수 (P0-1)
  ///
  /// 구조 생성만, 값 계산 없음
  pub fn float(v: f64) -> Self {
    Self::ConstFloat(v)
  }

  /// 불리언 리터럴 생성
  ///
  /// ## 헌법 준수 (P0-1)
  ///
  /// 구조 생성만, 값 계산 없음
  pub fn bool_(v: bool) -> Self {
    Self::ConstBool(v)
  }

  /// 식별자 생성
  ///
  /// ## 헌법 준수 (P0-1)
  ///
  /// 구조 생성만, 값 계산 없음
  pub fn ident(name: impl Into<String>) -> Self {
    Self::Ident(name.into())
  }

  /// 함수 호출 생성
  ///
  /// ## 헌법 준수 (P0-1)
  ///
  /// 구조 생성만, 값 계산 없음
  pub fn call(func: impl Into<String>, args: Vec<FxSurfaceExpr>) -> Self {
    Self::Call {
      func: func.into(),
      args,
    }
  }

  /// 중위 연산 생성
  ///
  /// ## 헌법 준수 (P0-1)
  ///
  /// 구조 생성만, 값 계산 없음
  pub fn infix(op: impl Into<String>, left: FxSurfaceExpr, right: FxSurfaceExpr) -> Self {
    Self::InfixOp {
      op: op.into(),
      left: Box::new(left),
      right: Box::new(right),
    }
  }

  /// 전위 연산 생성
  ///
  /// ## 헌법 준수 (P0-1)
  ///
  /// 구조 생성만, 값 계산 없음
  pub fn prefix(op: impl Into<String>, arg: FxSurfaceExpr) -> Self {
    Self::PrefixOp {
      op: op.into(),
      arg: Box::new(arg),
    }
  }

  /// 조건문 생성
  ///
  /// ## 헌법 준수 (P0-1)
  ///
  /// 구조 생성만, 값 계산 없음
  pub fn if_(cond: FxSurfaceExpr, then_: FxSurfaceExpr, else_: FxSurfaceExpr) -> Self {
    Self::If {
      cond: Box::new(cond),
      then_: Box::new(then_),
      else_: Box::new(else_),
    }
  }

  /// Let 바인딩 생성
  ///
  /// ## 헌법 준수 (P0-1)
  ///
  /// 구조 생성만, 값 계산 없음
  pub fn let_(name: impl Into<String>, value: FxSurfaceExpr, body: FxSurfaceExpr) -> Self {
    Self::Let {
      name: name.into(),
      value: Box::new(value),
      body: Box::new(body),
    }
  }

  /// Fx 블록 생성
  ///
  /// ## 헌법 준수 (P0-1)
  ///
  /// 구조 생성만, 값 계산 없음
  pub fn fx(inner: FxSurfaceExpr) -> Self {
    Self::Fx(Box::new(inner))
  }
}

// ─────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn test_surface_seconds_pnix_style() {
    // floor(param.system_time) % 60
    let expr = FxSurfaceExpr::infix(
      "%",
      FxSurfaceExpr::call("floor", vec![FxSurfaceExpr::ident("param.system_time")]),
      FxSurfaceExpr::float(60.0),
    );

    match expr {
      FxSurfaceExpr::InfixOp { op, left, right } => {
        assert_eq!(op, "%");
        assert!(matches!(*left, FxSurfaceExpr::Call { .. }));
        assert!(matches!(*right, FxSurfaceExpr::ConstFloat(60.0)));
      }
      _ => panic!("Expected InfixOp"),
    }
  }

  #[test]
  fn test_surface_seconds_clojure_style() {
    // (mod (floor param/system-time) 60)
    let expr = FxSurfaceExpr::call(
      "mod",
      vec![
        FxSurfaceExpr::call("floor", vec![FxSurfaceExpr::ident("param/system-time")]),
        FxSurfaceExpr::float(60.0),
      ],
    );

    match expr {
      FxSurfaceExpr::Call { func, args } => {
        assert_eq!(func, "mod");
        assert_eq!(args.len(), 2);
      }
      _ => panic!("Expected Call"),
    }
  }

  #[test]
  fn test_surface_fx_block() {
    // fx { floor(t) % 60 }
    let expr = FxSurfaceExpr::fx(FxSurfaceExpr::infix(
      "%",
      FxSurfaceExpr::call("floor", vec![FxSurfaceExpr::ident("t")]),
      FxSurfaceExpr::float(60.0),
    ));

    assert!(matches!(expr, FxSurfaceExpr::Fx(_)));
  }

  #[test]
  fn test_surface_let_binding() {
    // let x = 42 in x + 1
    let expr = FxSurfaceExpr::let_(
      "x",
      FxSurfaceExpr::int(42),
      FxSurfaceExpr::infix("+", FxSurfaceExpr::ident("x"), FxSurfaceExpr::int(1)),
    );

    match expr {
      FxSurfaceExpr::Let { name, value, body } => {
        assert_eq!(name, "x");
        assert!(matches!(*value, FxSurfaceExpr::ConstInt(42)));
        assert!(matches!(*body, FxSurfaceExpr::InfixOp { .. }));
      }
      _ => panic!("Expected Let"),
    }
  }

  #[test]
  fn test_surface_serde() {
    let expr = FxSurfaceExpr::infix("+", FxSurfaceExpr::int(1), FxSurfaceExpr::float(2.0));
    let json = serde_json::to_string(&expr).unwrap();
    let restored: FxSurfaceExpr = serde_json::from_str(&json).unwrap();

    match restored {
      FxSurfaceExpr::InfixOp { op, .. } => assert_eq!(op, "+"),
      _ => panic!("Expected InfixOp"),
    }
  }
}
