#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/license/scancode-licensedb"
OUT="$ROOT/stdlib/lib/corpus/scancode-licensedb.generated.px"
LIMIT="${SCANCODE_LICENSEDB_LIMIT:-1000}"
python3 - "$SRC" "$OUT" "$LIMIT" <<'PY'
import pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); limit=int(sys.argv[3])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for name in ['tree.json','apache-2.0.LICENSE','cc-by-4.0.LICENSE','index.json','source-manifest.json']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
data=json.loads((src/'index.json').read_text())
rows=[]; cats={}
for r in data:
    cat=r.get('category','')
    cats[cat]=cats.get(cat,0)+1
    rows.append({'license_key':r.get('license_key',''),'category':cat,'spdx_license_key':r.get('spdx_license_key',''),'other_spdx_license_keys':r.get('other_spdx_license_keys') or [],'is_exception':bool(r.get('is_exception',False)),'is_deprecated':bool(r.get('is_deprecated',False)),'json':r.get('json',''),'yaml':r.get('yaml',''),'html':r.get('html',''),'license_file':r.get('license','')})
rows=sorted(rows,key=lambda x:x['license_key'])
category_rows=[{'category':k,'count':v} for k,v in sorted(cats.items())]
obj={'schema':'license.scancode_licensedb.v1','source':'ScanCode LicenseDB index metadata','license':'CC-BY-4.0 metadata / Apache-2.0 tooling','summary':{'licenses':min(len(rows),limit),'licenses_total_seen':len(rows),'categories':len(category_rows),'exceptions':sum(1 for r in rows if r['is_exception']),'deprecated':sum(1 for r in rows if r['is_deprecated']),'limit':limit},'policy':'index metadata only; license text bodies, HTML/YAML/full JSON bodies, legal interpretation, compatibility/compliance advice, package-specific judgment, graph wiring excluded; final legal judgment Held','manifest':manifest,'files':files,'categories':category_rows,'licenses':rows[:limit]}
out.write_text('# GENERATED by scripts/gen-license-scancode-licensedb.sh. Do not edit. Gitignored.\n# Source: ScanCode LicenseDB index metadata only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: licenses={min(len(rows),limit)}/{len(rows)} bytes={out.stat().st_size}')
PY
