#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/budget/usaspending-api-catalog"
OUT="$ROOT/stdlib/lib/corpus/usaspending-api-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json,pathlib,re,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
contracts=[]
for f in manifest.get('files',[]):
    p=src/f.get('local_path','')
    txt=p.read_text(encoding='utf-8',errors='replace') if p.exists() else ''
    first_heading=None
    m=re.search(r'^#\s+(.+)$',txt,re.M)
    if m: first_heading=re.sub(r'\s+',' ',m.group(1)).strip()[:180]
    endpoints=[]
    for em in re.finditer(r'\[([A-Z ]*?)\s*(/api/v[0-9]/[^\]]+)\]',txt):
        method=(em.group(1).strip() or '').upper()
        path=em.group(2).strip()
        endpoints.append({'method':method,'path':path})
    methods=sorted(set(re.findall(r'^##\s+(GET|POST|PUT|PATCH|DELETE)\b',txt,re.M|re.I)))
    schema_keys=[]
    for km in re.finditer(r'"([A-Za-z_][A-Za-z0-9_]{1,80})"\s*:',txt):
        k=km.group(1)
        if k not in schema_keys: schema_keys.append(k)
        if len(schema_keys)>=80: break
    contracts.append({'file':f.get('path'),'bytes':f.get('bytes'),'sha256':f.get('sha256'),'title':first_heading,'endpoints':endpoints[:20],'methods':[m.upper() for m in methods],'schema_keys':schema_keys})
obj={'schema':'budget.usaspending.api_catalog.v1','source':'USAspending API contract catalog metadata','license':'CC0-1.0 / US federal public spending API documentation metadata','policy':'contract/catalog metadata only; API payload rows, award/transaction/entity values, attachments, examples/prose bodies, graph wiring excluded','summary':{'contracts':len(contracts),'endpoints':sum(len(c['endpoints']) for c in contracts),'schema_key_refs':sum(len(c['schema_keys']) for c in contracts)},'manifest':manifest,'contracts':contracts}
out.write_text('# GENERATED by scripts/gen-budget-usaspending-api-catalog.sh. Do not edit. Gitignored.\n# Source: USAspending API contract catalog metadata only; payload excluded.\n'+lit(obj)+'\n')
print(f'generated {out}: contracts={len(contracts)} endpoints={sum(len(c["endpoints"]) for c in contracts)} bytes={out.stat().st_size}')
PY
