#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/code/postgresql-sql-plan"
OUT="$ROOT/stdlib/lib/corpus/postgresql-sql-plan.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json,pathlib,re,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,(int,float)): return str(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
gram=(src/'src/backend/parser/gram.y').read_text(encoding='utf-8',errors='replace')
tokens=[]
for line in gram.splitlines():
    if line.lstrip().startswith('%token'):
        rest=re.sub(r'%token\s*(<[^>]+>)?','',line).strip()
        for name in re.findall(r'\b[A-Z][A-Z0-9_]+\b',rest):
            tokens.append({'name':name})
productions=[]
for m in re.finditer(r'^([a-zA-Z_][a-zA-Z0-9_]*)\s*:',gram,re.M):
    name=m.group(1)
    if not name.isupper(): productions.append({'name':name})
node_tags=[]; structs=[]
for p in sorted((src/'src/include/nodes').glob('*.h')):
    rel=str(p.relative_to(src))
    txt=p.read_text(encoding='utf-8',errors='replace')
    for name in re.findall(r'\b(T_[A-Za-z][A-Za-z0-9_]*)\b',txt):
        node_tags.append({'name':name,'path':rel})
    for name in re.findall(r'typedef\s+struct\s+([A-Za-z][A-Za-z0-9_]*)\b',txt):
        structs.append({'name':name,'path':rel})
tags=[]
if (src/'tags.ndjson').exists():
    for line in (src/'tags.ndjson').read_text(encoding='utf-8').splitlines():
        if line.strip():
            x=json.loads(line); tags.append({'name':x.get('name'),'commit_sha':x.get('commit_sha')})
# dedup stable
def dedup(rows, key):
    seen=set(); out=[]
    for r in rows:
        k=tuple(r.get(x) for x in key)
        if k not in seen:
            seen.add(k); out.append(r)
    return out
tokens=dedup(tokens,['name']); productions=dedup(productions,['name']); node_tags=dedup(node_tags,['name','path']); structs=dedup(structs,['name','path'])
obj={'schema':'db.postgresql.sql_plan_metadata.v1','source':'PostgreSQL SQL grammar and plan-node metadata','license':'PostgreSQL','summary':{'version_tags':len(tags),'tokens':len(tokens),'productions':len(productions),'node_tags':len(node_tags),'structs':len(structs)},'policy':'official PostgreSQL structural identifiers only; source bodies, docs prose, tests/examples, query logs, customer schemas, credentials, execution, and graph wiring excluded','manifest':manifest,'version_tags':tags,'sql_tokens':tokens,'grammar_productions':productions,'node_tags':node_tags,'node_structs':structs}
out.write_text('# GENERATED by scripts/gen-code-postgresql-sql-plan.sh. Do not edit. Gitignored.\n# Source: PostgreSQL grammar/header structural identifiers only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: tags={len(tags)} tokens={len(tokens)} productions={len(productions)} node_tags={len(node_tags)} structs={len(structs)} bytes={out.stat().st_size}')
PY
