#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/bio/ensembl-rest-catalog"
OUT="$ROOT/stdlib/lib/corpus/ensembl-rest-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json, os, pathlib, sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text())
limit=int(os.environ.get('ENSEMBL_SPECIES_LIMIT','300'))

def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
raw={}
for f in manifest.get('files',[]): raw[f['kind']]=json.loads((src/f['path']).read_text())
species=[]
all_species=raw.get('species',{}).get('species') or []
for s in all_species[:limit]:
    species.append({'name':s.get('name',''),'display_name':s.get('display_name',''),'common_name':s.get('common_name','') or '', 'taxon_id':str(s.get('taxon_id','')), 'division':s.get('division',''), 'release':s.get('release',0), 'groups':[str(x) for x in (s.get('groups') or [])]})
obj={'schema':'genome.ensembl.rest_catalog.v1','source':'Ensembl REST release/species catalog metadata','license':'Ensembl public data terms / API software Apache-2.0 where applicable','policy':'release/species catalog metadata only; gene/transcript/exon/sequence/variation/phenotype/alignment/sample payloads, genetic design guidance and graph wiring excluded','summary':{'rest_release':raw.get('rest_release',{}).get('release',''),'software_release':raw.get('software_release',{}).get('release',0),'species_stored':len(species),'species_available':len(all_species),'species_limit':limit},'manifest':manifest,'species':species}
out.write_text('# GENERATED by scripts/gen-bio-ensembl-rest-catalog.sh. Do not edit. Gitignored.\n# Source: Ensembl REST release/species metadata only; gene/transcript/sequence payloads excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: species={len(species)}/{len(all_species)} bytes={out.stat().st_size}')
PY
