#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/legal/regulationsgov-api-catalog"
OUT="$ROOT/stdlib/lib/corpus/regulationsgov-api-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import html,json,pathlib,re,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,(int,float)): return str(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
def clean(s):
    s=html.unescape(re.sub(r'<[^>]+>',' ',s)); return re.sub(r'\s+',' ',s).strip()
txt=(src/'open-gsa-doc.html').read_text(encoding='utf-8',errors='replace')
title=''
m=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
if m: title=clean(m.group(1))[:180]
links=[]
for href in re.findall(r'href=["\']([^"\']+)["\']',txt,re.I):
    if any(t in href.lower() for t in ['regulations', 'api', 'openapi', 'swagger', 'docket', 'comment', 'document']):
        links.append(href[:260])
endpoint_hints=[]
for s in re.findall(r'/(?:v4/)?(?:documents|comments|dockets|agencies|categories)[A-Za-z0-9_./?={}&%-]*',txt,re.I):
    endpoint_hints.append(s[:220])
headings=[]
for m in re.finditer(r'<h([1-6])[^>]*>(.*?)</h\1>',txt,re.I|re.S):
    headings.append({'level':int(m.group(1)),'title':clean(m.group(2))[:160]})
api_status=json.loads((src/'api-root-status.json').read_text()) if (src/'api-root-status.json').exists() else {}
static_endpoints=[
  {'path':'/v4/documents','payload':'excluded'},
  {'path':'/v4/documents/{documentId}','payload':'excluded'},
  {'path':'/v4/dockets','payload':'excluded'},
  {'path':'/v4/dockets/{docketId}','payload':'excluded'},
  {'path':'/v4/comments','payload':'excluded'},
  {'path':'/v4/comments/{commentId}','payload':'excluded'},
  {'path':'/v4/agencies','payload':'excluded'},
  {'path':'/v4/categories','payload':'excluded'}
]
obj={'schema':'legal.regulationsgov.api_catalog.v1','source':'Regulations.gov API documentation metadata','license':'US-PD / GSA public API documentation metadata','summary':{'pages':1,'links':len(set(links)),'headings':len(headings),'endpoint_hints':len(set(endpoint_hints)),'static_endpoints':len(static_endpoints)},'policy':'official OpenGSA docs metadata only; API-key-gated live payloads, docket/document/comment rows, comment text, attachments, submitter values, legal/compliance advice, and graph wiring excluded','manifest':manifest,'api_root_status':api_status,'page':{'file':'open-gsa-doc.html','title':title,'bytes':(src/'open-gsa-doc.html').stat().st_size,'links':sorted(set(links))[:100],'headings':headings[:100],'endpoint_hints':sorted(set(endpoint_hints))[:100]},'endpoints':static_endpoints}
out.write_text('# GENERATED by scripts/gen-legal-regulationsgov-api-catalog.sh. Do not edit. Gitignored.\n# Source: Regulations.gov API documentation metadata only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: endpoints={len(static_endpoints)} bytes={out.stat().st_size}')
PY
