#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/bio/rcsb-search-schema-catalog"
OUT="$ROOT/stdlib/lib/corpus/rcsb-search-schema-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json, pathlib, sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text())

def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
records=[]; total_props=0
for f in manifest.get('files',[]):
    schema=json.loads((src/f['path']).read_text())
    cats=schema.get('properties') or {}
    for cat_name, cat_schema in sorted(cats.items()):
        props=(cat_schema or {}).get('properties') or {}
        prop_records=[]
        for pname, pschema in sorted(props.items()):
            typ=pschema.get('type','') if isinstance(pschema,dict) else ''
            prop_records.append({'name':pname,'type':typ})
        total_props += len(prop_records)
        records.append({'schema_kind':f.get('kind'),'category':cat_name,'property_count':len(prop_records),'properties':prop_records[:120]})
obj={'schema':'bio.rcsb.search_schema_catalog.v1','source':'RCSB PDB Search API metadata schemas','license':'CC0-1.0 / public metadata','policy':'schema/category/property metadata only; PDB/mmCIF coordinates, structure records, sequences, ligand payloads, search results, design guidance and graph wiring excluded','summary':{'schema_files':len(manifest.get('files',[])),'categories':len(records),'properties':total_props},'manifest':manifest,'categories':records}
out.write_text('# GENERATED by scripts/gen-bio-rcsb-search-schema-catalog.sh. Do not edit. Gitignored.\n# Source: RCSB Search API schema metadata only; structure/search payload rows excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: categories={len(records)} properties={total_props} bytes={out.stat().st_size}')
PY
