#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/code/dhall-specification"
OUT="$ROOT/stdlib/lib/corpus/dhall-specification.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, re, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('$','DOLLAR_SIGN').replace('\\','\\\\').replace('"','\\"').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]; headings=[]; productions=[]
for p in sorted(src.rglob('*')):
    if p.is_file() and p.name != 'source-manifest.json': files.append({'path':str(p.relative_to(src)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
abnf=src/'standard/dhall.abnf'
if abnf.exists():
    current=None
    for line in abnf.read_text(encoding='utf-8',errors='replace').splitlines():
        if not line.strip() or line.lstrip().startswith(';'): continue
        m=re.match(r'^([A-Za-z][A-Za-z0-9_-]*)\s*=\s*(.+)$', line)
        if m:
            current=m.group(1); productions.append({'name':current,'rule':m.group(2).strip()[:180]})
        elif current and line.startswith(' '):
            pass
for p in sorted((src/'standard').glob('*.md')):
    txt=p.read_text(encoding='utf-8',errors='replace')
    rel=str(p.relative_to(src))
    for m in re.finditer(r'^(#{1,6})\s+(.+?)\s*$', txt, re.M): headings.append({'file':rel,'level':len(m.group(1)),'title':m.group(2).strip()[:120]})
obj={'schema':'config.dhall.specification.v1','source':'dhall-lang/dhall-lang standard','license':'BSD-3-Clause','summary':{'files':len(files),'productions':len(productions),'headings':len(headings)},'policy':'ABNF production metadata and headings only; prose/examples/literate code/test vectors/tool execution/graph wiring excluded','manifest':manifest,'files':files,'productions':productions,'headings':headings}
out.write_text('# GENERATED by scripts/gen-code-dhall-specification.sh. Do not edit. Gitignored.\n# Source: dhall-lang standard structural metadata.\n# Policy: ABNF productions + headings only; prose/examples/code excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: productions={len(productions)} headings={len(headings)} bytes={out.stat().st_size}')
PY
