#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/code/cue-specification"
OUT="$ROOT/stdlib/lib/corpus/cue-specification.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, re, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]; headings=[]; productions=[]
for rel in ['LICENSE','doc/ref/spec.md','doc/ref/impl.md']:
    p=src/rel
    if p.exists(): files.append({'path':rel,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
for rel in ['doc/ref/spec.md','doc/ref/impl.md']:
    p=src/rel
    if not p.exists(): continue
    txt=p.read_text(encoding='utf-8',errors='replace')
    for m in re.finditer(r'^(#{1,6})\s+(.+?)\s*$', txt, re.M): headings.append({'file':rel,'level':len(m.group(1)),'title':m.group(2).strip()[:120]})
    for block in re.findall(r'```ebnf\s*(.*?)```', txt, re.S):
        for line in block.splitlines():
            line=line.strip()
            if not line or line.startswith('//'): continue
            m=re.match(r'^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+?)(?:\s*\.\s*)?$', line)
            if m: productions.append({'file':rel,'name':m.group(1),'rule':m.group(2).strip()[:180]})
obj={'schema':'config.cue.specification.v1','source':'cue-lang/cue language specification','license':'Apache-2.0','summary':{'files':len(files),'headings':len(headings),'productions':len(productions)},'policy':'EBNF production metadata and headings only; prose/examples/config corpora/tool execution/graph wiring excluded','manifest':manifest,'files':files,'headings':headings,'productions':productions}
out.write_text('# GENERATED by scripts/gen-code-cue-specification.sh. Do not edit. Gitignored.\n# Source: cue-lang/cue spec structural metadata.\n# Policy: headings + EBNF productions only; prose/examples excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: headings={len(headings)} productions={len(productions)} bytes={out.stat().st_size}')
PY
