#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${OCSF_SCHEMA_SRC:-$ROOT/ingest/telemetry/ocsf-schema}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/ocsf-schema.generated.px}"
python3 - "$SRC" "$OUT" <<'PY'
import json,sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return json.dumps(v,ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v[k])+';' for k in sorted(v)) + ' }'
    if v is None: return 'null'
files=[]; entities=[]; attrs=[]; enum_values=[]
for rec in receipt['files']:
    path=rec['source_path']; data=json.loads((src/'raw'/rec['local_file']).read_text())
    kind=path.split('/')[0] if '/' in path else 'root'
    files.append({'source_path':path,'kind':kind,'sha256':rec['sha256'],'bytes':rec['bytes']})
    entity={'source_path':path,'kind':kind,'name':data.get('name','') or Path(path).stem,'uid':data.get('uid','') if isinstance(data.get('uid',''),(str,int)) else '','category':data.get('category','') if isinstance(data.get('category',''),str) else '','extends':data.get('extends','') if isinstance(data.get('extends',''),str) else ''}
    entities.append(entity)
    for container in ['attributes','profiles','constraints','associations']:
        obj=data.get(container)
        if isinstance(obj,dict):
            for k,v in sorted(obj.items()):
                row={'source_path':path,'entity':entity['name'],'container':container,'name':k}
                if isinstance(v,dict):
                    for kk in ['type','requirement','group','object_type','is_array','enum']:
                        if kk in v and isinstance(v[kk],(str,int,bool)): row[kk]=str(v[kk])
                    ev=v.get('enum')
                    if isinstance(ev,dict):
                        for ek,ed in sorted(ev.items()): enum_values.append({'source_path':path,'attribute':k,'key':str(ek),'value':str(ed.get('value','') if isinstance(ed,dict) else ed)})
                attrs.append(row)
obj={'schema':'telemetry.ocsf.schema.v1','source':{'name':'OCSF official schema JSON','license':'Apache-2.0','source_urls':['https://github.com/ocsf/ocsf-schema','https://github.com/ocsf/ocsf-schema/tree/'+receipt.get('ref','')],'receipt':receipt,'generator':'scripts/gen-telemetry-ocsf-schema.sh','scope':'schema JSON structural rows only; prose/real logs/PII/detection routing/execution/graph wiring excluded'},'summary':{'source_file_count':len(files),'entity_count':len(entities),'attribute_count':len(attrs),'enum_value_count':len(enum_values),'prose_ingested':False,'real_logs_or_events_ingested':False,'pii_payloads_ingested':False,'detection_or_alert_routing_enabled':False,'execution_enabled':False,'mirror_graph_wiring':False},'source_files':files,'entities':entities[:1200],'attributes':attrs[:1000],'enum_values':enum_values[:500]}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/update-telemetry-ocsf-schema.sh && scripts/gen-telemetry-ocsf-schema.sh; do not commit.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: files={len(files)} entities={len(entities)} attrs={len(attrs)} enum_values={len(enum_values)} bytes={out.stat().st_size}')
PY
