#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/math/mathml4-schema"
OUT="$ROOT/stdlib/lib/corpus/mathml4-schema.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, xml.etree.ElementTree as ET, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
XS='{http://www.w3.org/2001/XMLSchema}'
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
files=[]; rows=[]
for p in sorted(src.glob('mathml4*.xsd')):
    data=p.read_bytes(); files.append({'file':p.name,'sha256':hashlib.sha256(data).hexdigest(),'bytes':len(data)})
    root=ET.fromstring(data)
    for tag,kind in [(XS+'element','element'),(XS+'complexType','complex_type'),(XS+'simpleType','simple_type'),(XS+'attribute','attribute'),(XS+'group','group'),(XS+'attributeGroup','attribute_group'),(XS+'include','include'),(XS+'import','import')]:
        for e in root.iter(tag):
            row={'source_file':p.name,'kind':kind}
            for k in ['name','ref','type','base','substitutionGroup','schemaLocation','namespace']:
                if e.get(k): row[k]=e.get(k)
            if kind in ['complex_type','simple_type'] and not row.get('name'):
                continue
            rows.append(row)
obj={'schema':'math.mathml4_schema.v1','source':'W3C MathML 4 XSD schema files','license':'W3C-Software-Document-License-2023','summary':{'files':len(files),'rows':len(rows)},'policy':'XSD structural metadata only; annotation documentation/spec prose/examples/graph wiring excluded','files':files,'schema_rows':rows}
out.write_text('# GENERATED by scripts/gen-math-mathml4-schema.sh. Do not edit. Gitignored.\n# Source: W3C MathML 4 XSD schema files.\n# Policy: schema structure only; annotation documentation/spec prose/examples excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: files={len(files)} rows={len(rows)} bytes={out.stat().st_size}')
PY
