#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/climate/nasa-power-api-catalog"
OUT="$ROOT/stdlib/lib/corpus/nasa-power-api-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def sig(txt):
    b=txt.encode() if isinstance(txt,str) else txt
    return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def page_meta(path,page_id):
    txt=path.read_text(errors='ignore')
    mt=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
    links=[]
    for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>', txt, re.I|re.S):
        href=html.unescape(m.group(1)); label=clean(re.sub('<.*?>',' ',m.group(2)))[:180]
        if href and not href.startswith('#'):
            low=(href+' '+label).lower()
            if any(k in low for k in ['api','power','parameter','community','temporal','daily','hourly','climatology','regional','point']):
                kind='catalog_link'
                if any(k in low for k in ['api/temporal','api/application','api/system','download','json','csv']): kind='api_ref_payload_excluded'
                links.append({'kind':kind,'label':label,'href':urllib.parse.urljoin('https://power.larc.nasa.gov/',href)})
    tokens=sorted(set([x.lower() for x in re.findall(r'\b(?:POWER|API|temporal|daily|hourly|monthly|climatology|point|regional|parameters|community|ag|sb|re|solar|meteorology)\b',txt,re.I)]))
    return {'page':page_id,'file':path.name,'title':clean(re.sub('<.*?>',' ',mt.group(1)))[:220] if mt else '', 'html_sig':sig(txt),'tokens':tokens,'links':links[:160]}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
pages=[]
for name,page_id in [('api-docs.html','api_docs'),('api-pages.html','api_pages'),('tutorial-api.html','tutorial_api')]:
    p=src/name
    if p.exists(): pages.append(page_meta(p,page_id))
endpoints=[
    {'name':'point','path':'/api/temporal/{temporal}/point','requires_key':False,'payload_policy':'not called by ingest; climate/solar time-series payload excluded'},
    {'name':'regional','path':'/api/temporal/{temporal}/regional','requires_key':False,'payload_policy':'not called by ingest; gridded/regional payload excluded'},
    {'name':'parameters','path':'/api/system/manager/parameters','requires_key':False,'payload_policy':'not called by ingest; product/parameter payload excluded'},
    {'name':'communities','path':'/api/system/manager/communities','requires_key':False,'payload_policy':'not called by ingest; live payload excluded'}
]
files=[]
for p in [src/'source-manifest.json',src/'api-docs.html',src/'api-pages.html',src/'tutorial-api.html']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'climate.nasa_power.api_catalog.v1','source':'NASA POWER API documentation/catalog metadata','license':'NASA public documentation/catalog metadata; POWER/FIRMS product payloads excluded','summary':{'pages':len(pages),'links':sum(len(x['links']) for x in pages),'endpoints':len(endpoints),'files':len(files),'firms_ingested':False},'policy':'NASA POWER public documentation/catalog page metadata and endpoint tokens only; POWER climate/solar time-series values, parameter data payloads, climatology products, forecasts/life-safety decisions, FIRMS fire hotspot products, evacuation/emergency guidance, and graph wiring excluded','manifest':manifest,'files':files,'pages':pages,'endpoints':endpoints}
out.write_text('# GENERATED by scripts/gen-climate-nasa-power-api-catalog.sh. Do not edit. Gitignored.\n# Source: NASA POWER API catalog metadata only; data payloads/FIRMS/life-safety decisions excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} endpoints={len(endpoints)} bytes={out.stat().st_size}')
PY
