#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${GNIS_SRC:-$ROOT/ingest/place/gnis}"
OUT="${GNIS_OUT:-$ROOT/stdlib/lib/corpus/gnis-feature-classes.generated.px}"
python3 - <<'PY' "$SRC" "$OUT"
from html.parser import HTMLParser
import html,json,pathlib,re,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
fc_html=(src/'raw/feature-classes.html').read_text(errors='replace')
dl_html=(src/'raw/download-gnis-data.html').read_text(errors='replace')
class TableParser(HTMLParser):
 def __init__(self): super().__init__(); self.in_td=False; self.in_tr=False; self.cell=''; self.row=[]; self.rows=[]
 def handle_starttag(self,tag,attrs):
  if tag=='tr': self.in_tr=True; self.row=[]
  if tag in ('td','th') and self.in_tr: self.in_td=True; self.cell=''
 def handle_data(self,data):
  if self.in_td: self.cell+=data
 def handle_endtag(self,tag):
  if tag in ('td','th') and self.in_td:
   self.row.append(' '.join(self.cell.split())); self.in_td=False
  if tag=='tr' and self.in_tr:
   if self.row: self.rows.append(self.row)
   self.in_tr=False
p=TableParser(); p.feed(fc_html)
classes=[]
for r in p.rows:
 if not r: continue
 c=r[0].strip()
 if c and c.lower() not in ('feature class','class') and len(c) < 80:
  classes.append({'feature_class':c, 'definition_ingested':False})
seen=set(); class_rows=[]
for x in classes:
 if x['feature_class'] not in seen:
  seen.add(x['feature_class']); class_rows.append(x)
links=[]
for m in re.finditer(r'<a[^>]+href=["\']([^"\']+)["\'][^>]*>(.*?)</a>', dl_html, re.I|re.S):
 href=html.unescape(m.group(1)); text=' '.join(re.sub('<[^>]+>',' ',m.group(2)).split())
 if any(tok in href.lower() or tok in text.lower() for tok in ['download','gnis','csv','zip','txt']):
  links.append({'label':text[:120], 'href':href, 'name_rows_ingested':False})
def esc(s): s='' if s is None else str(s); return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'
def atom(v):
 if v is None: return 'null'
 if isinstance(v,bool): return 'true' if v else 'false'
 if isinstance(v,int): return str(v)
 if isinstance(v,str): return esc(v)
 if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
 if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
 raise TypeError(type(v))
seed={'schema':'place.gnis_feature_classes.v1','source':{'name':'USGS GNIS Domestic Names feature classes','license':'US-PD / public information','retrieved_at_unix':receipt.get('retrieved_at_unix')},'summary':{'feature_class_count':len(class_rows),'download_link_count':len(links),'name_rows_ingested':False,'coordinates_ingested':False,'definitions_prose_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'feature_classes':class_rows,'download_refs':links[:80]}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/gen-place-gnis-feature-classes.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: feature_classes={len(class_rows)} links={len(links)}')
PY
