#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/doc-layout/publaynet-schema-catalog"
OUT="$ROOT/stdlib/lib/corpus/publaynet-schema-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json, pathlib, re, sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
texts=[]
for p in sorted((src/'raw').glob('*.md')):
    texts.append(p.read_text(encoding='utf-8',errors='replace'))
alltxt='\n'.join(texts)
labels=[]
for label in ['text','title','list','table','figure']:
    if re.search(r'\b'+re.escape(label)+r'\b', alltxt, re.I): labels.append(label)
if len(labels)<5: labels=['text','title','list','table','figure']
counts=[]
for name,num in re.findall(r'(train|training|validation|val|test)[^0-9]{0,40}([0-9][0-9,]{2,})', alltxt, re.I):
    norm={'training':'train','validation':'val'}.get(name.lower(),name.lower())
    val=int(num.replace(',',''))
    if not any(c['name']==norm and c['count']==val for c in counts):
        counts.append({'name':norm,'count':val})
# Keep only schema-relevant asset names, not URLs/payloads.
asset_types=['document page images','layout annotation bounding boxes','polygon segmentations','PDF page release reference']
source_notes={'annotation_license':'CDLA-Permissive-1.0','image_payload_status':'excluded; IBM license file says images are not owned by IBM and use must abide by PMC OA terms','payload_downloaded':False}
obj={'schema':'doc.publaynet.layout_schema.v1','source':'PubLayNet layout dataset schema/catalog metadata','license':'CDLA-Permissive-1.0 annotations; image payloads excluded','policy':'schema/catalog metadata only; no images/PDFs/PMC article content/annotation rows/bboxes/polygons/examples/prose bodies/graph wiring','summary':{'labels':len(labels),'counts':len(counts),'asset_types':len(asset_types)},'manifest':manifest,'layout_labels':labels,'counts':counts[:20],'asset_types':asset_types,'source_notes':source_notes}
out.write_text('# GENERATED by scripts/gen-doc-publaynet-schema-catalog.sh. Do not edit. Gitignored.\n# Source: PubLayNet schema/catalog metadata only; dataset payload excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: labels={len(labels)} counts={len(counts)} bytes={out.stat().st_size}')
PY
