#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/code/python-grammar-ast"
OUT="$ROOT/stdlib/lib/corpus/python-grammar-ast.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json,pathlib,re,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,(int,float)): return str(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
gram=(src/'python.gram').read_text(encoding='utf-8',errors='replace')
asdl=(src/'Python.asdl').read_text(encoding='utf-8',errors='replace')
rules=[]
for line in gram.splitlines():
    if line.startswith('#') or not line.strip(): continue
    m=re.match(r'^([a-zA-Z_][a-zA-Z0-9_]*)\s*(?:\[[^\]]+\])?\s*:',line)
    if m:
        name=m.group(1)
        kind='token_ref' if name.isupper() else 'grammar_rule'
        rules.append({'name':name,'kind':kind})
constructors=[]
current_sum=None
for raw in asdl.splitlines():
    line=raw.split('--',1)[0].strip()
    if not line or line.startswith('module ') or line in ('{','}'): continue
    m=re.match(r'^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$',line)
    if m:
        current_sum=m.group(1)
        rhs=m.group(2)
    else:
        rhs=line
    for part in re.split(r'\s*\|\s*',rhs):
        cm=re.match(r'([A-Za-z_][A-Za-z0-9_]*)(?:\(([^)]*)\))?',part.strip())
        if cm and current_sum:
            fields=[]
            if cm.group(2):
                for f in cm.group(2).split(','):
                    bits=f.strip().split()
                    if len(bits)>=2:
                        fields.append({'type':bits[0], 'name':bits[1].rstrip('?*')})
            constructors.append({'sum':current_sum,'constructor':cm.group(1),'fields':fields})
# bounded full tag catalog metadata: tag name + commit sha only
tags=[]
if (src/'tags.ndjson').exists():
    for line in (src/'tags.ndjson').read_text(encoding='utf-8').splitlines():
        if line.strip():
            x=json.loads(line)
            tags.append({'name':x.get('name'), 'commit_sha':x.get('commit_sha')})
obj={'schema':'code.python.grammar_ast.v1','source':'CPython grammar and AST schema metadata','license':'PSF-2.0','summary':{'grammar_rules':len(rules),'ast_constructors':len(constructors),'version_tags':len(tags)},'policy':'CPython tag catalog and structural grammar/ASDL identifiers only; runtime source bodies, prose, examples, PyPI/user code, execution, and graph wiring excluded','manifest':manifest,'version_tags':tags,'grammar_rules':rules,'ast_constructors':constructors}
out.write_text('# GENERATED by scripts/gen-code-python-grammar-ast.sh. Do not edit. Gitignored.\n# Source: CPython grammar/ASDL structural identifiers + version tag catalog only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: rules={len(rules)} ast={len(constructors)} tags={len(tags)} bytes={out.stat().st_size}')
PY
