#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/transport/nhtsa-recalls-api"
OUT="$ROOT/stdlib/lib/corpus/nhtsa-recalls-api.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,float): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def typ(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'bool'
    if isinstance(v,int): return 'int'
    if isinstance(v,float): return 'float'
    if isinstance(v,str): return 'string'
    if isinstance(v,list): return 'list'
    if isinstance(v,dict): return 'object'
    return type(v).__name__
def walk(v,path,out):
    out.setdefault(path or '$',set()).add(typ(v))
    if isinstance(v,dict):
        for k,val in v.items(): walk(val,(path+'.' if path else '')+str(k),out)
    elif isinstance(v,list):
        out.setdefault((path or '$')+'[]',set()).add('item')
        for item in v[:3]: walk(item,(path or '$')+'[]',out)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for p in [src/'source-manifest.json', src/'recalls_by_vehicle.json']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
j=json.loads((src/'recalls_by_vehicle.json').read_text())
paths={}; walk(j,'',paths)
rows=[]
for r in j.get('results') or j.get('Results') or []:
    rows.append({'campaign_number':r.get('NHTSACampaignNumber',''),'manufacturer':r.get('Manufacturer',''),'component':r.get('Component',''),'report_received_date':r.get('ReportReceivedDate',''),'park_it':bool(r.get('parkIt',False)),'park_outside':bool(r.get('parkOutSide',False)),'over_the_air_update':bool(r.get('overTheAirUpdate',False))})
obj={'schema':'transport.nhtsa_recalls.api_schema.v1','source':'NHTSA Recalls API bounded metadata','license':'US-PD / US federal public API metadata','summary':{'recalls':len(rows),'api_count':int(j.get('Count') or j.get('count') or 0),'make':manifest.get('make',''),'model':manifest.get('model',''),'model_year':manifest.get('model_year','')},'policy':'bounded recall campaign metadata and schema only; VINs, complaints, ODI narratives, summary/consequence/remedy/notes prose bodies, repair/diagnostic advice, legal/compliance decisions, safety recommendations, runtime dependency, graph wiring excluded','manifest':manifest,'files':files,'endpoint_schema':{'endpoint':'recalls_by_vehicle','response_sha256':hashlib.sha256((src/'recalls_by_vehicle.json').read_bytes()).hexdigest(),'response_bytes':(src/'recalls_by_vehicle.json').stat().st_size,'key_paths':[{'path':k,'types':sorted(v)} for k,v in sorted(paths.items())]},'recalls':rows}
out.write_text('# GENERATED by scripts/gen-transport-nhtsa-recalls-api.sh. Do not edit. Gitignored.\n# Source: NHTSA Recalls API bounded campaign metadata only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: recalls={len(rows)} bytes={out.stat().st_size}')
PY
