#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${PROM_DATA_MODEL_SRC:-$ROOT/ingest/telemetry/prometheus-data-model}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/prometheus-data-model.generated.px}"
python3 - "$SRC" "$OUT" <<'PY'
import json,re,sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return json.dumps(v,ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v[k])+';' for k in sorted(v)) + ' }'
    if v is None: return 'null'
source_files=[]; go_types=[]; go_consts=[]; go_funcs=[]; headings=[]; tokens=[]
for rec in receipt['files']:
    source_files.append({'file':rec['file'],'sha256':rec['sha256'],'bytes':rec['bytes'],'role':rec['role']})
    text=(src/'raw'/rec['file']).read_text(encoding='utf-8',errors='replace')
    if rec['file'].endswith('.go'):
        for m in re.finditer(r'^type\s+(\w+)\s+([^\n{]+)',text,re.M): go_types.append({'file':rec['file'],'name':m.group(1),'base':m.group(2).strip()[:80]})
        for m in re.finditer(r'^\s*(\w+)\s+(?:[A-Za-z0-9_.*\[\]]+\s*)?=\s*(?:iota|"[^"]*"|[0-9]+)',text,re.M): go_consts.append({'file':rec['file'],'name':m.group(1)})
        for m in re.finditer(r'^func\s+(?:\([^)]*\)\s*)?(\w+)\s*\(',text,re.M): go_funcs.append({'file':rec['file'],'name':m.group(1)})
    else:
        for line in text.splitlines():
            hm=re.match(r'^(#{1,6})\s+(.+?)\s*$',line)
            if hm: headings.append({'file':rec['file'],'level':len(hm.group(1)),'title':hm.group(2)[:160]})
            for bt in re.findall(r'`([^`]{1,100})`',line):
                if not any(c.isspace() for c in bt): tokens.append({'file':rec['file'],'token':bt})
seen=set(); toks=[]
for t in tokens:
    k=(t['file'],t['token'])
    if k not in seen: seen.add(k); toks.append(t)
obj={'schema':'telemetry.prometheus.data_model.v1','source':{'name':'Prometheus data model structural metadata','license':'Apache-2.0','source_urls':['https://github.com/prometheus/prometheus','https://github.com/prometheus/prometheus/tree/'+receipt.get('ref','')],'receipt':receipt,'generator':'scripts/gen-telemetry-prometheus-data-model.sh','scope':'structural identifiers only; Go/prose bodies/real telemetry/alert routing/execution/graph wiring excluded'},'summary':{'source_file_count':len(source_files),'go_type_count':len(go_types),'go_const_count':len(go_consts),'go_func_count':len(go_funcs),'heading_count':len(headings),'token_count':len(toks),'source_bodies_ingested':False,'prose_bodies_ingested':False,'real_metrics_ingested':False,'scrape_logs_or_credentials_ingested':False,'alert_routing_enabled':False,'execution_enabled':False,'mirror_graph_wiring':False},'source_files':source_files,'go_types':go_types,'go_consts':go_consts[:500],'go_funcs':go_funcs[:300],'section_headings':headings[:200],'tokens':toks[:500]}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/update-telemetry-prometheus-data-model.sh && scripts/gen-telemetry-prometheus-data-model.sh; do not commit.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: types={len(go_types)} consts={len(go_consts)} funcs={len(go_funcs)} headings={len(headings)} tokens={len(toks)} bytes={out.stat().st_size}')
PY
