#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/governance/service-guidance-catalog"
OUT="$ROOT/stdlib/lib/corpus/service-guidance-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import html, json, os, pathlib, re, sys, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text())
limit=int(os.environ.get('SERVICE_GUIDANCE_LINK_LIMIT','180'))

def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))

def clean(s): return html.unescape(re.sub(r'\s+',' ',re.sub('<[^>]+>',' ',s))).strip()
pages=[]; links=[]; paths=[]
for f in manifest.get('files',[]):
    if f.get('kind')=='html_page' and f.get('path'):
        text=(src/f['path']).read_text(encoding='utf-8',errors='replace')
        title=''
        m=re.search(r'(?is)<title[^>]*>(.*?)</title>',text)
        if m: title=clean(m.group(1))[:160]
        headings=[]
        for hm in re.finditer(r'(?is)<h([1-3])[^>]*>(.*?)</h\1>',text):
            h=clean(hm.group(2))
            if h and len(headings)<80: headings.append({'level':int(hm.group(1)),'text':h[:160]})
        page_links=[]
        for lm in re.finditer(r'(?is)<a\s+[^>]*href="([^"]+)"[^>]*>(.*?)</a>',text):
            href=html.unescape(lm.group(1)); label=clean(lm.group(2))
            if not href or not label or len(label)>180: continue
            url=urllib.parse.urljoin(f['url'],href)
            if any(x in url.lower() for x in ['javascript:', 'mailto:']): continue
            page_links.append({'source_id':f.get('source_id'),'label':label[:160],'url':url})
            if len(page_links)>=limit: break
        pages.append({'source_id':f.get('source_id'),'label':f.get('label'),'license':f.get('license'),'url':f.get('url'),'title':title,'heading_count':len(headings),'link_count':len(page_links),'headings':headings})
        links.extend(page_links)
    elif f.get('kind')=='pdf_head_only':
        pages.append({'source_id':f.get('source_id'),'label':f.get('label'),'license':f.get('license'),'url':f.get('url'),'title':f.get('label'),'heading_count':0,'link_count':0,'pdf_bytes':f.get('bytes',0),'content_type':f.get('content_type',''),'head_only':True,'headings':[ ]})
    elif f.get('kind')=='github_tree_json' and f.get('path'):
        tree=json.loads((src/f['path']).read_text())
        for item in (tree.get('tree') or [])[:500]:
            path=item.get('path','')
            if not path: continue
            if item.get('type')!='blob': continue
            if not re.search(r'\.(md|html|njk|json|yml|yaml)$',path): continue
            paths.append({'source_id':'18f_guides','path':path,'type':item.get('type',''),'size':item.get('size',0)})
obj={'schema':'service.guidance_catalog.v1','source':'NASA/USDS/18F/GOV.UK public guidance catalog metadata','license':'Mixed US-PD/CC0/OGL-3.0; source-specific license metadata preserved, GOV.UK attribution required','policy':'page heading/link/path metadata only; handbook/playbook/manual prose bodies, PDF bodies, examples/templates/source code/assets, policy execution, runtime service/user data and graph wiring excluded','summary':{'pages':len(pages),'links':len(links),'paths':len(paths)},'manifest':manifest,'pages':pages,'links':links,'paths':paths}
out.write_text('# GENERATED by scripts/gen-governance-service-guidance-catalog.sh. Do not edit. Gitignored.\n# Source: public guidance page/link/path metadata only; prose/PDF/template/source-code bodies excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} links={len(links)} paths={len(paths)} bytes={out.stat().st_size}')
PY
