#!/usr/bin/env bash
set -euo pipefail
ROOT="${PNIX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
YEAR="${COD_YEAR:-$(date -u +%Y)}"
SRC="${COD_SOURCE:-$ROOT/ingest/materials/cod/cod-$YEAR-result.json}"
OUT="${COD_OUT:-$ROOT/stdlib/lib/corpus/cod.generated.px}"
LIMIT="${COD_RECORD_LIMIT:-300}"
if [ ! -f "$SRC" ]; then
  echo "missing COD source: $SRC" >&2
  echo "run: scripts/update-materials-cod.sh" >&2
  exit 1
fi
mkdir -p "$(dirname "$OUT")"
python3 - "$SRC" "$OUT" "$LIMIT" <<'PY'
import hashlib, json, sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2]); limit=int(sys.argv[3])

def q(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')+'"'

def lit(v, indent=0):
    sp=' '*indent
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,(int,float)) and not isinstance(v,bool): return repr(v)
    if v is None: return 'null'
    if isinstance(v,str): return q(v)
    if isinstance(v,list):
        if not v: return '[ ]'
        return '[\n'+''.join(' '*(indent+2)+lit(x, indent+2)+'\n' for x in v)+sp+']'
    if isinstance(v,dict):
        if not v: return '{ }'
        lines=['{']
        for k in v:
            lines.append(' '*(indent+2)+k+' = '+lit(v[k], indent+2)+';')
        lines.append(sp+'}')
        return '\n'.join(lines)
    raise TypeError(type(v))

def clean(v):
    return None if v in (None,'','?') else v

def put(src, dst, k, outk=None):
    v=clean(src.get(k))
    if v is not None:
        dst[outk or k] = v

data=json.load(src.open())
records=[]
for r in data[:limit]:
    rec={}
    for k in ['file','formula','calcformula','cellformula','nel','sg','sgHall','sgNumber','a','b','c','alpha','beta','gamma','vol','Z','Zprime','celltemp','diffrtemp','cellpressure','diffrpressure','method','radiation','wavelength','radType','radSymbol','journal','year','doi','date','time']:
        put(r, rec, k)
    if rec:
        records.append(rec)
sha=hashlib.sha256(src.read_bytes()).hexdigest()
value={
  'schema':'materials.cod.v1',
  'source':'Crystallography Open Database REST result',
  'license':'CC0-1.0',
  'source_url':'https://www.crystallography.net/cod/result?format=json&year=<year>',
  'source_sha256':sha,
  'record_limit':limit,
  'total_records_seen':len(data),
  'records':records,
}
out.write_text('# GENERATED by scripts/gen-materials-cod.sh; do not commit.\n'+lit(value)+'\n', encoding='utf-8')
print(f"generated {out}: records={len(records)} total={len(data)} sha256={sha}")
PY
