#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/code/json-schema-specification"
OUT="$ROOT/stdlib/lib/corpus/json-schema-specification.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for name in ['rfc8259.txt','LICENSE','meta.schema.json']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
meta=json.loads((src/'meta.schema.json').read_text(encoding='utf-8'))
properties=[]; defs=[]; refs=[]; required=[]; enums=[]; types=[]
def type_token(v):
    if isinstance(v,str): return [v]
    if isinstance(v,list): return [str(x) for x in v if isinstance(x,str)]
    return []
def walk(node,path):
    if isinstance(node,dict):
        for t in type_token(node.get('type')):
            types.append({'path':path,'type':t})
        if '$ref' in node: refs.append({'path':path,'ref':str(node.get('$ref'))})
        if '$dynamicRef' in node: refs.append({'path':path,'ref':str(node.get('$dynamicRef')),'dynamic':True})
        if 'required' in node and isinstance(node['required'],list):
            for r in node['required']: required.append({'path':path,'field':str(r)})
        if 'enum' in node and isinstance(node['enum'],list):
            for e in node['enum'][:80]: enums.append({'path':path,'token':str(e)[:80]})
        if 'const' in node: enums.append({'path':path,'token':str(node['const'])[:80],'const':True})
        if path.endswith('/properties') and isinstance(node,dict):
            for k,v in node.items(): properties.append({'keyword':k,'path':path+'/'+k,'types':type_token(v.get('type')) if isinstance(v,dict) else []})
        if path.endswith('/$defs') and isinstance(node,dict):
            for k,v in node.items(): defs.append({'name':k,'types':type_token(v.get('type')) if isinstance(v,dict) else []})
        for k,v in node.items():
            if k in ('description','$comment','title','examples'): continue
            walk(v, path+'/'+k)
    elif isinstance(node,list):
        for i,v in enumerate(node): walk(v, path+'/'+str(i))
walk(meta,'')
json_tokens=[{'name':'object'},{'name':'array'},{'name':'number'},{'name':'string'},{'name':'boolean'},{'name':'null'},{'name':'true'},{'name':'false'}]
obj={'schema':'config.json_schema.specification.v1','source':'RFC 8259 JSON + JSON Schema meta-schema','license':'IETF-RFC + BSD-3-Clause/AFL-3.0','summary':{'files':len(files),'json_tokens':len(json_tokens),'properties':len(properties),'defs':len(defs),'refs':len(refs),'required':len(required),'enums':len(enums),'types':len(types)},'policy':'syntax/schema structural metadata only; prose/comment/description/example values, test-suite, catalogs, real documents, execution, graph wiring excluded','manifest':manifest,'schema_id':meta.get('$id',''),'schema_schema':meta.get('$schema',''),'files':files,'json_tokens':json_tokens,'properties':properties,'defs':defs,'refs':refs[:400],'required_fields':required[:400],'enum_tokens':enums[:400],'type_tokens':types[:800]}
out.write_text('# GENERATED by scripts/gen-code-json-schema-specification.sh. Do not edit. Gitignored.\n# Source: RFC 8259 hash + JSON Schema official meta.schema.json structure.\n# Policy: structural metadata only; prose/comment/description/example/test-suite/catalogs excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: properties={len(properties)} defs={len(defs)} refs={len(refs)} bytes={out.stat().st_size}')
PY
