#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/units/bipm-si-brochure"
OUT="$ROOT/stdlib/lib/corpus/bipm-si-brochure.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
p=src/'source-manifest.json'
if p.exists(): manifest=json.loads(p.read_text(encoding='utf-8'))
base_units=[
 {'symbol':'s','name':'second','quantity':'time'}, {'symbol':'m','name':'metre','quantity':'length'}, {'symbol':'kg','name':'kilogram','quantity':'mass'},
 {'symbol':'A','name':'ampere','quantity':'electric_current'}, {'symbol':'K','name':'kelvin','quantity':'thermodynamic_temperature'},
 {'symbol':'mol','name':'mole','quantity':'amount_of_substance'}, {'symbol':'cd','name':'candela','quantity':'luminous_intensity'}]
derived_units=[
 {'symbol':'rad','name':'radian','quantity':'plane_angle'}, {'symbol':'sr','name':'steradian','quantity':'solid_angle'}, {'symbol':'Hz','name':'hertz','quantity':'frequency'},
 {'symbol':'N','name':'newton','quantity':'force'}, {'symbol':'Pa','name':'pascal','quantity':'pressure_stress'}, {'symbol':'J','name':'joule','quantity':'energy_work_heat'},
 {'symbol':'W','name':'watt','quantity':'power_radiant_flux'}, {'symbol':'C','name':'coulomb','quantity':'electric_charge'}, {'symbol':'V','name':'volt','quantity':'electric_potential'},
 {'symbol':'F','name':'farad','quantity':'capacitance'}, {'symbol':'ohm','name':'ohm','quantity':'electric_resistance'}, {'symbol':'S','name':'siemens','quantity':'electric_conductance'},
 {'symbol':'Wb','name':'weber','quantity':'magnetic_flux'}, {'symbol':'T','name':'tesla','quantity':'magnetic_flux_density'}, {'symbol':'H','name':'henry','quantity':'inductance'},
 {'symbol':'degC','name':'degree Celsius','quantity':'celsius_temperature'}, {'symbol':'lm','name':'lumen','quantity':'luminous_flux'}, {'symbol':'lx','name':'lux','quantity':'illuminance'},
 {'symbol':'Bq','name':'becquerel','quantity':'activity_referred_to_radionuclide'}, {'symbol':'Gy','name':'gray','quantity':'absorbed_dose'}, {'symbol':'Sv','name':'sievert','quantity':'dose_equivalent'}, {'symbol':'kat','name':'katal','quantity':'catalytic_activity'}]
prefixes=[
 ('Q','quetta','30'),('R','ronna','27'),('Y','yotta','24'),('Z','zetta','21'),('E','exa','18'),('P','peta','15'),('T','tera','12'),('G','giga','9'),('M','mega','6'),('k','kilo','3'),('h','hecto','2'),('da','deca','1'),
 ('d','deci','-1'),('c','centi','-2'),('m','milli','-3'),('u','micro','-6'),('n','nano','-9'),('p','pico','-12'),('f','femto','-15'),('a','atto','-18'),('z','zepto','-21'),('y','yocto','-24'),('r','ronto','-27'),('q','quecto','-30')]
constants=[
 {'symbol':'Delta_nu_Cs','name':'caesium_133_hyperfine_transition_frequency','value':'9192631770','unit':'Hz'},
 {'symbol':'c','name':'speed_of_light_in_vacuum','value':'299792458','unit':'m s^-1'},
 {'symbol':'h','name':'Planck_constant','value':'6.62607015e-34','unit':'J s'},
 {'symbol':'e','name':'elementary_charge','value':'1.602176634e-19','unit':'C'},
 {'symbol':'k','name':'Boltzmann_constant','value':'1.380649e-23','unit':'J K^-1'},
 {'symbol':'N_A','name':'Avogadro_constant','value':'6.02214076e23','unit':'mol^-1'},
 {'symbol':'K_cd','name':'luminous_efficacy_540_THz','value':'683','unit':'lm W^-1'}]
obj={'schema':'units.bipm_si_brochure.v1','source':'BIPM SI Brochure 9th edition v4.01','license':'CC-BY-4.0','summary':{'base_units':len(base_units),'derived_units':len(derived_units),'prefixes':len(prefixes),'defining_constants':len(constants)},'policy':'closed SI code tables only; brochure prose/logo/promotion assets/graph wiring excluded','manifest':manifest,'base_units':base_units,'derived_units':derived_units,'prefixes':[{'symbol':s,'name':n,'power10':p} for s,n,p in prefixes],'defining_constants':constants}
out.write_text('# GENERATED by scripts/gen-units-bipm-si-brochure.sh. Do not edit. Gitignored.\n# Source: BIPM SI Brochure code tables.\n# Policy: closed SI unit/prefix/constant metadata only; prose/logo assets excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: base={len(base_units)} derived={len(derived_units)} prefixes={len(prefixes)} constants={len(constants)} bytes={out.stat().st_size}')
PY
