#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/agriculture/usda-grin-catalog"
OUT="$ROOT/stdlib/lib/corpus/usda-grin-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def sig(txt):
    b=txt.encode() if isinstance(txt,str) else txt
    return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def page_meta(path,page_id):
    txt=path.read_text(errors='ignore')
    mt=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
    links=[]
    for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>', txt, re.I|re.S):
        href=html.unescape(m.group(1)); label=clean(re.sub('<.*?>',' ',m.group(2)))[:180]
        if href and not href.startswith('#'):
            low=(href+' '+label).lower()
            if any(k in low for k in ['gringlobal','taxonomy','descriptor','search','crop','accession','inventory']):
                links.append({'label':label,'href':urllib.parse.urljoin('https://npgsweb.ars-grin.gov/gringlobal/',href)})
    fields=[]
    for m in re.finditer(r'<(?:input|select|textarea)\b([^>]*)>', txt, re.I|re.S):
        attrs=m.group(1)
        nm=re.search(r'\bname=["\']([^"\']+)',attrs,re.I)
        typ=re.search(r'\btype=["\']([^"\']+)',attrs,re.I)
        if nm:
            name=nm.group(1)
            if not name.startswith('__'):
                fields.append({'name':name[:120],'type':(typ.group(1) if typ else '').lower()[:40]})
    uniq=[]; seen=set()
    for f in fields:
        k=(f['name'],f['type'])
        if k not in seen:
            seen.add(k); uniq.append(f)
    return {'page':page_id,'file':path.name,'title':clean(re.sub('<.*?>',' ',mt.group(1)))[:220] if mt else '', 'html_sig':sig(txt),'form_fields':uniq[:160],'links':links[:120]}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
pages=[]
for name,page_id in [('search.html','search'),('taxonomysearch.html','taxonomy_search'),('descriptors.html','descriptors')]:
    p=src/name
    if p.exists(): pages.append(page_meta(p,page_id))
files=[]
for p in [src/'source-manifest.json',src/'search.html',src/'taxonomysearch.html',src/'descriptors.html']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'agriculture.usda_grin.catalog.v1','source':'USDA GRIN-Global public catalog/search metadata','license':'US-PD / US federal public information','summary':{'pages':len(pages),'form_fields':sum(len(x['form_fields']) for x in pages),'links':sum(len(x['links']) for x in pages),'files':len(files)},'policy':'official GRIN-Global search/catalog page metadata only; germplasm accession rows, taxonomy result payloads, descriptor/trait values, precise provenance/locality values, GMO/breeding design guidance, and graph wiring excluded','manifest':manifest,'files':files,'pages':pages}
out.write_text('# GENERATED by scripts/gen-agriculture-usda-grin-catalog.sh. Do not edit. Gitignored.\n# Source: USDA GRIN catalog/search metadata only; germplasm payloads/trait values/breeding guidance excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} fields={obj["summary"]["form_fields"]} links={obj["summary"]["links"]} bytes={out.stat().st_size}')
PY
