#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/ui/carbon-catalog"
OUT="$ROOT/stdlib/lib/corpus/carbon-catalog.generated.px"
LIMIT="${CARBON_COMPONENT_LIMIT:-500}"
python3 - "$SRC" "$OUT" "$LIMIT" <<'PY'
import pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); limit=int(sys.argv[3])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
tree=json.loads((src/'tree.json').read_text())
files=[]
for name in ['tree.json','LICENSE']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
components={}; token_files=[]; package_roots={}
for row in tree.get('tree',[]):
    path=row.get('path','')
    if row.get('type')!='blob': continue
    if any(path.endswith(ext) for ext in ['.png','.jpg','.jpeg','.gif','.webp','.mp4','.svg','.ico','.snap']): continue
    parts=path.split('/')
    if len(parts)>=2 and parts[0]=='packages':
        package_roots[parts[1]]=package_roots.get(parts[1],0)+1
    if len(parts)>=5 and parts[:3]==['packages','react','src'] and parts[3]=='components':
        name=parts[4]
        e=components.setdefault(name, {'name':name,'mdx_files':0,'story_files':0,'test_files':0,'source_files':0,'style_files':0,'index_files':0})
        if path.endswith('.mdx'): e['mdx_files']+=1
        elif '.stories.' in path: e['story_files']+=1
        elif '/__tests__/' in path or path.endswith(('-test.tsx','-test.js','.test.tsx','.test.js')): e['test_files']+=1
        elif path.endswith(('.tsx','.ts','.jsx','.js')): e['source_files']+=1
        elif path.endswith(('.scss','.css')): e['style_files']+=1
        if parts[-1].startswith('index.'): e['index_files']+=1
    elif path.startswith(('packages/themes/scss/','packages/styles/scss/')):
        if '/__tests__/' in path or '/__snapshots__/' in path: continue
        if path.endswith(('.scss','.css','.js','.ts','.json')):
            token_files.append({'path':path,'package':parts[1] if len(parts)>1 else '', 'kind':path.rsplit('.',1)[-1]})
component_rows=list(sorted(components.values(), key=lambda x:x['name']))[:limit]
token_rows=sorted(token_files, key=lambda x:x['path'])[:1000]
packages=[{'name':k,'blob_count':v} for k,v in sorted(package_roots.items())]
obj={'schema':'ui.carbon.catalog.v1','source':'Carbon Design System repository tree catalog','license':'Apache-2.0','summary':{'components':len(component_rows),'components_total_seen':len(components),'token_files':len(token_rows),'token_files_total_seen':len(token_files),'packages':len(packages),'limit':limit},'policy':'path/name/count catalog metadata only; docs prose, source/style/icon bodies, assets, examples, runtime rendering, graph wiring excluded','manifest':manifest,'files':files,'packages':packages,'components':component_rows,'token_files':token_rows}
out.write_text('# GENERATED by scripts/gen-ui-carbon-catalog.sh. Do not edit. Gitignored.\n# Source: Carbon Design System repository tree path metadata.\n# Policy: component/token catalog only; prose/assets/code bodies/execution excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: components={len(component_rows)}/{len(components)} token_files={len(token_rows)}/{len(token_files)} bytes={out.stat().st_size}')
PY
