#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${PRONOM_DROID_SRC:-$ROOT/ingest/registry/pronom-droid}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/pronom-droid.generated.px}"
FORMAT_LIMIT="${PRONOM_DROID_FORMAT_LIMIT:-400}"
SEQ_LIMIT="${PRONOM_DROID_SEQUENCE_LIMIT:-800}"
python3 - "$SRC" "$OUT" "$FORMAT_LIMIT" "$SEQ_LIMIT" <<'PY'
import json, sys, xml.etree.ElementTree as ET
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2]); format_limit=int(sys.argv[3]); seq_limit=int(sys.argv[4])
receipt=json.loads((src/'source-receipt.json').read_text())
root=ET.parse(src/'raw/DROID_SignatureFile.xml').getroot()
ns={'p':'http://www.nationalarchives.gov.uk/pronom/SignatureFile'}

def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,(int,float)): return repr(v)
    if isinstance(v,str): return json.dumps(v, ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))
formats=[]; sequences=[]
all_formats=root.findall('.//p:FileFormat', ns)
all_sigs=root.findall('.//p:InternalSignature', ns)
for ff in all_formats[:format_limit if format_limit>0 else None]:
    exts=[(x.text or '').strip() for x in ff.findall('p:Extension', ns) if (x.text or '').strip()]
    sigs=[x.attrib.get('ID','') for x in ff.findall('p:InternalSignatureID', ns)]
    formats.append({'puid':ff.attrib.get('PUID',''),'name':ff.attrib.get('Name',''),'version':ff.attrib.get('Version',''),'mime_type':ff.attrib.get('MIMEType',''),'extensions':exts,'internal_signature_ids':sigs})
for sig in all_sigs:
    sid=sig.attrib.get('ID','')
    specificity=sig.attrib.get('Specificity','')
    for bs in sig.findall('p:ByteSequence', ns):
        ref=bs.attrib.get('Reference','')
        for sub in bs.findall('p:SubSequence', ns):
            if seq_limit>0 and len(sequences)>=seq_limit:
                break
            seq=(sub.findtext('p:Sequence', default='', namespaces=ns) or '').strip()
            sequences.append({'internal_signature_id':sid,'specificity':specificity,'reference':ref,'position':sub.attrib.get('Position',''),'min_offset':sub.attrib.get('SubSeqMinOffset',''),'max_offset':sub.attrib.get('SubSeqMaxOffset',''),'sequence':seq})
        if seq_limit>0 and len(sequences)>=seq_limit:
            break
    if seq_limit>0 and len(sequences)>=seq_limit:
        break
seed={'schema':'registry.pronom_droid.v1','source':{'name':'PRONOM DROID Signature File','license':'OGL-UK-3.0','version':receipt.get('version'),'retrieved_at':receipt.get('retrieved_at')},'summary':{'format_count':len(formats),'signature_sequence_count':len(sequences),'total_available_format_count':len(all_formats),'total_available_internal_signature_count':len(all_sigs),'format_limit':format_limit,'sequence_limit':seq_limit,'accepted_truth':False,'document_payloads_ingested':False,'sample_files_ingested':False,'parser_execution':False,'mirror_graph_wiring':False},'source_receipt':receipt,'signature_file':{'version':root.attrib.get('Version',''),'date_created':root.attrib.get('DateCreated','')},'formats':formats,'signature_sequences':sequences}
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('# GENERATED by scripts/gen-registry-pronom-droid.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: formats={len(formats)}/{len(all_formats)}, sequences={len(sequences)}')
PY
