#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${NIST_SP800_63_SRC:-$ROOT/ingest/security/nist-sp800-63-assurance-levels}"
OUT="${NIST_SP800_63_OUT:-$ROOT/stdlib/lib/corpus/nist-sp800-63-assurance-levels.generated.px}"
python3 - <<'PY' "$SRC" "$OUT"
import json,pathlib,re,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
docs=[('sp800-63','Digital Identity Guidelines','overall'),('sp800-63a','Identity Proofing','identity_proofing'),('sp800-63b','Authentication and Authenticator Management','authentication'),('sp800-63c','Federation and Assertions','federation')]
doc_rows=[]
for code,title,scope in docs:
    p=src/f'raw/{code}.html'; html=p.read_text(errors='replace')
    doc_rows.append({'doc':code.upper(),'title':title,'scope':scope,'url':f'https://pages.nist.gov/800-63-4/{code}.html','source_file':p.name,'mentions_ial':'IAL' in html,'mentions_aal':'AAL' in html,'mentions_fal':'FAL' in html,'body_text_ingested':False})
levels=[]
for family,scope in [('IAL','identity_proofing'),('AAL','authentication'),('FAL','federation')]:
    for level in [1,2,3]:
        levels.append({'code':f'{family}{level}','family':family,'level':level,'scope':scope,'source_suite':'SP800-63-4','requirement_prose_ingested':False,'risk_decision_ingested':False})
def esc(s): s='' if s is None else str(s); return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'
def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return esc(v)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))
seed={'schema':'security.nist_sp800_63_assurance_levels.v1','source':{'name':'NIST SP 800-63-4 assurance-level metadata','license':'US-PD / NIST public publication metadata','retrieved_at_unix':receipt.get('retrieved_at_unix')},'summary':{'document_count':len(doc_rows),'assurance_level_count':len(levels),'families':['IAL','AAL','FAL'],'requirement_prose_ingested':False,'compliance_advice_ingested':False,'auth_policy_ingested':False,'privilege_bypass_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'documents':doc_rows,'assurance_levels':levels}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/gen-security-nist-sp800-63-assurance-levels.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: documents={len(doc_rows)}, assurance_levels={len(levels)}')
PY
