#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/water/epa-echo-sdwa-api-catalog"
OUT="$ROOT/stdlib/lib/corpus/epa-echo-sdwa-api-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def sig(txt):
    b=txt.encode() if isinstance(txt,str) else txt
    return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def page_meta(path,page_id):
    txt=path.read_text(errors='ignore')
    mt=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
    links=[]
    for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>', txt, re.I|re.S):
        href=html.unescape(m.group(1)); label=clean(re.sub('<.*?>',' ',m.group(2)))[:220]
        if href and not href.startswith('#'):
            low=(href+' '+label).lower()
            if any(k in low for k in ['drinking','sdwa','sdwis','water system','facility-search-drinking-water','web-services','safe drinking']):
                kind='catalog_link'
                if any(k in low for k in ['rest','services','data','search']): kind='api_ref_payload_excluded'
                links.append({'kind':kind,'label':label,'href':urllib.parse.urljoin('https://echo.epa.gov/tools/web-services',href)})
    tokens=sorted(set([x.lower() for x in re.findall(r'\b(?:SDWA|SDWIS|drinking water|Safe Drinking Water Act|public drinking water systems|facility search|REST|JSON|XML)\b',txt,re.I)]))
    return {'page':page_id,'file':path.name,'title':clean(re.sub('<.*?>',' ',mt.group(1)))[:220] if mt else '', 'html_sig':sig(txt),'tokens':tokens,'links':links[:120]}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
pages=[]
for name,page_id in [('web-services.html','web_services'),('sdwa-docs.html','sdwa_docs')]:
    p=src/name
    if p.exists(): pages.append(page_meta(p,page_id))
endpoints=[{'name':'drinking_water_system_search','method':'GET','docs_url':'https://echo.epa.gov/tools/web-services/facility-search-drinking-water','source_system':'SDWIS/Fed','payload_policy':'not called by ingest; public water system rows, violations, contaminants, addresses, and safety/legal judgments excluded'}]
files=[]
for p in [src/'source-manifest.json',src/'web-services.html',src/'sdwa-docs.html']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'water.epa_echo_sdwa.api_catalog.v1','source':'EPA ECHO SDWA/SDWIS web services catalog metadata','license':'US-PD / US federal public information','summary':{'pages':len(pages),'links':sum(len(x['links']) for x in pages),'endpoints':len(endpoints),'files':len(files)},'policy':'official ECHO web-services catalog metadata only; public water system rows, violations, contaminant values, facility addresses, drinking-water safety advice, medical/legal/compliance judgments, and graph wiring excluded','manifest':manifest,'files':files,'pages':pages,'endpoints':endpoints}
out.write_text('# GENERATED by scripts/gen-water-epa-echo-sdwa-api-catalog.sh. Do not edit. Gitignored.\n# Source: EPA ECHO SDWA/SDWIS catalog metadata only; drinking-water payloads/safety/legal judgments excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} links={obj["summary"]["links"]} bytes={out.stat().st_size}')
PY
