#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/doc-layout/doclaynet-schema-catalog"
OUT="$ROOT/stdlib/lib/corpus/doclaynet-schema-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json, pathlib, re, sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
texts=[]
for p in sorted((src/'raw').glob('*.md')):
    texts.append(p.read_text(encoding='utf-8',errors='replace'))
alltxt='\n'.join(texts)
# DocLayNet class labels are stable public schema tokens. Prefer README/card extraction, keep fallback token list if card omits explicit list.
fallback_labels=['Caption','Footnote','Formula','List-item','Page-footer','Page-header','Picture','Section-header','Table','Text','Title']
labels=[]
for label in fallback_labels:
    if re.search(r'\b'+re.escape(label)+r'\b', alltxt, re.I):
        labels.append(label)
if len(labels)<8:
    labels=fallback_labels
cats=[]
m=re.search(r'doc_category[^\n]*following constants:\s*\n((?:\s+[a-z_]+,?\s*\n)+)', alltxt, re.I)
if m:
    for line in m.group(1).splitlines():
        v=line.strip().strip(',')
        if v: cats.append(v)
if not cats:
    cats=['financial_reports','scientific_articles','laws_and_regulations','government_tenders','manuals','patents']
splits=[]
for name,num in re.findall(r'(train|validation|val|test):\s*Dataset\(\{[^\n]*\n\s*features:[^\n]*\n\s*num_rows:\s*([0-9,]+)', alltxt):
    splits.append({'name':'val' if name=='validation' else name,'rows':int(num.replace(',',''))})
if not splits:
    for name,num in [('train',69375),('val',6489),('test',4999)]: splits.append({'name':name,'rows':num})
fields=[]
for f in ['image_id','image','width','height','doc_category','collection','doc_name','page_no','objects','bbox','category_id','segmentation','area','iscrowd']:
    if f in alltxt or f in ['bbox','category_id','segmentation','area','iscrowd']:
        fields.append(f)
asset_types=['PNG page images','COCO bounding-box annotations','single-page PDF extras','JSON digital text-cell extras']
obj={'schema':'doc.doclaynet.layout_schema.v1','source':'DocLayNet layout dataset schema/catalog metadata','license':'CDLA-Permissive-1.0','policy':'schema/catalog metadata only; no images/PDFs/JSON text/COCO annotation rows/bounding boxes/examples/prose bodies/graph wiring','summary':{'labels':len(labels),'document_categories':len(cats),'splits':len(splits),'fields':len(fields)},'manifest':manifest,'layout_labels':labels,'document_categories':cats,'splits':splits,'dataset_fields':fields,'asset_types':asset_types}
out.write_text('# GENERATED by scripts/gen-doc-doclaynet-schema-catalog.sh. Do not edit. Gitignored.\n# Source: DocLayNet schema/catalog metadata only; dataset payload excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: labels={len(labels)} categories={len(cats)} splits={len(splits)} bytes={out.stat().st_size}')
PY
