#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/transport/nhtsa-vpic-api"
OUT="$ROOT/stdlib/lib/corpus/nhtsa-vpic-api.generated.px"
MAKE_LIMIT="${NHTSA_VPIC_MAKE_LIMIT:-500}"
MANUFACTURER_LIMIT="${NHTSA_VPIC_MANUFACTURER_LIMIT:-100}"
python3 - "$SRC" "$OUT" "$MAKE_LIMIT" "$MANUFACTURER_LIMIT" <<'PY'
import pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); make_limit=int(sys.argv[3]); mfr_limit=int(sys.argv[4])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,float): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def typ(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'bool'
    if isinstance(v,int): return 'int'
    if isinstance(v,float): return 'float'
    if isinstance(v,str): return 'string'
    if isinstance(v,list): return 'list'
    if isinstance(v,dict): return 'object'
    return type(v).__name__
def walk(v,path,out):
    out.setdefault(path or '$',set()).add(typ(v))
    if isinstance(v,dict):
        for k,val in v.items(): walk(val,(path+'.' if path else '')+str(k),out)
    elif isinstance(v,list):
        out.setdefault((path or '$')+'[]',set()).add('item')
        for item in v[:3]: walk(item,(path or '$')+'[]',out)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for p in [src/'source-manifest.json']+sorted(src.glob('*.json')):
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
all_makes=json.loads((src/'all_makes.json').read_text())
manufacturers=json.loads((src/'manufacturers_page_1.json').read_text())
vehicle_types=json.loads((src/'vehicle_types_for_make.json').read_text())
models=json.loads((src/'models_for_make_year.json').read_text())
makes=[{'make_id':int(r.get('Make_ID') or 0),'make_name':r.get('Make_Name','')} for r in all_makes.get('Results',[])[:make_limit]]
mfrs=[]
for r in manufacturers.get('Results',[])[:mfr_limit]:
    mfrs.append({'mfr_id':int(r.get('Mfr_ID') or 0),'mfr_name':r.get('Mfr_Name',''),'common_name':r.get('Mfr_CommonName') or '','country':r.get('Country') or '','vehicle_type_names':[x.get('Name','') for x in (r.get('VehicleTypes') or []) if isinstance(x,dict)]})
types=[{'vehicle_type_id':int(r.get('VehicleTypeId') or 0),'vehicle_type_name':r.get('VehicleTypeName','')} for r in vehicle_types.get('Results',[])]
model_rows=[{'make_id':int(r.get('Make_ID') or 0),'make_name':r.get('Make_Name',''),'model_id':int(r.get('Model_ID') or 0),'model_name':r.get('Model_Name','')} for r in models.get('Results',[])]
endpoint_schemas=[]
for p in sorted(src.glob('*.json')):
    if p.name=='source-manifest.json': continue
    j=json.loads(p.read_text())
    paths={}; walk(j,'',paths)
    endpoint_schemas.append({'endpoint':p.stem,'count':int(j.get('Count') or 0) if isinstance(j,dict) else 0,'response_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'response_bytes':p.stat().st_size,'key_paths':[{'path':k,'types':sorted(v)} for k,v in sorted(paths.items())]})
obj={'schema':'transport.nhtsa_vpic.api_schema.v1','source':'NHTSA vPIC Vehicle API bounded metadata','license':'US-PD / US federal public API metadata','summary':{'makes':len(makes),'makes_total_seen':int(all_makes.get('Count') or len(all_makes.get('Results',[]))),'manufacturers':len(mfrs),'manufacturers_page_count':int(manufacturers.get('Count') or len(manufacturers.get('Results',[]))),'vehicle_types_for_sample_make':len(types),'models_for_sample_make_year':len(model_rows),'make_limit':make_limit,'manufacturer_limit':mfr_limit},'policy':'bounded make/manufacturer/model/type metadata and schema only; VIN logs, individual VINs, owner/person data, repair/diagnostic advice, legal/compliance decisions, safety recommendations, runtime dependency, graph wiring excluded','manifest':manifest,'files':files,'endpoint_schemas':endpoint_schemas,'makes':makes,'manufacturers':mfrs,'vehicle_types_for_sample_make':types,'models_for_sample_make_year':model_rows}
out.write_text('# GENERATED by scripts/gen-transport-nhtsa-vpic-api.sh. Do not edit. Gitignored.\n# Source: NHTSA vPIC API bounded vehicle metadata only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: makes={len(makes)}/{obj["summary"]["makes_total_seen"]} manufacturers={len(mfrs)} bytes={out.stat().st_size}')
PY
