#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${USPTO_IDM_SRC:-$ROOT/ingest/trademark/uspto-id-manual}"
OUT="${USPTO_IDM_OUT:-$ROOT/stdlib/lib/corpus/uspto-id-manual.generated.px}"
python3 - <<'PY' "$SRC" "$OUT"
import json,pathlib,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
raw=json.loads((src/'raw/idm-history-bounded.json').read_text())
rows=[]
for r in raw.get('records',[]):
    rows.append({'id':r.get('id'),'term_id':r.get('goodsServicesTermIdTx'),'class_no':r.get('classNo'),'class_id':r.get('fkClassId'),'edition':r.get('fkEditionNo'),'goods_services':r.get('goodsServicesCt'),'term_type':r.get('termCt'),'status':r.get('termStatusCd'),'description':r.get('descriptionTx'),'created_at':r.get('creationTimeStamp'),'modified_at':r.get('lastModTimeStamp')})
def esc(s): s='' if s is None else str(s); return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'
def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return esc(v)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))
seed={'schema':'trademark.uspto_id_manual.v1','source':{'name':'USPTO Trademark ID Manual bounded term metadata','license':'US-PD / USPTO public taxonomy metadata','retrieved_at_unix':receipt.get('retrieved_at_unix')},'summary':{'record_count':len(rows),'id_limit':receipt.get('id_limit'),'notes_ingested':False,'guidance_prose_ingested':False,'trademark_records_ingested':False,'legal_judgment_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'terms':rows}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/gen-trademark-uspto-id-manual.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: records={len(rows)}')
PY
