#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/transport/bts-ntad-catalog"
OUT="$ROOT/stdlib/lib/corpus/bts-ntad-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def sig(s):
    t=clean(s)
    return {'bytes':len(t.encode()),'sha256':hashlib.sha256(t.encode()).hexdigest()} if t else {'bytes':0,'sha256':''}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
datasets=[]
if (src/'dcat-us.json').exists():
    dcat=json.loads((src/'dcat-us.json').read_text())
    for d in dcat.get('dataset',[]):
        hay=' '.join(clean(d.get(k,'')) for k in ['title','identifier','landingPage','keyword']).lower()
        if not any(k in hay for k in ['ntad','national transportation atlas','highway performance monitoring','geospatial']):
            continue
        dist=[]
        for r in d.get('distribution',[])[:20]:
            dist.append({'title':clean(r.get('title',''))[:180],'format':clean(r.get('format',''))[:80],'mediaType':clean(r.get('mediaType',''))[:80],'accessURL':r.get('accessURL',''),'downloadURL':r.get('downloadURL',''),'description_sig':sig(r.get('description',''))})
        datasets.append({'identifier':d.get('identifier',''),'title':clean(d.get('title',''))[:220],'landingPage':d.get('landingPage',''),'modified':d.get('modified',''),'issued':d.get('issued',''),'publisher':clean((d.get('publisher') or {}).get('name',''))[:160] if isinstance(d.get('publisher'),dict) else clean(d.get('publisher',''))[:160],'keywords':[clean(x)[:80] for x in (d.get('keyword') or [])[:40]],'description_sig':sig(d.get('description','')),'distributions':dist})
        if len(datasets)>=80: break
pages=[]
if (src/'bts-geodata.html').exists():
    txt=(src/'bts-geodata.html').read_text(errors='ignore')
    mt=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
    pages.append({'page':'bts_geodata_portal','file':'bts-geodata.html','title':clean(re.sub('<.*?>',' ',mt.group(1)))[:220] if mt else '', 'html_sig':sig(txt)})
files=[]
for p in [src/'source-manifest.json',src/'bts-geodata.html',src/'dcat-us.json']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'transport.bts_ntad.catalog.v1','source':'BTS National Transportation Atlas Database DCAT/catalog metadata','license':'US-PD / US federal public information','summary':{'datasets':len(datasets),'distributions':sum(len(x['distributions']) for x in datasets),'pages':len(pages),'files':len(files)},'policy':'official DCAT/catalog/page metadata only; NTAD geospatial payloads, network geometries, coordinates, facility locations, routing/navigation use, operational control, safety/security judgments, prose bodies, and graph wiring excluded','manifest':manifest,'files':files,'pages':pages,'datasets':datasets}
out.write_text('# GENERATED by scripts/gen-transport-bts-ntad-catalog.sh. Do not edit. Gitignored.\n# Source: BTS NTAD DCAT/catalog metadata only; geospatial payloads/geometries excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: datasets={len(datasets)} distributions={obj["summary"]["distributions"]} bytes={out.stat().st_size}')
PY
