#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/transport/fhwa-hpms-catalog"
OUT="$ROOT/stdlib/lib/corpus/fhwa-hpms-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def prose_sig(s):
    t=clean(s)
    return {'bytes':len(t.encode()),'sha256':hashlib.sha256(t.encode()).hexdigest()} if t else {'bytes':0,'sha256':''}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
def links_from(path, page_id):
    if not path.exists(): return []
    txt=path.read_text(errors='ignore')
    rows=[]
    for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>', txt, re.I|re.S):
        href=html.unescape(m.group(1)); label=clean(re.sub('<.*?>',' ',m.group(2)))[:220]
        if not href or href.startswith('#'): continue
        low=(href+' '+label).lower()
        if any(k in low for k in ['hpms','highway performance','shapefile','geospatial','arnold','ntad','doi.org/10.21949']):
            kind='catalog_link'
            if 'shapefile' in low or '.zip' in low or 'geospatial' in low: kind='geospatial_payload_ref'
            if 'manual' in low or 'guide' in low or 'field' in low: kind='documentation_ref'
            if 'doi.org' in low: kind='persistent_identifier'
            rows.append({'page':page_id,'kind':kind,'label':label,'href':href})
    return rows[:120]
pages=[]
for name,page_id in [('fhwa-hpms.html','fhwa_hpms_main'),('fhwa-hpms-shapefiles.html','fhwa_hpms_shapefiles'),('data-gov-hpms-2024.html','data_gov_hpms_2024')]:
    path=src/name
    if path.exists():
        txt=path.read_text(errors='ignore')
        title=''
        mt=re.search(r'<title[^>]*>(.*?)</title>', txt, re.I|re.S)
        if mt: title=clean(re.sub('<.*?>',' ',mt.group(1)))[:220]
        pages.append({'page':page_id,'file':name,'title':title,'html_sig':prose_sig(txt),'links':links_from(path,page_id)})
files=[]
for p in [src/'source-manifest.json', src/'fhwa-hpms.html', src/'fhwa-hpms-shapefiles.html', src/'data-gov-hpms-2024.html']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'transport.fhwa_hpms.catalog.v1','source':'FHWA HPMS catalog metadata via official FHWA/Data.gov pages','license':'US-PD / US federal public information','summary':{'pages':len(pages),'links':sum(len(x['links']) for x in pages),'files':len(files)},'policy':'official catalog/page/link metadata only; HPMS road segment payloads, geometries, condition/performance values, routing/navigation use, engineering/safety judgments, prose bodies, and graph wiring excluded','manifest':manifest,'files':files,'pages':pages}
out.write_text('# GENERATED by scripts/gen-transport-fhwa-hpms-catalog.sh. Do not edit. Gitignored.\n# Source: FHWA/Data.gov HPMS catalog metadata only; road segment payloads/geometries excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} links={obj["summary"]["links"]} bytes={out.stat().st_size}')
PY
