#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/procurement/samgov-contract-api-catalog"
OUT="$ROOT/stdlib/lib/corpus/samgov-contract-api-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib,sys,json,hashlib,re,html,urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(re.sub('<.*?>',' ',str(s or '')))).strip()
def sig(txt):
    b=txt.encode() if isinstance(txt,str) else txt
    return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
pages=[]
for p in sorted(src.glob('*.html')):
    txt=p.read_text(errors='ignore')
    mt=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
    links=[]
    for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>',txt,re.I|re.S):
        href=html.unescape(m.group(1)); label=clean(m.group(2))[:160]
        if href and not href.startswith('#') and any(k in (href+' '+label).lower() for k in ['api','sam','fpds','contract','opportunit','data-services','open.gsa','yml','yaml']):
            links.append({'label':label,'href':urllib.parse.urljoin('https://open.gsa.gov/',href)})
    pages.append({'page':p.stem,'file':p.name,'title':clean(mt.group(1))[:220] if mt else '', 'html_sig':sig(txt),'links':links[:120]})
yml=(src/'opportunities.yml').read_text(errors='ignore') if (src/'opportunities.yml').exists() else ''
endpoints=[]; current=None; current_method=None; in_params=False; param=None
for raw in yml.splitlines():
    line=raw.rstrip('\n')
    m=re.match(r'^(/[^:]+):\s*$',line)
    if m:
        if param and current: current.setdefault('parameters',[]).append(param); param=None
        if current: endpoints.append(current)
        current={'path':m.group(1),'method':'','operation_id':'','tags':[],'parameters':[]}; current_method=None; in_params=False; continue
    if current is None: continue
    mm=re.match(r'^\s{4}(get|post|put|delete|patch):\s*$',line)
    if mm: current_method=mm.group(1).upper(); current['method']=current_method; continue
    mo=re.match(r'^\s+operationId:\s*(.+)$',line)
    if mo: current['operation_id']=mo.group(1).strip().strip("'\""); continue
    if re.match(r'^\s+parameters:\s*$',line): in_params=True; continue
    if in_params:
        mn=re.match(r'^\s+-\s*name:\s*(.+)$',line)
        if mn:
            if param: current['parameters'].append(param)
            param={'name':mn.group(1).strip().strip("'\""),'param_in':'','required':False,'type':''}; continue
        mi=re.match(r'^\s+in:\s*(.+)$',line)
        if mi and param: param['param_in']=mi.group(1).strip().strip("'\""); continue
        mr=re.match(r'^\s+required:\s*(true|false)$',line)
        if mr and param: param['required']=mr.group(1)=='true'; continue
        mt=re.match(r'^\s+type:\s*(.+)$',line)
        if mt and param: param['type']=mt.group(1).strip().strip("'\""); continue
if param and current: current.setdefault('parameters',[]).append(param)
if current: endpoints.append(current)
files=[]
for p in sorted(src.iterdir()):
    if p.is_file(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'procurement.samgov_contract_api_catalog.v1','source':'SAM.gov / GSA contract opportunities and FPDS API catalog metadata','license':'US federal public docs/catalog metadata; API payloads excluded','summary':{'pages':len(pages),'links':sum(len(x['links']) for x in pages),'opportunity_endpoints':len(endpoints),'parameters':sum(len(x.get('parameters',[])) for x in endpoints),'files':len(files)},'policy':'Public API docs/YAML endpoint metadata only. Excludes opportunity records, award/FPDS records, entity/FOUO/CUI/sensitive payloads, API keys, request/response logs, attachments, solicitation/proposal content, legal/procurement advice, and graph/mirror wiring.','manifest':manifest,'files':files,'pages':pages,'opportunity_api':{'yaml_sig':sig(yml),'endpoints':endpoints}}
out.write_text('# GENERATED by scripts/gen-procurement-samgov-contract-api-catalog.sh. Do not edit. Gitignored.\n# Source: SAM.gov/GSA public API catalog metadata only; contract payloads/API keys excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} endpoints={len(endpoints)} bytes={out.stat().st_size}')
PY
