#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/regulatory/ecfr-section-reference"
OUT="$ROOT/stdlib/lib/corpus/ecfr-section-reference.generated.px"
LIMIT="${ECFR_SECTION_LIMIT_PER_TITLE:-120}"
python3 - "$SRC" "$OUT" "$LIMIT" <<'PY'
import json, sys, pathlib, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); limit=int(sys.argv[3])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('\n',' ').replace('\r','')+'"'
sections=[]; title_rows=[]
def walk(node, path, acc):
    typ=node.get('type','')
    ident=node.get('identifier','')
    here=path+([typ+':'+ident] if ident else [])
    if typ=='section':
        acc.append({
            'identifier':ident,
            'label':node.get('label',''),
            'label_level':node.get('label_level',''),
            'label_description':node.get('label_description',''),
            'reserved':bool(node.get('reserved',False)),
            'received_on':node.get('received_on',''),
            'size':node.get('size',0),
            'path':here[:-1]
        })
    for ch in node.get('children',[]) or []:
        walk(ch, here, acc)
for line in (src/'structures.txt').read_text().splitlines():
    title,date,file=line.split('\t')
    p=src/file
    d=json.loads(p.read_text())
    acc=[]; walk(d, [], acc)
    kept=acc[:limit]
    title_rows.append({'title':title,'snapshot_date':date,'label':d.get('label',''),'description':d.get('label_description',''),'total_sections_seen':len(acc),'sections_kept':len(kept),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
    for s in kept:
        s['title']=title; s['snapshot_date']=date
        sections.append(s)
lines=['''# GENERATED by scripts/gen-regulatory-ecfr-section-reference.sh. Do not edit. Gitignored.
# Source: eCFR API title structure JSON.
# Policy: section id/title/reference metadata only; XML/full text/IBR body/legal advice excluded.
{ schema = "regulatory.ecfr_section_reference.v1";
  source = "eCFR API title structure section references";
  license = "US-PD";
''']
lines.append(f'  summary = {{ titles = {len(title_rows)}; sections = {len(sections)}; limit_per_title = {limit}; }};\n')
lines.append('  titles = [\n')
for t in title_rows:
    lines.append('    { title = '+esc(t['title'])+'; snapshot_date = '+esc(t['snapshot_date'])+'; label = '+esc(t['label'])+'; description = '+esc(t['description'])+'; total_sections_seen = '+str(t['total_sections_seen'])+'; sections_kept = '+str(t['sections_kept'])+'; sha256 = '+esc(t['sha256'])+'; }\n')
lines.append('  ];\n  sections = [\n')
for s in sections:
    lines.append('    { title = '+esc(s['title'])+'; snapshot_date = '+esc(s['snapshot_date'])+'; identifier = '+esc(s['identifier'])+'; label = '+esc(s['label'])+'; label_level = '+esc(s['label_level'])+'; label_description = '+esc(s['label_description'])+'; reserved = '+('true' if s['reserved'] else 'false')+'; received_on = '+esc(s['received_on'])+'; size = '+str(s['size'])+'; path = [ '+' '.join(esc(x) for x in s['path'])+' ]; }\n')
lines.append('  ];\n}\n')
out.write_text(''.join(lines), encoding='utf-8')
print(f'generated {out}: titles={len(title_rows)} sections={len(sections)} bytes={out.stat().st_size}')
PY
