#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/bio/iof-ontology-catalog"
OUT="$ROOT/stdlib/lib/corpus/iof-ontology-catalog.generated.px"
TERM_LIMIT="${IOF_TERM_LIMIT:-900}"
python3 - "$SRC" "$OUT" "$TERM_LIMIT" <<'PY'
import pathlib,sys,json,hashlib,xml.etree.ElementTree as ET,re
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); term_limit=int(sys.argv[3])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def local(iri):
    if not iri: return ''
    return re.split(r'[#/]',iri.rstrip('/'))[-1]
def get_res(el):
    for k,v in el.attrib.items():
        if k.endswith('}resource') or k.endswith('}about') or k.endswith('}ID'):
            return v
    return ''
repo=json.load(open(src/'repo.json')) if (src/'repo.json').exists() else {}
tree=json.load(open(src/'tree.json')) if (src/'tree.json').exists() else {'tree':[]}
manifest=json.load(open(src/'source-manifest.json')) if (src/'source-manifest.json').exists() else {}
files=[]
for x in tree.get('tree',[]):
    path=x.get('path',''); low=path.lower()
    if x.get('type')=='blob' and any(low.endswith(e) for e in ['.rdf','.owl','.ttl','.xml','.ofn','.omn']):
        category='external_cache' if path.startswith('cache/') else 'example_or_test' if any(s in low for s in ['/test/','/testing/','/examples/']) else 'migration' if path.startswith('migration/') else 'iof_ontology'
        files.append({'path':path,'bytes':x.get('size',0),'sha':x.get('sha',''),'category':category})
terms=[]; imports=[]
kind_map={'Class':'class','ObjectProperty':'object_property','DatatypeProperty':'datatype_property','AnnotationProperty':'annotation_property'}
for p in sorted((src/'raw').glob('*')):
    source_path=p.name.replace('__','/')
    try: root=ET.parse(p).getroot()
    except Exception: continue
    for el in root.iter():
        tag=el.tag.split('}',1)[-1]
        if tag=='Ontology':
            iri=get_res(el)
            if iri: imports.append({'declared_in':source_path,'ontology_iri':iri})
        if tag=='imports':
            iri=get_res(el)
            if iri: imports.append({'declared_in':source_path,'import_iri':iri})
        if tag in kind_map and len(terms)<term_limit:
            iri=get_res(el)
            if not iri: continue
            rec={'kind':kind_map[tag],'iri':iri,'local_name':local(iri),'declared_in':source_path}
            supers=[]; domains=[]; ranges=[]
            for ch in list(el):
                ct=ch.tag.split('}',1)[-1]; res=get_res(ch)
                if not res: continue
                if ct=='subClassOf' or ct=='subPropertyOf': supers.append(res)
                elif ct=='domain': domains.append(res)
                elif ct=='range': ranges.append(res)
            if supers: rec['super_refs']=supers[:20]
            if domains: rec['domain_refs']=domains[:20]
            if ranges: rec['range_refs']=ranges[:20]
            terms.append(rec)
raw_files=[]
for p in sorted((src/'raw').glob('*')):
    raw_files.append({'path':p.name.replace('__','/'),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'industry.iof.ontology_catalog.v1','source':'Industrial Ontologies Foundry ontology repository structural catalog','license':'MIT','summary':{'tree_files':len(tree.get('tree',[])),'ontology_file_records':len(files),'raw_rdf_files':len(raw_files),'terms_stored':len(terms),'term_limit':term_limit,'imports':len(imports)},'policy':'Repository/tree metadata and RDF structural IRI tokens only. Excludes RDF/OWL bodies, labels/comments/definitions/prose annotations, examples/tests, external cache ontology bodies, migration replacement bodies, reasoning, and graph/mirror wiring.','repository':{'full_name':repo.get('full_name',''),'default_branch':repo.get('default_branch',''),'html_url':repo.get('html_url',''),'license':(repo.get('license') or {}).get('spdx_id',''),'updated_at':repo.get('updated_at','')},'manifest':manifest,'files':files,'raw_files':raw_files,'imports':imports[:200],'terms':terms}
out.write_text('# GENERATED by scripts/gen-bio-iof-ontology-catalog.sh. Do not edit. Gitignored.\n# Source: IOF ontology structural token catalog only; RDF bodies/prose/examples/graph wiring excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: files={len(files)} raw={len(raw_files)} terms={len(terms)} imports={len(imports)} bytes={out.stat().st_size}')
PY
