#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${GEOBOUNDARIES_SRC:-$ROOT/ingest/place/geoboundaries}"
OUT="${GEOBOUNDARIES_OUT:-$ROOT/stdlib/lib/corpus/geoboundaries-catalog.generated.px}"
python3 - <<'PY' "$SRC" "$OUT"
import json,pathlib,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
def as_list(x): return x if isinstance(x,list) else ([x] if isinstance(x,dict) and x.get('boundaryID') else [])
rows=[]
for p in sorted((src/'raw').glob('*.json')):
 try: data=json.loads(p.read_text())
 except Exception: continue
 for r in as_list(data):
  rows.append({'boundary_id':r.get('boundaryID'),'name':r.get('boundaryName'),'iso3':r.get('boundaryISO'),'type':r.get('boundaryType'),'year':r.get('boundaryYearRepresented'),'canonical':r.get('boundaryCanonical'),'source':r.get('boundarySource'),'license':r.get('boundaryLicense'),'license_detail':r.get('licenseDetail'),'api_file':p.name,'geometry_payload_ingested':False,'has_geojson_url':bool(r.get('gjDownloadURL') or r.get('simplifiedGeometryGeoJSON')),'has_shape_url':bool(r.get('downloadURL') or r.get('staticDownloadLink'))})
def esc(s): s='' if s is None else str(s); return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'
def atom(v):
 if v is None: return 'null'
 if isinstance(v,bool): return 'true' if v else 'false'
 if isinstance(v,int): return str(v)
 if isinstance(v,str): return esc(v)
 if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
 if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
 raise TypeError(type(v))
seed={'schema':'place.geoboundaries_catalog.v1','source':{'name':'geoBoundaries gbOpen API catalog','license':'CC-BY-4.0 / per-record license retained','retrieved_at_unix':receipt.get('retrieved_at_unix')},'summary':{'record_count':len(rows),'geometry_payloads_ingested':False,'coordinates_ingested':False,'gb_humanitarian_ingested':False,'gb_authoritative_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'records':rows}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/gen-place-geoboundaries-catalog.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: records={len(rows)}')
PY
