#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/doc-layout/pubtables1m-schema-catalog"
OUT="$ROOT/stdlib/lib/corpus/pubtables1m-schema-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json, pathlib, re, sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
labels=[]
for name,path in [('detection','hf-detection-config.json'),('structure_recognition','hf-structure-config.json')]:
    p=src/'raw'/path
    if p.exists():
        cfg=json.loads(p.read_text())
        id2=cfg.get('id2label') or {}
        labels.append({'task':name,'labels':[{'id':int(k),'label':v} for k,v in sorted(id2.items(), key=lambda kv:int(kv[0]))]})
if not labels:
    labels=[{'task':'detection','labels':[{'id':0,'label':'table'}]},{'task':'structure_recognition','labels':[{'id':0,'label':'table'},{'id':1,'label':'table column'},{'id':2,'label':'table row'},{'id':3,'label':'table column header'},{'id':4,'label':'table projected row header'},{'id':5,'label':'table spanning cell'}]}]
readme=(src/'raw'/'github-README.md').read_text(encoding='utf-8',errors='replace') if (src/'raw'/'github-README.md').exists() else ''
archives=[]
for m in re.finditer(r'PubTables-1M-[A-Za-z0-9_\-]+\.tar\.gz', readme):
    v=m.group(0)
    if v not in archives: archives.append(v)
counts=[]
for split,num in re.findall(r'/(train|test|val)[^0-9]{0,80}([0-9][0-9,]{2,})\s+XML', readme, re.I):
    counts.append({'split':split.lower(),'xml_files':int(num.replace(',',''))})
asset_types=['page image JPG archives','PASCAL VOC XML annotation archives','page/table word JSON archives','table structure cropped image archives']
obj={'schema':'doc.pubtables1m.layout_schema.v1','source':'PubTables-1M / Table Transformer schema/catalog metadata','license':'MIT repository/config metadata; dataset payloads excluded','policy':'schema/catalog metadata only; no dataset archives/images/XML/JSON text/annotation rows/bboxes/model weights/metrics/prose bodies/graph wiring','summary':{'tasks':len(labels),'label_rows':sum(len(x['labels']) for x in labels),'archive_refs':len(archives),'count_refs':len(counts)},'manifest':manifest,'task_label_maps':labels,'archive_refs':archives[:40],'count_refs':counts[:40],'asset_types':asset_types}
out.write_text('# GENERATED by scripts/gen-doc-pubtables1m-schema-catalog.sh. Do not edit. Gitignored.\n# Source: PubTables-1M/Table Transformer schema/catalog metadata only; payload excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: tasks={len(labels)} label_rows={sum(len(x["labels"]) for x in labels)} archives={len(archives)} bytes={out.stat().st_size}')
PY
