#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${NATURAL_EARTH_SRC:-$ROOT/ingest/place/natural-earth}"
OUT="${NATURAL_EARTH_OUT:-$ROOT/stdlib/lib/corpus/natural-earth-catalog.generated.px}"
LAYER_LIMIT="${NATURAL_EARTH_LAYER_LIMIT:-500}"
python3 - <<'PY' "$SRC" "$OUT" "$LAYER_LIMIT"
import json,pathlib,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); limit=int(sys.argv[3])
receipt=json.loads((src/'source-receipt.json').read_text()); tags=json.loads((src/'raw/tags.json').read_text()); tree=json.loads((src/'raw/tree.json').read_text())
def esc(s): s='' if s is None else str(s); return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'
def atom(v):
 if v is None: return 'null'
 if isinstance(v,bool): return 'true' if v else 'false'
 if isinstance(v,int): return str(v)
 if isinstance(v,str): return esc(v)
 if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
 if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
 raise TypeError(type(v))
tag_rows=[{'name':t.get('name'),'commit_sha':(t.get('commit') or {}).get('sha')} for t in tags]
layers={}
for e in tree.get('tree',[]):
 p=e.get('path','')
 if e.get('type')!='blob' or '/' not in p: continue
 parts=p.split('/')
 scale=parts[0] if parts[0] in ('10m_cultural','10m_physical','50m_cultural','50m_physical','110m_cultural','110m_physical') else None
 if not scale: continue
 fn=parts[-1]
 stem=fn.rsplit('.',1)[0]; ext=fn.rsplit('.',1)[-1] if '.' in fn else ''
 key=(scale,stem)
 rec=layers.setdefault(key, {'scale_theme':scale,'layer':stem,'extensions':set(),'file_count':0,'bytes_total':0})
 rec['extensions'].add(ext); rec['file_count']+=1; rec['bytes_total']+=int(e.get('size') or 0)
rows=[]
for rec in layers.values():
 rec['extensions']=sorted(rec['extensions']); rows.append(rec)
rows=sorted(rows, key=lambda r:(r['scale_theme'],r['layer']))[:limit]
seed={'schema':'place.natural_earth_catalog.v1','source':{'name':'Natural Earth vector catalog','license':'Public Domain','repo':receipt.get('repo'),'retrieved_at_unix':receipt.get('retrieved_at_unix')},'summary':{'tag_count':len(tag_rows),'layer_count':len(rows),'layer_limit':limit,'geometry_payloads_ingested':False,'coordinates_ingested':False,'raster_payloads_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'tags':tag_rows,'layers':rows}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/gen-place-natural-earth-catalog.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: tags={len(tag_rows)} layers={len(rows)}')
PY
