#!/usr/bin/env bash
set -euo pipefail
ROOT="${PNIX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
REL="$ROOT/ingest/devops/kubernetes/release.json"
TAG="${K8S_TAG:-$(python3 - "$REL" <<'PY'
import json,sys,os
p=sys.argv[1]
print(json.load(open(p))['tag_name'] if os.path.exists(p) else 'unknown')
PY
)}"
SRC="${K8S_OPENAPI_SOURCE:-$ROOT/ingest/devops/kubernetes/swagger-$TAG.json}"
OUT="${K8S_OPENAPI_OUT:-$ROOT/stdlib/lib/corpus/kubernetes-openapi.generated.px}"
LIMIT="${K8S_DEFINITION_LIMIT:-500}"
PROP_LIMIT="${K8S_PROPERTY_LIMIT:-80}"
if [ ! -f "$SRC" ]; then
  echo "missing Kubernetes OpenAPI source: $SRC" >&2
  echo "run: scripts/update-devops-kubernetes-openapi.sh" >&2
  exit 1
fi
mkdir -p "$(dirname "$OUT")"
python3 - "$SRC" "$REL" "$OUT" "$LIMIT" "$PROP_LIMIT" <<'PY'
import hashlib, json, sys
from pathlib import Path
src=Path(sys.argv[1]); rel=Path(sys.argv[2]); out=Path(sys.argv[3]); limit=int(sys.argv[4]); prop_limit=int(sys.argv[5])

def q(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')+'"'

def lit(v, indent=0):
    sp=' '*indent
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if v is None: return 'null'
    if isinstance(v,str): return q(v)
    if isinstance(v,list):
        if not v: return '[ ]'
        return '[\n'+''.join(' '*(indent+2)+lit(x, indent+2)+'\n' for x in v)+sp+']'
    if isinstance(v,dict):
        if not v: return '{ }'
        lines=['{']
        for k in v:
            lines.append(' '*(indent+2)+k+' = '+lit(v[k], indent+2)+';')
        lines.append(sp+'}')
        return '\n'.join(lines)
    raise TypeError(type(v))

def refname(x):
    return x.split('/')[-1] if isinstance(x,str) else ''

def prop_shape(p):
    rec={'name':''}
    if '$ref' in p: rec['ref']=refname(p.get('$ref'))
    if 'type' in p: rec['type']=p.get('type')
    if 'format' in p: rec['format']=p.get('format')
    if 'x-kubernetes-int-or-string' in p: rec['x_kubernetes_int_or_string']=True
    if 'x-kubernetes-list-type' in p: rec['x_kubernetes_list_type']=p.get('x-kubernetes-list-type')
    if 'x-kubernetes-map-type' in p: rec['x_kubernetes_map_type']=p.get('x-kubernetes-map-type')
    items=p.get('items')
    if isinstance(items,dict):
        ir={}
        if '$ref' in items: ir['ref']=refname(items.get('$ref'))
        if 'type' in items: ir['type']=items.get('type')
        if 'format' in items: ir['format']=items.get('format')
        if ir: rec['items']=ir
    addl=p.get('additionalProperties')
    if isinstance(addl,dict):
        ar={}
        if '$ref' in addl: ar['ref']=refname(addl.get('$ref'))
        if 'type' in addl: ar['type']=addl.get('type')
        if ar: rec['additional_properties']=ar
    return rec

release=json.load(rel.open()) if rel.exists() else {}
sw=json.load(src.open())
defs=sw.get('definitions',{})
records=[]
for name in sorted(defs)[:limit]:
    d=defs[name]
    rec={'name':name}
    if 'type' in d: rec['type']=d.get('type')
    if d.get('required'): rec['required']=d['required']
    gvks=d.get('x-kubernetes-group-version-kind') or []
    if gvks:
        rec['gvk']=[{k.replace('-','_'):v for k,v in g.items() if v} for g in gvks]
    props=[]
    for pn,p in sorted((d.get('properties') or {}).items())[:prop_limit]:
        pr=prop_shape(p); pr['name']=pn; props.append(pr)
    if props: rec['properties']=props
    records.append(rec)
sha=hashlib.sha256(src.read_bytes()).hexdigest()
value={
  'schema':'devops.k8s.openapi.v1',
  'source':'Kubernetes release swagger.json OpenAPI schema',
  'license':'Apache-2.0',
  'source_url':'https://github.com/kubernetes/kubernetes/tree/<tag>/api/openapi-spec',
  'source_sha256':sha,
  'release_tag':release.get('tag_name',''),
  'release_published_at':release.get('published_at',''),
  'definition_limit':limit,
  'property_limit':prop_limit,
  'total_definitions_seen':len(defs),
  'definitions':records,
}
out.write_text('# GENERATED by scripts/gen-devops-kubernetes-openapi.sh; do not commit.\n'+lit(value)+'\n', encoding='utf-8')
print(f"generated {out}: definitions={len(records)} total_definitions={len(defs)} tag={release.get('tag_name','')} sha256={sha}")
PY
