#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/science/epa-radnet-catalog"
OUT="$ROOT/stdlib/lib/corpus/epa-radnet-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def sig(txt):
    b=txt.encode() if isinstance(txt,str) else txt
    return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def page_meta(path,page_id):
    txt=path.read_text(errors='ignore')
    mt=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
    links=[]
    for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>', txt, re.I|re.S):
        href=html.unescape(m.group(1)); label=clean(re.sub('<.*?>',' ',m.group(2)))[:180]
        if href and not href.startswith('#'):
            low=(href+' '+label).lower()
            if any(k in low for k in ['radnet','radiation','gamma','air','monitor','station','data','download','epa']):
                kind='catalog_link'
                if any(k in low for k in ['near-real-time','data','download','csv','xml','json']): kind='payload_ref_excluded'
                links.append({'kind':kind,'label':label,'href':urllib.parse.urljoin('https://www.epa.gov/radnet/',href)})
    tokens=sorted(set([x.lower() for x in re.findall(r'\b(?:RadNet|gamma|radiation|monitor|station|air|filter|drinking water|near-real-time|dose|beta|gross beta)\b',txt,re.I)]))
    return {'page':page_id,'file':path.name,'title':clean(re.sub('<.*?>',' ',mt.group(1)))[:220] if mt else '', 'html_sig':sig(txt),'tokens':tokens,'safety_policy':'catalog only; not for dose, exposure, KI, evacuation, shelter, or release-interpretation decisions','links':links[:140]}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
pages=[]
for name,page_id in [('radnet.html','radnet_home'),('near-real-time-air.html','near_real_time_air')]:
    p=src/name
    if p.exists(): pages.append(page_meta(p,page_id))
files=[]
for p in [src/'source-manifest.json',src/'radnet.html',src/'near-real-time-air.html']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'science.epa_radnet.catalog.v1','source':'EPA RadNet catalog metadata','license':'US-PD / US federal public information','summary':{'pages':len(pages),'links':sum(len(x['links']) for x in pages),'files':len(files)},'policy':'official EPA RadNet catalog page metadata only; near-real-time readings, dose-rate values, air filter/drinking-water measurements, radiation release interpretation, exposure/medical advice, KI administration, evacuation/shelter decisions, and graph wiring excluded','manifest':manifest,'files':files,'pages':pages}
out.write_text('# GENERATED by scripts/gen-science-epa-radnet-catalog.sh. Do not edit. Gitignored.\n# Source: EPA RadNet catalog metadata only; measurement/dose/safety decisions excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} links={obj["summary"]["links"]} bytes={out.stat().st_size}')
PY
