#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/science/usgs-earthquake-products-catalog"
OUT="$ROOT/stdlib/lib/corpus/usgs-earthquake-products-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def sig(txt):
    b=txt.encode() if isinstance(txt,str) else txt
    return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def page_meta(path,page_id,product_type):
    txt=path.read_text(errors='ignore')
    mt=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
    links=[]
    for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>', txt, re.I|re.S):
        href=html.unescape(m.group(1)); label=clean(re.sub('<.*?>',' ',m.group(2)))[:180]
        if href and not href.startswith('#'):
            low=(href+' '+label).lower()
            if any(k in low for k in ['shakemap','pager','earthquake','product','download','github','documentation','feed','comcat','xml','json']):
                kind='catalog_link'
                if any(k in low for k in ['feed','download','json','xml','grid','shape','kml']): kind='payload_ref_excluded'
                links.append({'kind':kind,'label':label,'href':urllib.parse.urljoin('https://earthquake.usgs.gov/data/',href)})
    tokens=sorted(set([x.lower() for x in re.findall(r'\b(?:ShakeMap|PAGER|shakemap|pager|grid|intensity|mmi|loss|fatality|exposure|alert|product)\b',txt)]))
    return {'page':page_id,'product_type':product_type,'file':path.name,'title':clean(re.sub('<.*?>',' ',mt.group(1)))[:220] if mt else '', 'html_sig':sig(txt),'tokens':tokens,'accepted_truth':False,'safety_policy':'catalog only; not for response, evacuation, building-safety, or loss/fatality decisions','links':links[:120]}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
pages=[]
if (src/'shakemap.html').exists(): pages.append(page_meta(src/'shakemap.html','shakemap','shakemap'))
if (src/'pager.html').exists(): pages.append(page_meta(src/'pager.html','pager','pager'))
files=[]
for p in [src/'source-manifest.json',src/'shakemap.html',src/'pager.html']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'science.usgs_earthquake_products.catalog.v1','source':'USGS ShakeMap/PAGER product catalog metadata','license':'US-PD / US federal public information','summary':{'pages':len(pages),'links':sum(len(x['links']) for x in pages),'files':len(files)},'policy':'official product catalog page metadata only; ShakeMap grids/intensity values, PAGER loss/fatality estimates, alert levels, event product payloads, forecasts, response/evacuation/building-safety guidance, accepted-truth disaster decisions, and graph wiring excluded','manifest':manifest,'files':files,'products':pages}
out.write_text('# GENERATED by scripts/gen-science-usgs-earthquake-products-catalog.sh. Do not edit. Gitignored.\n# Source: USGS ShakeMap/PAGER catalog metadata only; grids/loss estimates/response guidance excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} links={obj["summary"]["links"]} bytes={out.stat().st_size}')
PY
