#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${FGDC_ADDRESS_SRC:-$ROOT/ingest/place/fgdc-address-standard}"
OUT="${FGDC_ADDRESS_OUT:-$ROOT/stdlib/lib/corpus/fgdc-address-standard-catalog.generated.px}"
python3 - <<'PY' "$SRC" "$OUT"
import json,pathlib,re,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
html=(src/'raw/address-data.html').read_text(errors='replace')
def clean(x): return re.sub(r'\s+',' ', re.sub(r'<[^>]+>',' ',x)).strip()
doc_no='FGDC-STD-016-2011' if 'FGDC-STD-016-2011' in html else None
title='United States Thoroughfare, Landmark, and Postal Address Data Standard'
sections=[]
for name in ['Document number','Maintenance authority','Objectives','Scope','Sponsored by','Project history','Schemas']:
    if name in html: sections.append(name)
links=[]
for m in re.finditer(r'href="([^"]+)"', html):
    href=m.group(1)
    if 'Address' in href or 'address' in href or href.endswith('.zip'):
        links.append(href)
links=sorted(set(links))[:80]
def esc(s): s='' if s is None else str(s); return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'
def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return esc(v)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))
seed={'schema':'place.fgdc_address_standard_catalog.v1','source':{'name':'FGDC United States Thoroughfare, Landmark, and Postal Address Data Standard catalog','license':'US-PD / U.S. federal public standard metadata','retrieved_at_unix':receipt.get('retrieved_at_unix')},'summary':{'document_number':doc_no,'zip_entry_count':len(receipt.get('zip_entries',[])),'project_section_count':len(sections),'pdf_prose_ingested':False,'address_records_ingested':False,'coordinates_ingested':False,'mirror_graph_wiring':False},'project':{'title':title,'document_number':doc_no,'endorsed':'February 2011','official_page':'https://www.fgdc.gov/standards/projects/address-data','known_sections':sections,'related_links':links},'source_receipt':receipt,'zip_manifest':receipt.get('zip_entries',[])}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/gen-place-fgdc-address-standard-catalog.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: zip_entries={len(seed["zip_manifest"])} sections={len(sections)}')
PY
