#!/usr/bin/env bash
set -euo pipefail
# NCBI taxdump -> pnix attrset source. Source-style bounded snapshot; graph wiring 없음.
ROOT="${PNIX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
SRC_DIR="${NCBI_TAXONOMY_SOURCE:-$ROOT/ingest/science/ncbi-taxonomy/taxdump}"
TAR="$ROOT/ingest/science/ncbi-taxonomy/taxdump.tar.gz"
OUT="${NCBI_TAXONOMY_OUT:-$ROOT/stdlib/lib/corpus/ncbi-taxonomy.generated.px}"
LIMIT="${NCBI_TAXONOMY_NODE_LIMIT:-1000}"
if [ ! -f "$SRC_DIR/nodes.dmp" ] || [ ! -f "$SRC_DIR/names.dmp" ]; then
  echo "missing NCBI taxdump files: $SRC_DIR" >&2
  echo "run: scripts/update-science-ncbi-taxonomy.sh" >&2
  exit 1
fi
mkdir -p "$(dirname "$OUT")"
python3 - "$SRC_DIR" "$TAR" "$OUT" "$LIMIT" <<'PY'
import hashlib, sys
from pathlib import Path
src = Path(sys.argv[1]); tar = Path(sys.argv[2]); out = Path(sys.argv[3]); limit = int(sys.argv[4])

def q(s):
    s = '' if s is None else str(s)
    return '"' + s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t') + '"'

def lit(v, indent=0):
    sp=' '*indent
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if v is None: return 'null'
    if isinstance(v,str): return q(v)
    if isinstance(v,list):
        if not v: return '[ ]'
        return '[\n' + ''.join(' '*(indent+2)+lit(x, indent+2)+'\n' for x in v) + sp + ']'
    if isinstance(v,dict):
        if not v: return '{ }'
        lines=['{']
        for k in v:
            lines.append(' '*(indent+2)+k+' = '+lit(v[k], indent+2)+';')
        lines.append(sp+'}')
        return '\n'.join(lines)
    raise TypeError(type(v))

def fields(line):
    parts = line.rstrip('\n').split('\t|\t')
    if parts:
        parts[-1] = parts[-1].removesuffix('\t|').strip()
    return [p.strip() for p in parts]

nodes=[]; wanted=set(); total_nodes=0
for line in (src/'nodes.dmp').open(encoding='utf-8', errors='replace'):
    p = fields(line); total_nodes += 1
    if len(p) < 12: continue
    if len(nodes) < limit:
        tax_id,parent,rank,embl,division,div_inh,gc,gc_inh,mgc,mgc_inh,gb_hidden,hidden_root = p[:12]
        rec = {"tax_id": tax_id, "parent_tax_id": parent, "rank": rank}
        if division: rec["division_id"] = division
        if gc: rec["genetic_code_id"] = gc
        if mgc: rec["mitochondrial_genetic_code_id"] = mgc
        if gb_hidden == '1': rec["genbank_hidden"] = True
        if hidden_root == '1': rec["hidden_subtree_root"] = True
        nodes.append(rec); wanted.add(tax_id)

by_id={r['tax_id']:r for r in nodes}; total_names=0
for line in (src/'names.dmp').open(encoding='utf-8', errors='replace'):
    p=fields(line); total_names += 1
    if len(p) < 4: continue
    tax_id,name_txt,unique_name,name_class = p[:4]
    rec=by_id.get(tax_id)
    if rec is None: continue
    if name_class == 'scientific name' and 'scientific_name' not in rec:
        rec['scientific_name'] = name_txt
    elif name_class in ('genbank common name','common name') and 'common_name' not in rec:
        rec['common_name'] = name_txt

merged=[]; total_merged=0
mp=src/'merged.dmp'
if mp.exists():
    for line in mp.open(encoding='utf-8', errors='replace'):
        p=fields(line); total_merged += 1
        if len(p) >= 2 and len(merged) < limit:
            merged.append({"old_tax_id":p[0], "new_tax_id":p[1]})

delnodes=[]; total_delnodes=0
dp=src/'delnodes.dmp'
if dp.exists():
    for line in dp.open(encoding='utf-8', errors='replace'):
        p=fields(line); total_delnodes += 1
        if p and len(delnodes) < limit:
            delnodes.append(p[0])
sha=hashlib.sha256(tar.read_bytes()).hexdigest() if tar.exists() else ''
value={
  "schema":"bio.ncbi_taxonomy.v1",
  "source":"NCBI taxdump",
  "license":"US-PD",
  "source_url":"https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz",
  "source_sha256":sha,
  "node_limit":limit,
  "total_nodes_seen":total_nodes,
  "total_names_seen":total_names,
  "total_merged_seen":total_merged,
  "total_delnodes_seen":total_delnodes,
  "nodes":nodes,
  "merged":merged,
  "delnodes":delnodes,
}
out.write_text('# GENERATED by scripts/gen-science-ncbi-taxonomy.sh; do not commit.\n'+lit(value)+'\n', encoding='utf-8')
print(f"generated {out}: nodes={len(nodes)} merged={len(merged)} delnodes={len(delnodes)} total_nodes={total_nodes} sha256={sha}")
PY
