#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${NCES_CIP_SRC:-$ROOT/ingest/education/nces-cip}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/nces-cip.generated.px}"
LIMIT="${NCES_CIP_LIMIT:-1000}"
python3 - "$SRC" "$OUT" "$LIMIT" <<'PY'
import html, json, re, sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2]); limit=int(sys.argv[3])
receipt=json.loads((src/'source-receipt.json').read_text())
text=(src/'raw/browse.html').read_bytes().decode('ISO-8859-1','replace')

def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,(int,float)): return repr(v)
    if isinstance(v,str): return json.dumps(v, ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))

def parent(code):
    if re.fullmatch(r'\d{2}\.\d{4}', code): return code[:5]
    if re.fullmatch(r'\d{2}\.\d{2}', code): return code[:2]
    return ''
rows=[]; total=0
pat=re.compile(r'<a href="cipdetail\.aspx\?y=56&amp;cipid=(\d+)" title="View this CIP">([^<]+)</a>')
for cipid,label in pat.findall(text):
    label=html.unescape(label).strip()
    m=re.match(r'([0-9]{2}(?:\.[0-9]{2}(?:[0-9]{2})?)?)\)\s*(.*)', label)
    if not m: continue
    total += 1
    code=m.group(1); title=m.group(2).strip()
    if limit>0 and len(rows)>=limit: continue
    level=2 if re.fullmatch(r'\d{2}', code) else (4 if re.fullmatch(r'\d{2}\.\d{2}', code) else 6)
    rows.append({'cipid':cipid,'code':code,'title':title,'level':level,'parent_code':parent(code)})
seed={'schema':'education.nces_cip.v1','source':{'name':'NCES Classification of Instructional Programs (CIP) browse tree','license':'US-GOV-PD','year_id':receipt.get('year_id'),'retrieved_at':receipt.get('retrieved_at')},'summary':{'record_count':len(rows),'total_available_record_count':total,'record_limit':limit,'detail_prose_ingested':False,'program_rows_ingested':False,'student_data_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'records':rows}
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('# GENERATED by scripts/gen-education-nces-cip.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: records={len(rows)}, total={total}')
PY
