#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/workforce/open-skills-rsd-catalog"
OUT="$ROOT/stdlib/lib/corpus/open-skills-rsd-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib,sys,json,hashlib,re,html,urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(re.sub('<.*?>',' ',str(s or '')))).strip()
def sig(txt):
    b=txt.encode() if isinstance(txt,str) else txt
    return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
rsd=(src/'rsd.html').read_text(errors='ignore') if (src/'rsd.html').exists() else ''
osmt=(src/'osmt-page.html').read_text(errors='ignore') if (src/'osmt-page.html').exists() else ''
repo=json.loads((src/'osmt-repo.json').read_text()) if (src/'osmt-repo.json').exists() else {}
mt=re.search(r'<title[^>]*>(.*?)</title>',rsd,re.I|re.S)
license_links=[]
for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>',rsd,re.I|re.S):
    href=html.unescape(m.group(1)); label=clean(m.group(2))[:160]
    if 'creativecommons.org/licenses/by/4.0' in href or 'Repository' in label or 'Issues' in label or 'openskillsnetwork' in href:
        license_links.append({'label':label,'href':urllib.parse.urljoin('https://rsd.openskillsnetwork.org/',href)})
headings=[]
for m in re.finditer(r'<h([1-6])[^>]*(?:id=["\']([^"\']+)["\'])?[^>]*>(.*?)</h\1>',rsd,re.I|re.S):
    h=clean(m.group(3))
    if h: headings.append({'level':int(m.group(1)),'id':m.group(2) or '','label_hash':hashlib.sha256(h.encode()).hexdigest(),'label_len':len(h)})
field_tokens=sorted(set(re.findall(r'\b(?:skillStatement|canonicalURL|alignment|occupation|job|credential|CTDL|CTDL-ASN|Achievement|Pathway|LearnerRecord|creator|keywords|category|author|version|identifier)\b',rsd)))
osmt_title=''
mo=re.search(r'<title[^>]*>(.*?)</title>',osmt,re.I|re.S)
if mo: osmt_title=clean(mo.group(1))[:220]
files=[]
for p in sorted(src.iterdir()):
    if p.is_file(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'workforce.open_skills_rsd.catalog.v1','source':'Open Skills Network Rich Skill Descriptor recommendations catalog metadata','license':'CC-BY-4.0 documentation metadata; OSMT code/data excluded','summary':{'headings':len(headings),'field_tokens':len(field_tokens),'license_links':len(license_links),'files':len(files),'osmt_repo_license':(repo.get('license') or {}).get('spdx_id','NOASSERTION')},'policy':'RSD documentation metadata only. Excludes prose bodies, examples, sample skill statements, OSMT source code/database contents, skill libraries, job/learner profiles, credential payloads, and graph/mirror wiring.','manifest':manifest,'files':files,'rsd_doc':{'title':clean(mt.group(1))[:220] if mt else '','html_sig':sig(rsd),'license_links':license_links,'headings':headings[:120],'field_tokens':field_tokens},'osmt':{'page_title':osmt_title,'page_sig':sig(osmt),'repo':{'full_name':repo.get('full_name',''),'html_url':repo.get('html_url',''),'default_branch':repo.get('default_branch',''),'license':(repo.get('license') or {}).get('spdx_id','NOASSERTION'),'updated_at':repo.get('updated_at',''),'language':repo.get('language','')}}}
out.write_text('# GENERATED by scripts/gen-workforce-open-skills-rsd-catalog.sh. Do not edit. Gitignored.\n# Source: RSD doc metadata only; prose/examples/OSMT source/skill payloads excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: headings={len(headings)} tokens={len(field_tokens)} bytes={out.stat().st_size}')
PY
