#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/finance/fed-h15-series-catalog"
OUT="$ROOT/stdlib/lib/corpus/fed-h15-series-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import html, json, pathlib, re, sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
packages=[]; all_series={}
for f in manifest.get('files',[]):
    p=src/f.get('path','')
    txt=p.read_text(encoding='utf-8',errors='replace') if p.exists() else ''
    plain=re.sub(r'<(script|style)[^>]*>.*?</\1>',' ',txt,flags=re.S|re.I)
    plain=re.sub(r'<[^>]+>',' ',plain)
    plain=html.unescape(re.sub(r'\s+',' ',plain))
    release=None
    m=re.search(r'H\.15 Selected Interest Rates - last released ([A-Za-z]+, [A-Za-z]+ \d{1,2}, \d{4})', plain)
    if m: release=m.group(1)
    series=[]
    pat=re.compile(r'(H15/H15/[A-Z0-9_]+\.[A-Z]+)\s+(\d{4}-\d{2}-\d{2})\s+(\d{4}-\d{2}-\d{2})\s+([0-9,]+)\s+(.+?)(?=\s+H15/H15/|\s+Back to Top|\s+Board of Governors|$)')
    for sid,frm,to,obs,desc in pat.findall(plain):
        desc=desc.strip()
        rec={'package_id':f.get('id'),'series_id':sid,'available_from':frm,'available_to':to,'observations':int(obs.replace(',','')),'label':desc[:240]}
        series.append(rec)
        all_series.setdefault(sid,rec)
    packages.append({'id':f.get('id'),'label':f.get('label'),'series_hash':f.get('series'),'source_url':f.get('url'),'last_released':release,'series_count':len(series),'series':series})
obj={'schema':'finance.federal_reserve.h15_series_catalog.v1','source':'Federal Reserve H.15 DDP series catalog metadata','license':'US-PD / Federal Reserve public statistical release metadata','policy':'series catalog only; rate observation values/CSV/XML payloads/forecasts/advice/FRED payloads/graph wiring excluded','summary':{'packages':len(packages),'unique_series':len(all_series)},'manifest':manifest,'packages':packages,'unique_series':list(all_series.values())}
out.write_text('# GENERATED by scripts/gen-finance-fed-h15-series-catalog.sh. Do not edit. Gitignored.\n# Source: Federal Reserve H.15 DDP series catalog metadata only; rate values excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: packages={len(packages)} unique_series={len(all_series)} bytes={out.stat().st_size}')
PY
