#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/license/purl-spec"
OUT="$ROOT/stdlib/lib/corpus/purl-spec.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for name in ['tree.json','LICENSE','purl-types-index.json','source-manifest.json']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
type_ids=json.loads((src/'purl-types-index.json').read_text())
def field(d, name):
    v=d.get(name+'_definition') or {}
    return {'requirement':v.get('requirement',''),'native_name':v.get('native_name',''),'case_sensitive':v.get('case_sensitive',False)}
types=[]
for t in type_ids:
    d=json.loads((src/'types'/f'{t}-definition.json').read_text())
    q=d.get('qualifiers_definition') or []
    quals=[]
    if isinstance(q,dict):
        q=[q]
    if isinstance(q,list):
        for item in q:
            if isinstance(item,dict):
                quals.append({'key':item.get('key',''),'requirement':item.get('requirement',''),'native_name':item.get('native_name',''),'case_sensitive':item.get('case_sensitive',False)})
    sdef=d.get('subpath_definition') or {}
    if not isinstance(sdef,dict): sdef={}
    repo=d.get('repository') or {}
    if not isinstance(repo,dict): repo={}
    types.append({'type':d.get('type',t),'type_name':d.get('type_name',''),'repository_used':bool(repo.get('use_repository',False)),'namespace':field(d,'namespace'),'name':field(d,'name'),'version':field(d,'version'),'qualifiers':quals,'subpath_requirement':sdef.get('requirement','')})
schemas=[]
for p in sorted((src/'schemas').glob('*.json')):
    d=json.loads(p.read_text())
    props=sorted((d.get('properties') or {}).keys())
    req=d.get('required') or []
    schemas.append({'file':p.name,'schema_id':d.get('$id',''),'properties':props,'required':req})
obj={'schema':'license.purl_spec.v1','source':'package-url specification machine-readable metadata','license':'MIT','summary':{'types':len(types),'schemas':len(schemas),'repository_backed_types':sum(1 for t in types if t['repository_used'])},'policy':'purl type/schema structural metadata only; docs prose, examples, real package registry data, dependency/license package data, tests, graph wiring excluded','manifest':manifest,'files':files,'types':types,'schemas':schemas}
out.write_text('# GENERATED by scripts/gen-license-purl-spec.sh. Do not edit. Gitignored.\n# Source: package-url purl-spec machine-readable type/schema metadata only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: types={len(types)} schemas={len(schemas)} bytes={out.stat().st_size}')
PY
