#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${DULWICH_SRC:-$ROOT/ingest/vcs/dulwich}"
OUT="${DULWICH_OUT:-$ROOT/stdlib/lib/corpus/dulwich-catalog.generated.px}"
RELEASE_LIMIT="${DULWICH_RELEASE_LIMIT:-40}"
python3 - <<'PY' "$SRC" "$OUT" "$RELEASE_LIMIT"
import json,pathlib,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); limit=int(sys.argv[3])
receipt=json.loads((src/'source-receipt.json').read_text())
pypi=json.loads((src/'raw/pypi.json').read_text()); tags=json.loads((src/'raw/tags.json').read_text())
def esc(s):
 s='' if s is None else str(s); return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'
def atom(v):
 if v is None: return 'null'
 if isinstance(v,bool): return 'true' if v else 'false'
 if isinstance(v,int): return str(v)
 if isinstance(v,str): return esc(v)
 if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
 if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
 raise TypeError(type(v))
info=pypi.get('info',{})
release_rows=[]
for version, files in sorted((pypi.get('releases') or {}).items(), reverse=True)[:limit]:
 release_rows.append({'version':version,'file_count':len(files),'files':[{'filename':f.get('filename'),'packagetype':f.get('packagetype'),'python_version':f.get('python_version'),'size':f.get('size'),'upload_time':f.get('upload_time_iso_8601') or f.get('upload_time'),'sha256':(f.get('digests') or {}).get('sha256'),'yanked':bool(f.get('yanked',False))} for f in files]})
tag_rows=[{'name':t.get('name'),'commit_sha':(t.get('commit') or {}).get('sha'),'tarball_url':t.get('tarball_url'),'zipball_url':t.get('zipball_url')} for t in tags]
seed={'schema':'vcs.dulwich.catalog.v1','source':{'name':'Dulwich PyPI/GitHub release catalog','license':'Apache-2.0 OR GPL-2.0-or-later (Apache-2.0 path selected)','retrieved_at_unix':receipt.get('retrieved_at_unix')},'summary':{'latest_version':info.get('version'),'release_count':len(release_rows),'release_limit':limit,'tag_count':len(tag_rows),'package_archives_ingested':False,'source_bodies_ingested':False,'git_operation_execution':False,'mirror_graph_wiring':False},'source_receipt':receipt,'project':{'name':info.get('name'),'version':info.get('version'),'license':info.get('license'),'requires_python':info.get('requires_python'),'classifiers':[c for c in info.get('classifiers',[]) if c.startswith(('Development Status','Environment','Intended Audience','License','Operating System','Programming Language','Topic'))]},'releases':release_rows,'tags':tag_rows}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/gen-vcs-dulwich-catalog.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: releases={len(release_rows)} tags={len(tag_rows)} latest={info.get("version")}')
PY
