#!/usr/bin/env bash
set -euo pipefail
ROOT="${PNIX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
SRC="${GO_SOURCE:-$ROOT/ingest/science/go/go-basic.obo}"
OUT="${GO_OUT:-$ROOT/stdlib/lib/corpus/go.generated.px}"
LIMIT="${GO_TERM_LIMIT:-1000}"
if [ ! -f "$SRC" ]; then
  echo "missing GO source: $SRC" >&2
  echo "run: scripts/update-science-go.sh" >&2
  exit 1
fi
mkdir -p "$(dirname "$OUT")"
python3 - "$SRC" "$OUT" "$LIMIT" <<'PY'
import hashlib, re, sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2]); limit=int(sys.argv[3])
text=src.read_text(encoding='utf-8', errors='replace')
sha=hashlib.sha256(src.read_bytes()).hexdigest()

def q(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')+'"'

def lit(v, indent=0):
    sp=' '*indent
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if v is None: return 'null'
    if isinstance(v,str): return q(v)
    if isinstance(v,list):
        if not v: return '[ ]'
        return '[\n'+''.join(' '*(indent+2)+lit(x, indent+2)+'\n' for x in v)+sp+']'
    if isinstance(v,dict):
        if not v: return '{ }'
        lines=['{']
        for k in v:
            lines.append(' '*(indent+2)+k+' = '+lit(v[k], indent+2)+';')
        lines.append(sp+'}')
        return '\n'.join(lines)
    raise TypeError(type(v))

def split_comment(rest):
    if ' ! ' in rest:
        a,_=rest.split(' ! ',1); return a.strip()
    return rest.strip()

def finish(block):
    rec={'id':'','name':'','namespace':'','alt_id':[],'subset':[],'is_a':[],'relationship':[],'is_obsolete':False,'replaced_by':[],'consider':[]}
    for line in block:
        if line.startswith('id: '): rec['id']=line[4:].strip()
        elif line.startswith('name: '): rec['name']=line[6:].strip()
        elif line.startswith('namespace: '): rec['namespace']=line[11:].strip()
        elif line.startswith('alt_id: '): rec['alt_id'].append(line[8:].strip())
        elif line.startswith('subset: '): rec['subset'].append(line[8:].strip())
        elif line.startswith('is_a: '): rec['is_a'].append(split_comment(line[6:]))
        elif line.startswith('relationship: '):
            main=split_comment(line[14:]); bits=main.split()
            if len(bits)>=2: rec['relationship'].append(bits[0]+' '+bits[1])
        elif line.startswith('is_obsolete: '): rec['is_obsolete']=line[13:].strip()=='true'
        elif line.startswith('replaced_by: '): rec['replaced_by'].append(line[13:].strip())
        elif line.startswith('consider: '): rec['consider'].append(line[10:].strip())
    if not rec['id']: return None
    compact={'id':rec['id'], 'name':rec['name']}
    for k in ['namespace','alt_id','subset','is_a','relationship','is_obsolete','replaced_by','consider']:
        v=rec[k]
        if v not in ('',[],False): compact[k]=v
    return compact
header={}; terms=[]; in_term=False; block=[]
for line in text.splitlines():
    if line == '[Term]':
        if in_term:
            r=finish(block)
            if r: terms.append(r)
        in_term=True; block=[]; continue
    if line.startswith('[') and line.endswith(']'):
        if in_term:
            r=finish(block)
            if r: terms.append(r)
        in_term=False; block=[]; continue
    if in_term:
        block.append(line)
    else:
        if line.startswith('data-version: '): header['data_version']=line.split(': ',1)[1]
        elif line.startswith('date: '): header['source_date']=line.split(': ',1)[1]
        elif line.startswith('ontology: '): header['ontology']=line.split(': ',1)[1]
if in_term:
    r=finish(block)
    if r: terms.append(r)
value={
  'schema':'bio.go.v1',
  'source':'Gene Ontology go-basic OBO',
  'license':'CC-BY-4.0',
  'source_url':'https://purl.obolibrary.org/obo/go/go-basic.obo',
  'source_sha256':sha,
  'data_version':header.get('data_version',''),
  'source_date':header.get('source_date',''),
  'term_limit':limit,
  'total_terms_seen':len(terms),
  'terms':terms[:limit],
}
out.write_text('# GENERATED by scripts/gen-science-go.sh; do not commit.\n'+lit(value)+'\n', encoding='utf-8')
print(f"generated {out}: terms={min(limit,len(terms))} total_terms={len(terms)} data_version={header.get('data_version','')} sha256={sha}")
PY
