#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/legal/congressgov-api-catalog"
OUT="$ROOT/stdlib/lib/corpus/congressgov-api-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json,pathlib,re,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,(int,float)): return str(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
sw=json.loads((src/'Documentation/swagger.json').read_text())
paths=[]
for path,methods in sorted((sw.get('paths') or {}).items()):
    for method,spec in sorted((methods or {}).items()):
        if method.startswith('x-'): continue
        params=[]
        for p in spec.get('parameters') or []:
            params.append({'name':p.get('name'), 'in':p.get('in'), 'required':bool(p.get('required')), 'schema_type':((p.get('schema') or {}).get('type'))})
        paths.append({'path':path,'method':method.upper(),'operation_id':spec.get('operationId'),'tags':spec.get('tags') or [],'parameters':params})
schemas=[]
components=(sw.get('components') or {}).get('schemas') or sw.get('definitions') or {}
for name,schema in sorted(components.items()):
    props=sorted((schema.get('properties') or {}).keys())[:80]
    schemas.append({'name':name,'type':schema.get('type'),'properties':props,'required':schema.get('required') or []})
docs=[]
for p in sorted((src/'Documentation').glob('*Endpoint.md')):
    txt=p.read_text(encoding='utf-8',errors='replace')
    headings=[]
    for m in re.finditer(r'^(#{1,6})\s+(.+)$',txt,re.M):
        title=re.sub(r'[`*_#]','',m.group(2)).strip()[:160]
        if title: headings.append({'level':len(m.group(1)),'title':title})
    docs.append({'file':p.name,'bytes':p.stat().st_size,'headings':headings[:40]})
obj={'schema':'legal.congressgov.api_catalog.v1','source':'Congress.gov API documentation metadata','license':'US-PD / Library of Congress public information metadata','summary':{'paths':len(paths),'schemas':len(schemas),'docs':len(docs)},'policy':'official API documentation metadata only; live payload calls, API keys, bill/law/report text, examples/prose bodies, legal/political advice, and graph wiring excluded','manifest':manifest,'api_info':{'title':(sw.get('info') or {}).get('title'),'version':(sw.get('info') or {}).get('version')},'paths':paths,'schemas':schemas,'documents':docs}
out.write_text('# GENERATED by scripts/gen-legal-congressgov-api-catalog.sh. Do not edit. Gitignored.\n# Source: Congress.gov API documentation metadata only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: paths={len(paths)} schemas={len(schemas)} docs={len(docs)} bytes={out.stat().st_size}')
PY
