#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/ml/torchmetrics-catalog"
OUT="$ROOT/stdlib/lib/corpus/torchmetrics-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import ast, pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for name in ['tree.json','LICENSE','source-manifest.json']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
symbols=[]; categories={}
base=src/'files'/'src'/'torchmetrics'
for p in sorted(base.rglob('*.py')):
    rel=str(p.relative_to(src/'files'))
    module=rel[:-3].replace('/','.')
    parts=rel.split('/')
    category=parts[2] if len(parts)>3 else 'core'
    categories[category]=categories.get(category,0)+1
    try: tree=ast.parse(p.read_text())
    except SyntaxError: continue
    for node in tree.body:
        if isinstance(node,(ast.FunctionDef,ast.AsyncFunctionDef,ast.ClassDef)) and not node.name.startswith('_'):
            symbols.append({'category':category,'module':module,'name':node.name,'kind':'class' if isinstance(node,ast.ClassDef) else 'function'})
seen=set(); uniq=[]
for r in sorted(symbols,key=lambda x:(x['category'],x['module'],x['kind'],x['name'])):
    key=(r['module'],r['kind'],r['name'])
    if key not in seen: seen.add(key); uniq.append(r)
category_rows=[{'name':k,'module_files':v} for k,v in sorted(categories.items())]
obj={'schema':'ml.torchmetrics.catalog.v1','source':'TorchMetrics metric symbol catalog','license':'Apache-2.0','summary':{'categories':len(category_rows),'modules':len(set(r['module'] for r in uniq)),'symbols':len(uniq)},'policy':'symbol names only; source bodies, docstrings, tests, datasets, eval results, runtime execution, graph wiring excluded','manifest':manifest,'files':files,'categories':category_rows,'symbols':uniq}
out.write_text('# GENERATED by scripts/gen-ml-torchmetrics-catalog.sh. Do not edit. Gitignored.\n# Source: TorchMetrics public metric symbol names only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: categories={len(category_rows)} symbols={len(uniq)} bytes={out.stat().st_size}')
PY
