#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/ocr/tesseract-catalog"
OUT="$ROOT/stdlib/lib/corpus/tesseract-catalog.generated.px"
LIMIT="${TESSERACT_FILE_LIMIT:-800}"
python3 - "$SRC" "$OUT" "$LIMIT" <<'PY'
import pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); limit=int(sys.argv[3])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for name in ['tree.json','LICENSE','source-manifest.json']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
tree=json.loads((src/'tree.json').read_text())
rows=[]; modules={}; exts={}
for row in tree.get('tree',[]):
    path=row.get('path','')
    if row.get('type')!='blob': continue
    if not (path.startswith('src/') or path.startswith('include/')): continue
    if not path.endswith(('.h','.hpp','.hh','.cpp','.cc','.c')): continue
    if 'test' in path.lower(): continue
    parts=path.split('/')
    area=parts[0]
    module=parts[1] if len(parts)>2 else area
    stem=parts[-1].rsplit('.',1)[0]
    ext=parts[-1].rsplit('.',1)[-1]
    key=area+'/'+module
    modules[key]=modules.get(key,0)+1
    exts[ext]=exts.get(ext,0)+1
    rows.append({'area':area,'module':module,'stem':stem,'extension':ext,'path':path})
rows=sorted(rows,key=lambda x:(x['area'],x['module'],x['path']))
module_rows=[{'name':k,'file_count':v} for k,v in sorted(modules.items())]
ext_rows=[{'extension':k,'file_count':v} for k,v in sorted(exts.items())]
obj={'schema':'ocr.tesseract.catalog.v1','source':'Tesseract OCR repository tree source catalog','license':'Apache-2.0','summary':{'modules':len(module_rows),'extensions':len(ext_rows),'files':min(len(rows),limit),'files_total_seen':len(rows),'limit':limit},'policy':'Git tree module/file path metadata only; source bodies, docs prose, tests, traineddata/model files, images/PDFs, OCR outputs, runtime execution, graph wiring excluded','manifest':manifest,'files':files,'modules':module_rows,'extensions':ext_rows,'source_files':rows[:limit]}
out.write_text('# GENERATED by scripts/gen-ocr-tesseract-catalog.sh. Do not edit. Gitignored.\n# Source: Tesseract Git tree source path metadata only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: modules={len(module_rows)} files={min(len(rows),limit)}/{len(rows)} bytes={out.stat().st_size}')
PY
