#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/regulatory/federal-register-api"
OUT="$ROOT/stdlib/lib/corpus/federal-register-api.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def typ(v):
    if isinstance(v,bool): return 'bool'
    if isinstance(v,int): return 'int'
    if isinstance(v,float): return 'float'
    if isinstance(v,str): return 'string'
    if isinstance(v,list): return 'list'
    if isinstance(v,dict): return 'object'
    if v is None: return 'null'
    return type(v).__name__
def schema_of(prefix,obj,limit=240):
    rows=[]
    def walk(path,v):
        if len(rows)>=limit: return
        rows.append({'path':path,'type':typ(v)})
        if isinstance(v,dict):
            for k,val in sorted(v.items()): walk(path+'.'+k if path else k,val)
        elif isinstance(v,list) and v:
            walk(path+'[]',v[0])
    walk(prefix,obj)
    return rows
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
doc_sample=json.loads((src/'documents-sample.json').read_text()) if (src/'documents-sample.json').exists() else {}
agencies=json.loads((src/'agencies.json').read_text()) if (src/'agencies.json').exists() else []
agency_rows=[]
for a in agencies[:120]:
    agency_rows.append({'slug':a.get('slug',''),'name':clean(a.get('name',''))[:160],'parent_id':a.get('parent_id') or 0,'url':a.get('url',''),'json_url':a.get('json_url','')})
endpoints=[
    {'name':'documents','method':'GET','url':'https://www.federalregister.gov/api/v1/documents.json','params':['per_page','page','order','conditions[type][]','conditions[agencies][]','conditions[publication_date][gte]','conditions[publication_date][lte]']},
    {'name':'document','method':'GET','url':'https://www.federalregister.gov/api/v1/documents/{document_number}.json','params':['document_number']},
    {'name':'agencies','method':'GET','url':'https://www.federalregister.gov/api/v1/agencies.json','params':[]},
    {'name':'suggested_searches','method':'GET','url':'https://www.federalregister.gov/api/v1/suggested_searches.json','params':[]}
]
files=[]
for p in [src/'source-manifest.json',src/'api-docs.html',src/'documents-sample.json',src/'agencies.json']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'regulatory.federal_register.api_schema.v1','source':'Federal Register API endpoint/schema metadata','license':'US-PD / US federal public information','summary':{'endpoints':len(endpoints),'document_schema_paths':len(schema_of('documents_response',doc_sample)),'agencies':len(agency_rows),'files':len(files)},'policy':'endpoint catalog and response key/type inventory only; document/rule bodies, abstracts, titles as prose content, comments, legal/compliance advice, and graph wiring excluded','manifest':manifest,'files':files,'endpoints':endpoints,'document_response_schema':schema_of('documents_response',doc_sample),'agency_schema':schema_of('agency',agencies[0] if agencies else {}),'agencies_bounded':agency_rows}
out.write_text('# GENERATED by scripts/gen-regulatory-federal-register-api.sh. Do not edit. Gitignored.\n# Source: Federal Register API schema metadata only; document bodies/prose/legal advice excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: endpoints={len(endpoints)} schema_paths={obj["summary"]["document_schema_paths"]} agencies={len(agency_rows)} bytes={out.stat().st_size}')
PY
