#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/workforce/onet-database/unpacked"
OUT="$ROOT/stdlib/lib/corpus/onet-database.generated.px"
OCC_LIMIT="${ONET_OCC_LIMIT:-300}"
ROW_LIMIT="${ONET_ROW_LIMIT:-600}"
SOFT_LIMIT="${ONET_SOFTWARE_LIMIT:-500}"
python3 - "$SRC" "$OUT" "$OCC_LIMIT" "$ROW_LIMIT" "$SOFT_LIMIT" <<'PY'
import csv, sys, pathlib, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); occ_lim=int(sys.argv[3]); row_lim=int(sys.argv[4]); soft_lim=int(sys.argv[5])
root=next(src.glob('db_*_text'), src)

def esc(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n',' ').replace('\r','')+'"'

def arr(xs): return '[ ' + ' '.join(esc(x) for x in xs if x) + ' ]'

def read_tsv(name):
    p=root/name
    with p.open(encoding='utf-8-sig', newline='') as f:
        yield from csv.DictReader(f, delimiter='\t')

def file_hash(name):
    p=root/name
    return hashlib.sha256(p.read_bytes()).hexdigest() if p.exists() else ''

occupations=[]
for r in read_tsv('Occupation Data.txt'):
    occupations.append({'code':r.get('O*NET-SOC Code',''), 'title':r.get('Title','')})
    if len(occupations)>=occ_lim: break
rating_files=[('abilities','Abilities.txt'),('knowledge','Knowledge.txt'),('work_activities','Work Activities.txt'),('essential_skills','Essential Skills.txt')]
ratings=[]; file_summaries=[]
for kind, fn in rating_files:
    n=0
    for r in read_tsv(fn):
        ratings.append({
            'kind':kind,
            'occupation_code':r.get('O*NET-SOC Code',''),
            'element_id':r.get('Element ID',''),
            'element_name':r.get('Element Name',''),
            'scale_id':r.get('Scale ID',''),
            'data_value':r.get('Data Value',''),
            'date':r.get('Date',''),
            'domain_source':r.get('Domain Source','')
        })
        n+=1
        if n>=row_lim: break
    file_summaries.append({'name':fn,'kind':kind,'rows_kept':n,'sha256':file_hash(fn)})
software=[]; n=0
for r in read_tsv('Software Skills.txt'):
    software.append({
        'occupation_code':r.get('O*NET-SOC Code',''),
        'workplace_example':r.get('Workplace Example',''),
        'element_id':r.get('Element ID',''),
        'element_name':r.get('Element Name',''),
        'hot_technology':r.get('Hot Technology',''),
        'in_demand':r.get('In Demand','')
    })
    n+=1
    if n>=soft_lim: break
file_summaries.append({'name':'Software Skills.txt','kind':'software_skills','rows_kept':len(software),'sha256':file_hash('Software Skills.txt')})
file_summaries.append({'name':'Occupation Data.txt','kind':'occupation_titles','rows_kept':len(occupations),'sha256':file_hash('Occupation Data.txt')})

lines=['''# GENERATED by scripts/gen-workforce-onet-database.sh. Do not edit. Gitignored.
# Source: O*NET 30.3 Database text format (USDOL/ETA, CC-BY-4.0).
# Policy: bounded structure only; occupation descriptions/prose/career advice/statistics excluded.
{ schema = "workforce.onet_database.structure.v1";
  source = "O*NET 30.3 Database";
  license = "CC-BY-4.0";
  attribution = "O*NET 30.3 Database by USDOL/ETA, used under CC BY 4.0; pnix has modified selected bounded structural rows.";
''']
lines.append(f'  summary = {{ occupations = {len(occupations)}; rating_rows = {len(ratings)}; software_rows = {len(software)}; occupation_limit = {occ_lim}; row_limit_per_rating_file = {row_lim}; software_limit = {soft_lim}; }};\n')
lines.append('  source_files = [\n')
for s in file_summaries:
    lines.append('    { name = '+esc(s['name'])+'; kind = '+esc(s['kind'])+'; rows_kept = '+str(s['rows_kept'])+'; sha256 = '+esc(s['sha256'])+'; }\n')
lines.append('  ];\n  occupations = [\n')
for o in occupations:
    lines.append('    { code = '+esc(o['code'])+'; title = '+esc(o['title'])+'; }\n')
lines.append('  ];\n  ratings = [\n')
for r in ratings:
    lines.append('    { kind = '+esc(r['kind'])+'; occupation_code = '+esc(r['occupation_code'])+'; element_id = '+esc(r['element_id'])+'; element_name = '+esc(r['element_name'])+'; scale_id = '+esc(r['scale_id'])+'; data_value = '+esc(r['data_value'])+'; date = '+esc(r['date'])+'; domain_source = '+esc(r['domain_source'])+'; }\n')
lines.append('  ];\n  software_skills = [\n')
for r in software:
    lines.append('    { occupation_code = '+esc(r['occupation_code'])+'; workplace_example = '+esc(r['workplace_example'])+'; element_id = '+esc(r['element_id'])+'; element_name = '+esc(r['element_name'])+'; hot_technology = '+esc(r['hot_technology'])+'; in_demand = '+esc(r['in_demand'])+'; }\n')
lines.append('  ];\n}\n')
out.write_text(''.join(lines), encoding='utf-8')
print(f'generated {out}: occupations={len(occupations)} ratings={len(ratings)} software={len(software)} bytes={out.stat().st_size}')
PY
