#!/usr/bin/env bash
set -euo pipefail
ROOT="${PNIX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
SRC_DIR="${RHEA_SOURCE:-$ROOT/ingest/science/rhea/tsv}"
TAR="$ROOT/ingest/science/rhea/rhea-tsv.tar.gz"
OUT="${RHEA_OUT:-$ROOT/stdlib/lib/corpus/rhea.generated.px}"
LIMIT="${RHEA_RECORD_LIMIT:-1000}"
if [ -d "$SRC_DIR/tsv" ]; then
  SRC_DIR="$SRC_DIR/tsv"
fi
if [ ! -d "$SRC_DIR" ]; then
  echo "missing Rhea source dir: $SRC_DIR" >&2
  echo "run: scripts/update-science-rhea.sh" >&2
  exit 1
fi
mkdir -p "$(dirname "$OUT")"
python3 - "$SRC_DIR" "$TAR" "$OUT" "$LIMIT" <<'PY'
import csv, hashlib, sys
from pathlib import Path
src=Path(sys.argv[1]); tar=Path(sys.argv[2]); out=Path(sys.argv[3]); limit=int(sys.argv[4])

def q(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')+'"'

def lit(v, indent=0):
    sp=' '*indent
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if v is None: return 'null'
    if isinstance(v,str): return q(v)
    if isinstance(v,list):
        if not v: return '[ ]'
        return '[\n'+''.join(' '*(indent+2)+lit(x, indent+2)+'\n' for x in v)+sp+']'
    if isinstance(v,dict):
        if not v: return '{ }'
        lines=['{']
        for k in v:
            lines.append(' '*(indent+2)+k+' = '+lit(v[k], indent+2)+';')
        lines.append(sp+'}')
        return '\n'.join(lines)
    raise TypeError(type(v))

def tsv_rows(path):
    with path.open(encoding='utf-8', errors='replace', newline='') as f:
        return list(csv.DictReader(f, delimiter='\t'))

# Inspect available files robustly; current release uses directions/relationships plus mapping/xref TSVs.
directions_file=src/'rhea-directions.tsv'
relationships_file=src/'rhea-relationships.tsv'
# Safety: avoid reaction SMILES and UniProt/pathway bulk links. Use ChEBI id/name or pH mapping only.
chebi_file=src/'chebi_pH7_3_mapping.tsv'
if not chebi_file.exists():
    chebi_file=src/'chebiId_name.tsv'

directions=[]; total_directions=0
if directions_file.exists():
    for r in tsv_rows(directions_file):
        total_directions += 1
        if len(directions) < limit:
            rec={k.lower().replace(' ','_').replace('-','_'):v for k,v in r.items() if v not in ('',None)}
            directions.append(rec)
relationships=[]; total_relationships=0
if relationships_file.exists():
    for r in tsv_rows(relationships_file):
        total_relationships += 1
        if len(relationships) < limit:
            rec={k.lower().replace(' ','_').replace('-','_'):v for k,v in r.items() if v not in ('',None)}
            relationships.append(rec)
chebi_refs=[]; total_chebi=0
if chebi_file.exists():
    for r in tsv_rows(chebi_file):
        total_chebi += 1
        if len(chebi_refs) < limit:
            rec={k.lower().replace(' ','_').replace('-','_'):v for k,v in r.items() if v not in ('',None)}
            chebi_refs.append(rec)
sha=hashlib.sha256(tar.read_bytes()).hexdigest() if tar.exists() else ''
value={
  'schema':'molecular.rhea.v1',
  'source':'Rhea TSV release',
  'license':'CC-BY-4.0',
  'source_url':'https://ftp.expasy.org/databases/rhea/tsv/rhea-tsv.tar.gz',
  'source_sha256':sha,
  'record_limit':limit,
  'total_directions_seen':total_directions,
  'total_relationships_seen':total_relationships,
  'total_chebi_refs_seen':total_chebi,
  'directions':directions,
  'relationships':relationships,
  'chebi_refs':chebi_refs,
}
out.write_text('# GENERATED by scripts/gen-science-rhea.sh; do not commit.\n'+lit(value)+'\n', encoding='utf-8')
print(f"generated {out}: directions={len(directions)} relationships={len(relationships)} chebi_refs={len(chebi_refs)} sha256={sha}")
PY
