#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${TDWG_DWC_SRC:-$ROOT/ingest/biodiversity/tdwg-darwin-core}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/tdwg-darwin-core.generated.px}"
TERM_LIMIT="${TDWG_DWC_TERM_LIMIT:-500}"
python3 - "$SRC" "$OUT" "$TERM_LIMIT" <<'PY'
import csv, json, sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2]); limit=int(sys.argv[3])
receipt=json.loads((src/'source-receipt.json').read_text())

def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,(int,float)): return repr(v)
    if isinstance(v,str): return json.dumps(v, ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))
rows=[]; total=0; status_counts={}
with (src/'raw/term_versions.csv').open(newline='', encoding='utf-8') as f:
    for r in csv.DictReader(f):
        total += 1
        status=r.get('status','')
        status_counts[status]=status_counts.get(status,0)+1
        if limit>0 and len(rows)>=limit:
            continue
        rows.append({
            'iri':r.get('iri',''),
            'local_name':r.get('term_localName',''),
            'label':r.get('label',''),
            'organized_in':r.get('organized_in',''),
            'issued':r.get('issued',''),
            'status':status,
            'replaces':r.get('replaces',''),
            'rdf_type':r.get('rdf_type',''),
            'term_iri':r.get('term_iri',''),
            'abcd_equivalence':r.get('abcd_equivalence',''),
            'flags':r.get('flags','')
        })
seed={'schema':'biodiversity.tdwg_darwin_core.v1','source':{'name':'TDWG Darwin Core vocabulary term metadata','license':'CC-BY-4.0','retrieved_at':receipt.get('retrieved_at'),'ref':receipt.get('ref')},'summary':{'term_count':len(rows),'total_available_term_count':total,'term_limit':limit,'status_counts':status_counts,'definition_prose_ingested':False,'comments_ingested':False,'examples_ingested':False,'occurrence_rows_ingested':False,'coordinates_ingested':False,'media_ingested':False,'personal_data_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'terms':rows}
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('# GENERATED by scripts/gen-biodiversity-tdwg-darwin-core.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: terms={len(rows)}, total={total}')
PY
