#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/code/lucene-catalog"
OUT="$ROOT/stdlib/lib/corpus/lucene-catalog.generated.px"
LIMIT="${LUCENE_CATALOG_LIMIT:-1200}"
python3 - "$SRC" "$OUT" "$LIMIT" <<'PY'
import pathlib, sys, json, hashlib, re
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); limit=int(sys.argv[3])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
tree=json.loads((src/'tree.json').read_text())
release={}
if (src/'release.json').exists(): release=json.loads((src/'release.json').read_text())
files=[]
for name in ['tree.json','release.json']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
modules={}; classes=[]
selected_prefixes=('lucene/core/src/java/','lucene/analysis/','lucene/queryparser/','lucene/highlighter/','lucene/join/','lucene/facet/','lucene/sandbox/')
for row in tree.get('tree',[]):
    path=row.get('path','')
    if row.get('type')!='blob' or not path.endswith('.java'): continue
    if '/src/test/' in path or '/test-framework/' in path or '/benchmark/' in path or '/src/tools/' in path: continue
    if not path.startswith(selected_prefixes): continue
    parts=path.split('/')
    module='/'.join(parts[:2]) if len(parts)>2 and parts[0]=='lucene' else parts[0]
    modules[module]=modules.get(module,0)+1
    cls=parts[-1][:-5]
    package=''
    if '/src/java/' in path:
        package=path.split('/src/java/',1)[1].rsplit('/',1)[0].replace('/','.')
    elif '/src/main/java/' in path:
        package=path.split('/src/main/java/',1)[1].rsplit('/',1)[0].replace('/','.')
    kind='class'
    if cls.endswith('Analyzer'): kind='analyzer'
    elif cls.endswith('Query') or 'queryparser' in path: kind='query'
    elif cls.endswith('Tokenizer') or cls.endswith('TokenFilter') or cls.endswith('Filter'): kind='analysis_component'
    elif cls.endswith('Codec') or 'codecs' in path: kind='codec'
    classes.append({'module':module,'path':path,'package':package,'name':cls,'kind':kind})
classes=classes[:limit]
module_rows=[{'module':k,'java_source_count_seen':v} for k,v in sorted(modules.items())]
obj={'schema':'search.lucene.catalog.v1','source':'Apache Lucene release source catalog','license':'Apache-2.0','summary':{'modules':len(module_rows),'classes':len(classes),'class_limit':limit,'total_java_sources_seen':sum(modules.values())},'policy':'release tree path/class metadata only; source bodies, docs prose, tests/testdata, benchmarks, real indices/queries, ranking judgments, execution, graph wiring excluded','manifest':manifest,'release':{'tag':release.get('tag_name',''),'name':release.get('name','')},'files':files,'modules':module_rows,'classes':classes}
out.write_text('# GENERATED by scripts/gen-code-lucene-catalog.sh. Do not edit. Gitignored.\n# Source: Apache Lucene release tree path metadata.\n# Policy: module/package/class catalog only; source bodies/tests/prose/execution excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: modules={len(module_rows)} classes={len(classes)} total_seen={sum(modules.values())} bytes={out.stat().st_size}')
PY
