#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${OTEL_SEMCONV_SRC:-$ROOT/ingest/telemetry/opentelemetry-semconv}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/opentelemetry-semconv.generated.px}"
python3 - "$SRC" "$OUT" <<'PY'
import json,re,sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2])
receipt=json.loads((src/'source-receipt.json').read_text())
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return json.dumps(v,ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v[k])+';' for k in sorted(v)) + ' }'
    if v is None: return 'null'
    raise TypeError(type(v))
files=[]; groups=[]; attrs=[]; members=[]
for rec in receipt['files']:
    path=rec['source_path']; text=(src/'raw'/rec['local_file']).read_text(encoding='utf-8',errors='replace')
    files.append({'source_path':path,'sha256':rec['sha256'],'bytes':rec['bytes']})
    current_group=None; in_attrs=False; current_attr=None; in_members=False; current_member=None
    for line in text.splitlines():
        if re.match(r'^  - id:\s*', line):
            gid=line.split(':',1)[1].strip().strip('"\'')
            current_group={'file':path,'id':gid,'type':'','display_name':''}; groups.append(current_group); in_attrs=False; current_attr=None; in_members=False; continue
        if current_group and re.match(r'^    type:\s*', line) and not current_attr:
            current_group['type']=line.split(':',1)[1].strip().strip('"\''); continue
        if current_group and re.match(r'^    display_name:\s*', line):
            current_group['display_name']=line.split(':',1)[1].strip().strip('"\''); continue
        if re.match(r'^    attributes:\s*$', line):
            in_attrs=True; current_attr=None; in_members=False; continue
        if in_attrs and re.match(r'^      - id:\s*', line):
            aid=line.split(':',1)[1].strip().strip('"\'')
            current_attr={'file':path,'group_id':current_group['id'] if current_group else '', 'id':aid,'stability':'','requirement_level':'','type':''}
            attrs.append(current_attr); in_members=False; current_member=None; continue
        if current_attr and re.match(r'^        (stability|requirement_level):\s*', line):
            k,v=line.strip().split(':',1); current_attr[k]=v.strip().strip('"\''); continue
        if current_attr and re.match(r'^        type:\s*\S+', line):
            current_attr['type']=line.split(':',1)[1].strip().strip('"\''); continue
        if current_attr and re.match(r'^          members:\s*$', line):
            in_members=True; continue
        if current_attr and in_members and re.match(r'^            - id:\s*', line):
            mid=line.split(':',1)[1].strip().strip('"\'')
            current_member={'file':path,'attribute_id':current_attr['id'],'id':mid,'value':'','stability':''}
            members.append(current_member); continue
        if current_member and re.match(r'^              (value|stability):\s*', line):
            k,v=line.strip().split(':',1); current_member[k]=v.strip().strip('"\'')
obj={'schema':'telemetry.opentelemetry.semantic_conventions.v1','source':{'name':'OpenTelemetry Semantic Conventions model YAML','license':'Apache-2.0','source_urls':['https://github.com/open-telemetry/semantic-conventions','https://github.com/open-telemetry/semantic-conventions/tree/'+receipt.get('ref','')+'/model'],'receipt':receipt,'generator':'scripts/gen-telemetry-opentelemetry-semconv.sh','scope':'model YAML structural tokens only; prose/examples/real telemetry/credentials/alert routing/execution/graph wiring excluded'},'summary':{'source_file_count':len(files),'group_count':len(groups),'attribute_count':len(attrs),'enum_member_count':len(members),'prose_ingested':False,'real_telemetry_ingested':False,'credentials_ingested':False,'alert_routing_enabled':False,'mirror_graph_wiring':False},'source_files':files,'groups':groups,'attributes':attrs[:4000],'enum_members':members[:4000]}
out.parent.mkdir(parents=True,exist_ok=True)
out.write_text('# GENERATED by scripts/update-telemetry-opentelemetry-semconv.sh && scripts/gen-telemetry-opentelemetry-semconv.sh; do not commit.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: files={len(files)} groups={len(groups)} attrs={len(attrs)} enum_members={len(members)} bytes={out.stat().st_size}')
PY
