#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/water/wqp-api-catalog"
OUT="$ROOT/stdlib/lib/corpus/wqp-api-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import html, json, pathlib, re, sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text(encoding='utf-8')) if (src/'source-manifest.json').exists() else {}
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,(int,float)): return str(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
def clean(s):
    s=html.unescape(re.sub(r'<[^>]+>',' ',s))
    return re.sub(r'\s+',' ',s).strip()
pages=[]
link_re=re.compile(r'href=["\']([^"\']+)["\']',re.I)
endpoint_re=re.compile(r'/(?:data|mime|providers?)/[A-Za-z0-9_./?=&%-]+')
for p in sorted(src.glob('*.html')):
    txt=p.read_text(encoding='utf-8',errors='replace')
    title=''
    m=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
    if m: title=clean(m.group(1))[:180]
    links=[]
    for href in link_re.findall(txt):
        if any(t in href.lower() for t in ['webservice','data/','station','result','activity','project','organization','waterqualitydata']):
            links.append(href[:260])
    endpoints=sorted(set(x.split('#')[0][:220] for x in endpoint_re.findall(txt)))[:80]
    pages.append({'file':p.name,'title':title,'bytes':p.stat().st_size,'links':sorted(set(links))[:80],'endpoint_hints':endpoints})
static_endpoints=[
  {'name':'station_search','path':'/data/Station/search','payload':'excluded'},
  {'name':'result_search','path':'/data/Result/search','payload':'excluded'},
  {'name':'activity_search','path':'/data/Activity/search','payload':'excluded'},
  {'name':'activity_metric_search','path':'/data/ActivityMetric/search','payload':'excluded'},
  {'name':'biological_metric_search','path':'/data/BiologicalMetric/search','payload':'excluded'},
  {'name':'project_search','path':'/data/Project/search','payload':'excluded'},
  {'name':'organization_search','path':'/data/Organization/search','payload':'excluded'},
  {'name':'result_detection_quantitation_limit_search','path':'/data/ResultDetectionQuantitationLimit/search','payload':'excluded'}
]
obj={'schema':'water.wqp.api_catalog.v1','source':'Water Quality Portal API catalog metadata','license':'US-PD / official public documentation metadata','summary':{'pages':len(pages),'links':sum(len(x['links']) for x in pages),'endpoint_hints':sum(len(x['endpoint_hints']) for x in pages),'endpoints':len(static_endpoints)},'policy':'official WQP web-service catalog metadata only; monitoring rows, provider payload values, coordinates/addresses, safety/legal/medical judgments, and graph wiring excluded','manifest':manifest,'pages':pages,'endpoints':static_endpoints}
out.write_text('# GENERATED by scripts/gen-water-wqp-api-catalog.sh. Do not edit. Gitignored.\n# Source: Water Quality Portal API catalog metadata only; monitoring rows/provider payloads excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} endpoints={len(static_endpoints)} bytes={out.stat().st_size}')
PY
