#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${SBOM_SCHEMA_SRC:-$ROOT/ingest/sbom/format-schemas}"
OUT="${SBOM_SCHEMA_OUT:-$ROOT/stdlib/lib/corpus/sbom-format-schemas.generated.px}"
python3 - <<'PY' "$SRC" "$OUT"
import json,pathlib,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
files=[]; defs=[]; props=[]; enums=[]
for meta in receipt.get('files',[]):
    p=src/meta['path']; d=json.loads(p.read_text())
    fmt='cyclonedx' if 'cyclonedx' in p.name else 'spdx'
    files.append({'format':fmt,'path':meta['path'],'sha256':meta['sha256'],'bytes':meta['bytes'],'schema_id':d.get('$id'),'schema_dialect':d.get('$schema')})
    containers=[]
    for key in ['definitions','$defs']:
        if isinstance(d.get(key),dict): containers.append((key,d[key]))
    for cname,c in containers:
        for name,val in list(c.items())[:1500]:
            if isinstance(val,dict):
                defs.append({'format':fmt,'container':cname,'name':name,'type':val.get('type')})
                for pn,pv in list((val.get('properties') or {}).items())[:200]:
                    props.append({'format':fmt,'definition':name,'property':pn,'type':pv.get('type') if isinstance(pv,dict) else None})
                if isinstance(val.get('enum'),list):
                    for e in val.get('enum')[:200]: enums.append({'format':fmt,'definition':name,'value':str(e)})
    for pn,pv in list((d.get('properties') or {}).items())[:500]:
        props.append({'format':fmt,'definition':'<root>','property':pn,'type':pv.get('type') if isinstance(pv,dict) else None})
def esc(s): s='' if s is None else str(s); return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'
def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return esc(v)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))
seed={'schema':'sbom.format_schemas.v1','source':{'name':'CycloneDX/SPDX SBOM format schemas','license':'CycloneDX Apache-2.0; SPDX public schema metadata','retrieved_at_unix':receipt.get('retrieved_at_unix')},'summary':{'schema_file_count':len(files),'definition_count':len(defs),'property_count':len(props),'enum_value_count':len(enums),'actual_sbom_documents_ingested':False,'customer_inventory_ingested':False,'compliance_judgment_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'schema_files':files,'definitions':defs,'properties':props[:3000],'enum_values':enums[:1000]}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/gen-sbom-format-schemas.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: files={len(files)}, definitions={len(defs)}, properties={len(props)}, enums={len(enums)}')
PY
