#!/usr/bin/env bash
set -euo pipefail
# JARVIS-DFT JSON -> pnix attrset source. Computed materials properties only; accepted_truth=false.
ROOT="${PNIX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
SRC="${JARVIS_SOURCE:-$ROOT/ingest/materials/jarvis/unpacked/jdft_3d-9-24-2025.json}"
ZIP="$ROOT/ingest/materials/jarvis/jdft_3d-9-24-2025.json.zip"
ARTICLE="$ROOT/ingest/materials/jarvis/article.json"
OUT="${JARVIS_OUT:-$ROOT/stdlib/lib/corpus/jarvis.generated.px}"
LIMIT="${JARVIS_RECORD_LIMIT:-1000}"
if [ ! -f "$SRC" ]; then
  echo "missing JARVIS source: $SRC" >&2
  echo "run: scripts/update-materials-jarvis.sh" >&2
  exit 1
fi
mkdir -p "$(dirname "$OUT")"
python3 - "$SRC" "$ZIP" "$ARTICLE" "$OUT" "$LIMIT" <<'PY'
import hashlib, json, sys
from pathlib import Path
src=Path(sys.argv[1]); zipf=Path(sys.argv[2]); article_path=Path(sys.argv[3]); out=Path(sys.argv[4]); limit=int(sys.argv[5])

def q(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')+'"'

def lit(v, indent=0):
    sp=' '*indent
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,(int,float)) and not isinstance(v,bool): return repr(v)
    if v is None: return 'null'
    if isinstance(v,str): return q(v)
    if isinstance(v,list):
        if not v: return '[ ]'
        return '[\n'+''.join(' '*(indent+2)+lit(x, indent+2)+'\n' for x in v)+sp+']'
    if isinstance(v,dict):
        if not v: return '{ }'
        lines=['{']
        for k in v:
            lines.append(' '*(indent+2)+k+' = '+lit(v[k], indent+2)+';')
        lines.append(sp+'}')
        return '\n'.join(lines)
    raise TypeError(type(v))

def clean(v):
    return None if v in ('na','',[],{}) else v

def put(rec, out, src_key, out_key=None):
    v=clean(rec.get(src_key))
    if v is not None:
        out[out_key or src_key.replace('-','_')] = v

article={}
if article_path.exists():
    article=json.load(article_path.open())
data=json.load(src.open())
records=[]
for r in data[:limit]:
    atoms=r.get('atoms') or {}
    rec={
      'jid': r.get('jid',''),
      'accepted_truth': False,
      'method': clean(r.get('func')) or 'DFT',
    }
    for k in ['formula','spg_number','spg_symbol','crys','typ','dimensionality','nat','density','formation_energy_peratom','optb88vdw_bandgap','mbj_bandgap','hse_gap','ehull','magmom_oszicar','magmom_outcar','bulk_modulus_kv','shear_modulus_gv','poisson','encut','kpoint_length_unit','reference']:
        put(r, rec, k)
    if atoms:
        a={}
        for k in ['elements','abc','angles']:
            v=clean(atoms.get(k))
            if v is not None: a[k]=v
        if a: rec['atoms_summary']=a
    records.append(rec)
sha=hashlib.sha256(zipf.read_bytes()).hexdigest() if zipf.exists() else ''
value={
  'schema':'materials.jarvis.v1',
  'source':'JARVIS-DFT 3D Figshare JSON',
  'license':'CC-BY-4.0',
  'source_url':'https://api.figshare.com/v2/articles/6815699',
  'source_file':'jdft_3d-9-24-2025.json.zip',
  'source_sha256':sha,
  'article_version': article.get('version',''),
  'doi': article.get('doi',''),
  'record_limit':limit,
  'total_records_seen':len(data),
  'records':records,
}
out.write_text('# GENERATED by scripts/gen-materials-jarvis.sh; do not commit.\n'+lit(value)+'\n', encoding='utf-8')
print(f"generated {out}: records={len(records)} total={len(data)} sha256={sha}")
PY
