#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/ml/sklearn-metrics"
OUT="$ROOT/stdlib/lib/corpus/sklearn-metrics.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import ast, pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for name in ['tree.json','COPYING','source-manifest.json']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
symbols=[]; scorers=[]
for p in sorted((src/'files'/'sklearn'/'metrics').rglob('*.py')):
    rel=str(p.relative_to(src/'files'))
    mod=rel[:-3].replace('/','.')
    tree=ast.parse(p.read_text())
    for node in tree.body:
        if isinstance(node,(ast.FunctionDef,ast.AsyncFunctionDef,ast.ClassDef)) and not node.name.startswith('_'):
            symbols.append({'module':mod,'name':node.name,'kind':'class' if isinstance(node,ast.ClassDef) else 'function'})
        if isinstance(node,ast.Assign):
            names=[t.id for t in node.targets if isinstance(t,ast.Name)]
            if '_SCORERS' in names and isinstance(node.value,ast.Dict):
                for k in node.value.keys:
                    if isinstance(k,ast.Constant) and isinstance(k.value,str):
                        scorers.append({'name':k.value,'module':mod})
    if rel.endswith('sklearn/metrics/_scorer.py'):
        text=p.read_text()
        m=__import__('re').search(r'_SCORERS\s*=\s*dict\((.*?)\n\)', text, __import__('re').S)
        if m:
            for name in __import__('re').findall(r'^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=', m.group(1), __import__('re').M):
                scorers.append({'name':name,'module':mod})
        for base in ['precision','recall','f1','jaccard']:
            scorers.append({'name':base,'module':mod})
            for avg in ['macro','micro','samples','weighted']:
                scorers.append({'name':base+'_'+avg,'module':mod})
# de-dup stable
seen=set(); uniq=[]
for r in sorted(symbols,key=lambda x:(x['module'],x['kind'],x['name'])):
    key=(r['module'],r['kind'],r['name'])
    if key not in seen: seen.add(key); uniq.append(r)
seen=set(); sc=[]
for r in sorted(scorers,key=lambda x:x['name']):
    if r['name'] not in seen: seen.add(r['name']); sc.append(r)
obj={'schema':'ml.sklearn.metrics_catalog.v1','source':'scikit-learn sklearn.metrics symbol catalog','license':'BSD-3-Clause','summary':{'modules':len(set(r['module'] for r in uniq)),'symbols':len(uniq),'scorers':len(sc)},'policy':'symbol names only; source bodies, docstrings, tests, datasets, eval results, runtime execution, graph wiring excluded','manifest':manifest,'files':files,'symbols':uniq,'scorers':sc}
out.write_text('# GENERATED by scripts/gen-ml-sklearn-metrics.sh. Do not edit. Gitignored.\n# Source: scikit-learn sklearn.metrics symbol names only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: symbols={len(uniq)} scorers={len(sc)} bytes={out.stat().st_size}')
PY
