#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${OPENMETRICS_SRC:-$ROOT/ingest/telemetry/openmetrics}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/openmetrics.generated.px}"
python3 - "$SRC" "$OUT" <<'PY'
import json,re,sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2])
receipt=json.loads((src/'source-receipt.json').read_text())
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return json.dumps(v,ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v[k])+';' for k in sorted(v)) + ' }'
    if v is None: return 'null'
    raise TypeError(type(v))
source_files=[]; messages=[]; enums=[]; fields=[]; code_lines=[]; table_rows=[]; tokens=[]; headings=[]
proto=(src/'raw/proto/openmetrics_data_model.proto').read_text()
cur_msg=''; cur_enum=''
for line in proto.splitlines():
    s=line.strip()
    m=re.match(r'message\s+(\w+)\s*\{',s)
    if m: cur_msg=m.group(1); messages.append({'name':cur_msg}); continue
    e=re.match(r'enum\s+(\w+)\s*\{',s)
    if e: cur_enum=e.group(1); enums.append({'name':cur_enum}); continue
    if s=='}': cur_msg=''; cur_enum=''; continue
    fm=re.match(r'(optional|required|repeated)?\s*([A-Za-z0-9_.]+)\s+(\w+)\s*=\s*(\d+)',s)
    if fm and cur_msg:
        fields.append({'message':cur_msg,'cardinality':fm.group(1) or 'singular','type':fm.group(2),'name':fm.group(3),'number':int(fm.group(4))})
    em=re.match(r'(\w+)\s*=\s*(\d+)',s)
    if em and cur_enum:
        enums.append({'enum':cur_enum,'name':em.group(1),'number':int(em.group(2))})
md=(src/'raw/specification/OpenMetrics.md').read_text()
in_code=False
for line in md.splitlines():
    hm=re.match(r'^(#{1,6})\s+(.+?)\s*$', line)
    if hm:
        headings.append({'level':len(hm.group(1)),'title':hm.group(2)[:160]})
    for bt in re.findall(r'`([^`]{1,120})`', line):
        if not any(c.isspace() for c in bt) or bt.startswith('#'):
            tokens.append({'token':bt[:120]})
    if line.startswith('```'):
        in_code=not in_code; continue
    if in_code:
        t=line.strip()
        if t and not t.startswith('#'):
            code_lines.append({'line':t[:240]})
            for tok in re.findall(r'[#A-Z_]{3,}|[a-zA-Z_][a-zA-Z0-9_]*(?:\{[^}]+\})?',t):
                if len(tok)>1: tokens.append({'token':tok[:120]})
    elif line.startswith('|') and not set(line.strip()) <= set('|-: '):
        cols=[c.strip() for c in line.strip('|').split('|')]
        if len(cols)>=2:
            table_rows.append({'cols':cols[:6]})
for rec in receipt['files']:
    source_files.append({'file':rec['file'],'sha256':rec['sha256'],'bytes':rec['bytes'],'role':rec['role']})
# de-dup tokens preserving order
seen=set(); tok2=[]
for t in tokens:
    if t['token'] not in seen:
        seen.add(t['token']); tok2.append(t)
obj={'schema':'telemetry.openmetrics.specification.v1','source':{'name':'OpenMetrics official specification structural metadata','license':'Apache-2.0','source_urls':['https://github.com/prometheus/OpenMetrics','https://github.com/prometheus/OpenMetrics/tree/'+receipt.get('ref','')],'receipt':receipt,'generator':'scripts/gen-telemetry-openmetrics.sh','scope':'proto and spec structural rows only; prose/real metrics/scrape data/alert routing/execution/graph wiring excluded'},'summary':{'source_file_count':len(source_files),'proto_message_count':len(messages),'proto_enum_row_count':len(enums),'proto_field_count':len(fields),'code_line_count':len(code_lines),'table_row_count':len(table_rows),'heading_count':len(headings),'token_count':len(tok2),'prose_body_ingested':False,'real_metrics_ingested':False,'scrape_targets_or_logs_ingested':False,'alert_routing_enabled':False,'execution_enabled':False,'mirror_graph_wiring':False},'source_files':source_files,'proto_messages':messages,'proto_enums':enums,'proto_fields':fields,'format_code_lines':code_lines[:300],'table_rows':table_rows[:120],'section_headings':headings[:200],'tokens':tok2[:500]}
out.parent.mkdir(parents=True,exist_ok=True)
out.write_text('# GENERATED by scripts/update-telemetry-openmetrics.sh && scripts/gen-telemetry-openmetrics.sh; do not commit.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: messages={len(messages)} fields={len(fields)} code_lines={len(code_lines)} table_rows={len(table_rows)} tokens={len(tok2)} bytes={out.stat().st_size}')
PY
