#!/usr/bin/env bash
set -euo pipefail
ROOT="${PNIX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
DUCK="${DUCKDB_BIN:-$ROOT/ingest/code/duckdb/bin/duckdb}"
REL="$ROOT/ingest/code/duckdb/release.json"
OUT="${DUCKDB_OUT:-$ROOT/stdlib/lib/corpus/duckdb.generated.px}"
FUNC_LIMIT="${DUCKDB_FUNCTION_LIMIT:-500}"
if [ ! -x "$DUCK" ]; then
  echo "missing duckdb binary: $DUCK" >&2
  echo "run: scripts/update-code-duckdb.sh" >&2
  exit 1
fi
mkdir -p "$(dirname "$OUT")"
python3 - "$DUCK" "$REL" "$OUT" "$FUNC_LIMIT" <<'PY'
import csv, hashlib, json, subprocess, sys
from io import StringIO
from pathlib import Path
duck=Path(sys.argv[1]); rel=Path(sys.argv[2]); out=Path(sys.argv[3]); limit=int(sys.argv[4])
release=json.load(rel.open()) if rel.exists() else {}

def q(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')+'"'

def lit(v, indent=0):
    sp=' '*indent
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if v is None: return 'null'
    if isinstance(v,str): return q(v)
    if isinstance(v,list):
        if not v: return '[ ]'
        return '[\n'+''.join(' '*(indent+2)+lit(x, indent+2)+'\n' for x in v)+sp+']'
    if isinstance(v,dict):
        if not v: return '{ }'
        lines=['{']
        for k in v:
            lines.append(' '*(indent+2)+k+' = '+lit(v[k], indent+2)+';')
        lines.append(sp+'}')
        return '\n'.join(lines)
    raise TypeError(type(v))

def query(sql):
    p=subprocess.run([str(duck), ':memory:', '-csv', '-c', sql], text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
    return list(csv.DictReader(StringIO(p.stdout)))
version=query('select version() as version')[0]['version']
try:
    kw=query('select keyword_name, keyword_category from duckdb_keywords() order by keyword_name')
except Exception:
    kw=[]
try:
    funcs=query(f"select function_name, function_type, return_type, parameters from duckdb_functions() order by function_name limit {limit}")
except Exception:
    funcs=[]
try:
    settings=query('select name, input_type, scope from duckdb_settings() order by name')
except Exception:
    settings=[]
value={
  'schema':'code.duckdb.metadata.v1',
  'source':'DuckDB CLI runtime metadata snapshot',
  'license':'MIT',
  'source_url':'https://github.com/duckdb/duckdb/releases',
  'release_tag':release.get('tag_name',''),
  'release_published_at':release.get('published_at',''),
  'duckdb_version':version,
  'function_limit':limit,
  'keywords':[{k.lower():v for k,v in r.items()} for r in kw],
  'functions':[{k.lower():v for k,v in r.items()} for r in funcs],
  'settings':[{k.lower():v for k,v in r.items()} for r in settings],
}
value['source_fingerprint']=hashlib.sha256(json.dumps(value, sort_keys=True).encode()).hexdigest()
out.write_text('# GENERATED by scripts/gen-code-duckdb.sh; do not commit.\n'+lit(value)+'\n', encoding='utf-8')
print(f"generated {out}: keywords={len(kw)} functions={len(funcs)} settings={len(settings)} version={version}")
PY
