#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/ml/nist-ai-rmf"
OUT="$ROOT/stdlib/lib/corpus/nist-ai-rmf.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def split_tags(v):
    if isinstance(v,list): vals=v
    else: vals=re.split(r'[,;|]\s*', str(v or ''))
    return [x.strip() for x in vals if x and x.strip()]
def digest_text(v):
    s=str(v or '')
    return {'sha256':hashlib.sha256(s.encode()).hexdigest() if s else '', 'bytes':len(s.encode()), 'lines':len([x for x in s.splitlines() if x.strip()])}
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for name in ['playbook.html','playbook.json','playbook.csv','source-manifest.json']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
data=json.loads((src/'playbook.json').read_text())
rows=[]; funcs={}; cats={}; actors={}; topics={}
for r in data:
    fn=r.get('type','')
    cat=r.get('category','')
    title=r.get('title','')
    sub=title.replace(' ', '-')
    aa=split_tags(r.get('AI Actors'))
    tt=split_tags(r.get('Topic'))
    funcs[fn]=funcs.get(fn,0)+1
    cats[cat]=cats.get(cat,0)+1
    for a in aa: actors[a]=actors.get(a,0)+1
    for t in tt: topics[t]=topics.get(t,0)+1
    rows.append({'function':fn,'category':cat,'subcategory':title,'subcategory_key':sub,'ai_actors':aa,'topics':tt,'description_digest':digest_text(r.get('description')),'about_digest':digest_text(r.get('section_about')),'actions_digest':digest_text(r.get('section_actions')),'doc_digest':digest_text(r.get('section_doc')),'ref_digest':digest_text(r.get('section_ref'))})
def count_rows(m,name): return [{name:k,'count':v} for k,v in sorted(m.items(), key=lambda x:(x[0]))]
obj={'schema':'ml.nist_ai_rmf.playbook.v1','source':'NIST AI RMF Playbook structural metadata','license':'US-PD / NIST public information','summary':{'subcategories':len(rows),'functions':len(funcs),'categories':len(cats),'actor_tags':len(actors),'topic_tags':len(topics)},'policy':'function/category/subcategory/actor/topic taxonomy plus prose hashes only; playbook prose bodies, suggested action text, documentation questions, reference body text, PDF/XLSX bodies, compliance/risk advice, maturity scoring, graph wiring excluded','manifest':manifest,'files':files,'functions':count_rows(funcs,'function'),'categories':count_rows(cats,'category'),'ai_actors':count_rows(actors,'actor'),'topics':count_rows(topics,'topic'),'subcategories':rows}
out.write_text('# GENERATED by scripts/gen-ml-nist-ai-rmf.sh. Do not edit. Gitignored.\n# Source: NIST AI RMF Playbook structural metadata only; prose bodies excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: subcategories={len(rows)} functions={len(funcs)} categories={len(cats)} bytes={out.stat().st_size}')
PY
