#!/usr/bin/env bash
set -euo pipefail
ROOT="${PNIX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
SRC="${TIKA_SOURCE:-$ROOT/ingest/doc/tika/unpacked}"
VERSION="${TIKA_VERSION:-3.3.1}"
JAR="$ROOT/ingest/doc/tika/tika-parsers-standard-package-$VERSION.jar"
OUT="${TIKA_OUT:-$ROOT/stdlib/lib/corpus/tika.generated.px}"
if [ ! -d "$SRC" ]; then
  echo "missing Tika unpacked source: $SRC" >&2
  echo "run: scripts/update-doc-tika.sh" >&2
  exit 1
fi
mkdir -p "$(dirname "$OUT")"
python3 - "$SRC" "$JAR" "$OUT" "$VERSION" <<'PY'
import hashlib, sys
from pathlib import Path
src=Path(sys.argv[1]); jar=Path(sys.argv[2]); out=Path(sys.argv[3]); version=sys.argv[4]

def q(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')+'"'

def lit(v, indent=0):
    sp=' '*indent
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if v is None: return 'null'
    if isinstance(v,str): return q(v)
    if isinstance(v,list):
        if not v: return '[ ]'
        return '[\n'+''.join(' '*(indent+2)+lit(x, indent+2)+'\n' for x in v)+sp+']'
    if isinstance(v,dict):
        if not v: return '{ }'
        lines=['{']
        for k in v:
            lines.append(' '*(indent+2)+k+' = '+lit(v[k], indent+2)+';')
        lines.append(sp+'}')
        return '\n'.join(lines)
    raise TypeError(type(v))
services=[]
svc_dir=src/'META-INF'/'services'
if svc_dir.exists():
    for fp in sorted(svc_dir.iterdir()):
        if not fp.is_file(): continue
        impls=[]
        for line in fp.read_text(encoding='utf-8', errors='replace').splitlines():
            line=line.strip()
            if not line or line.startswith('#'): continue
            impls.append(line)
        services.append({'service':fp.name, 'implementations':impls})
entries=[]
for fp in sorted(src.rglob('*')):
    if fp.is_file():
        rel=str(fp.relative_to(src))
        if rel.startswith('META-INF/'):
            entries.append(rel)
sha=hashlib.sha256(jar.read_bytes()).hexdigest() if jar.exists() else ''
value={
  'schema':'doc.tika.parser_routing.v1',
  'source':'Apache Tika parsers standard package Maven artifact',
  'license':'Apache-2.0',
  'source_url':'https://repo1.maven.org/maven2/org/apache/tika/tika-parsers-standard-package/<version>/',
  'source_sha256':sha,
  'version':version,
  'services':services,
  'artifact_entries':entries,
}
out.write_text('# GENERATED by scripts/gen-doc-tika.sh; do not commit.\n'+lit(value)+'\n', encoding='utf-8')
print(f"generated {out}: services={len(services)} entries={len(entries)} version={version} sha256={sha}")
PY
