#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${KR_PUBLIC_CCTR_OUT:-$ROOT/ingest/korea/kr-public-culture-classification-transport-rnd-catalogs}"
UA="pnix-ingest/1.0 (Korean public culture/classification/transport/RD catalog metadata only; no payload)"
mkdir -p "$OUT/pages"
cat > "$OUT/sources.json" <<'JSON'
[
  {"source_id":"kr_heritage_national_designated_api","domain":"culture_heritage","label":"국가유산청 전국 지정문화재 현황 catalog","license":"Data.go.kr public catalog metadata; heritage rows excluded","urls":["https://www.data.go.kr/data/15034324/openapi.do"],"declared_field_refs":["heritage type field","designation number field","heritage name field","management agency field"],"excluded_payload":"heritage records, descriptions, photos, precise locations"},
  {"source_id":"kr_heritage_spatial_info_api","domain":"culture_heritage","label":"국가유산청 문화재 공간 정보 catalog","license":"Data.go.kr public catalog metadata; spatial payload excluded","urls":["https://www.data.go.kr/data/3070426/openapi.do?recommendDataYn=Y"],"declared_field_refs":["spatial data type marker","coordinate field marker","area/regulation field marker","SHP/XML format marker"],"excluded_payload":"coordinates, shapes, maps, regulation geometry, restoration guidance"},
  {"source_id":"kr_museum_artmuseum_standard_catalog","domain":"culture_facility","label":"전국박물관미술관정보표준데이터 catalog","license":"Data.go.kr public standard catalog metadata; facility rows excluded","urls":["https://www.data.go.kr/data/15017323/standard.do"],"declared_field_refs":["facility name field","museum/art-museum type field","address field","latitude/longitude field","fee/hour field"],"excluded_payload":"facility rows, addresses, precise coordinates, operation advice"},
  {"source_id":"kr_content_industry_ksic_mapping_catalog","domain":"classification","label":"콘텐츠산업분류 한국표준산업분류 연계정보 catalog","license":"Data.go.kr public catalog metadata; classification rows excluded","urls":["https://www.data.go.kr/data/15150114/fileData.do"],"declared_field_refs":["content industry special code field","KSIC code field","large/middle/small class field names"],"excluded_payload":"classification mapping rows, policy analysis"},
  {"source_id":"kr_worknet_occupation_classification_catalog","domain":"classification","label":"워크넷 직업분류 catalog","license":"Data.go.kr public catalog metadata; occupation rows excluded","urls":["https://www.data.go.kr/data/15119096/fileData.do?recommendDataYn=Y"],"declared_field_refs":["KNOW occupation name field","large/middle/small occupation class field names","occupation hierarchy marker"],"excluded_payload":"occupation classification rows, job recommendation guidance"},
  {"source_id":"kr_employment24_jobcode_mapping_catalog","domain":"classification","label":"고용24 직업코드 직업분류코드 매핑정보 catalog","license":"Data.go.kr public catalog metadata; code rows excluded","urls":["https://www.data.go.kr/data/15158873/fileData.do"],"declared_field_refs":["KONET job code field","KECO field","KSCO field","job name field"],"excluded_payload":"job-code mapping rows, employment recommendation guidance"},
  {"source_id":"kr_kats_ks_status_catalog","domain":"standard_classification","label":"한국산업표준(KS) 현황 catalog","license":"Data.go.kr public catalog metadata; KS body excluded","urls":["https://www.data.go.kr/data/15054306/fileData.do"],"declared_field_refs":["KS division field","enact/revision/confirm/abolish status field","year field","standard count field"],"excluded_payload":"KS standard body, normative requirements, compliance advice"},
  {"source_id":"kr_science_technology_standard_classification_catalog","domain":"classification","label":"과학기술표준분류체계 catalog","license":"Data.go.kr public catalog metadata; classification rows excluded","urls":["https://www.data.go.kr/data/15113217/fileData.do?recommendDataYn=Y"],"declared_field_refs":["science technology class code field","large/middle/small class field names","R&D planning/evaluation marker"],"excluded_payload":"classification rows, evaluation decisions"},
  {"source_id":"kr_koroad_monthly_traffic_accident_stats_catalog","domain":"transport_safety","label":"한국도로교통공단 월별 교통사고 통계 catalog","license":"Data.go.kr public catalog metadata; traffic stats rows excluded","urls":["https://www.data.go.kr/data/15070315/fileData.do?recommendDataYn=Y"],"declared_field_refs":["month field","accident count field","fatality field","injury field"],"excluded_payload":"traffic accident statistics rows, safety operation guidance"},
  {"source_id":"kr_koroad_accident_type_stats_catalog","domain":"transport_safety","label":"한국도로교통공단 사고유형별 교통사고 통계 catalog","license":"Data.go.kr public catalog metadata; accident rows excluded","urls":["https://www.data.go.kr/data/15070282/fileData.do"],"declared_field_refs":["accident type field","vehicle/person collision category field","fatality/injury field names"],"excluded_payload":"accident statistics rows, safety/legal guidance"},
  {"source_id":"kr_ts_vehicle_recall_status_catalog","domain":"transport_safety","label":"한국교통안전공단 자동차결함 리콜현황 catalog","license":"Data.go.kr public catalog metadata; recall payload excluded","urls":["https://www.data.go.kr/data/3048950/fileData.do?recommendDataYn=Y"],"declared_field_refs":["manufacturer field","vehicle model field","production period field","recall start field","recall reason field"],"excluded_payload":"recall rows, defect descriptions, repair/safety advice"},
  {"source_id":"kr_molit_aviation_incident_stats_catalog","domain":"transport_safety","label":"국토교통부 연도별 국내 주요 항공사고 현황 catalog","license":"Data.go.kr public catalog metadata; aviation incident rows excluded","urls":["https://www.data.go.kr/data/15049017/fileData.do?recommendDataYn=Y"],"declared_field_refs":["year field","incident type field","damage/fatality field","aircraft category field"],"excluded_payload":"aviation incident rows, investigation reports, safety operation guidance"},
  {"source_id":"kr_data_go_kr_list_api_catalog","domain":"public_data_catalog","label":"공공데이터활용지원센터 목록조회서비스 catalog","license":"Data.go.kr public catalog metadata; listing payload excluded","urls":["https://www.data.go.kr/data/15077093/openapi.do"],"declared_field_refs":["agency name field","public data name field","description field","category field","data type field"],"excluded_payload":"full portal listing payload, organization/person/contact rows"},
  {"source_id":"kr_data_go_kr_core_data_catalog","domain":"public_data_catalog","label":"공공데이터포털 국가중점데이터 catalog","license":"Data.go.kr public catalog metadata; core-data list payload excluded","urls":["https://www.data.go.kr/tcs/eds/selectCoreDataListView.do"],"declared_field_refs":["core data category field","agency field","domain category field","open status marker"],"excluded_payload":"full core-data listing payload, dataset records"},
  {"source_id":"kr_kisti_ntis_project_search_api_catalog","domain":"research_rnd","label":"KISTI 국가R&D 과제검색 서비스 catalog","license":"Data.go.kr public catalog metadata; project rows excluded","urls":["https://www.data.go.kr/data/15077315/openapi.do?recommendDataYn=Y"],"declared_field_refs":["project metadata search marker","project id field","research period field","ministry/program field"],"excluded_payload":"project records, abstracts, participants, budget rows"},
  {"source_id":"kr_kisti_ntis_report_search_api_catalog","domain":"research_rnd","label":"KISTI 국가R&D 연구보고서 검색 서비스 catalog","license":"Data.go.kr public catalog metadata; report rows excluded","urls":["https://www.data.go.kr/data/15102622/openapi.do?recommendDataYn=Y"],"declared_field_refs":["research report metadata search marker","report title field","project relation field","API list marker"],"excluded_payload":"report records, report bodies, PDF text"},
  {"source_id":"kr_nrf_krs_statistics_api_catalog","domain":"research_rnd","label":"한국연구재단 KRS 통계정보서비스 catalog","license":"Data.go.kr public catalog metadata; support statistics rows excluded","urls":["https://www.data.go.kr/data/15073646/openapi.do"],"declared_field_refs":["research support statistics marker","year field","support performance field","language field"],"excluded_payload":"statistics values, project/person support rows"},
  {"source_id":"kr_kiat_ntis_technology_transfer_catalog","domain":"research_rnd","label":"한국산업기술진흥원 NTIS 기술이전 정보 catalog","license":"Data.go.kr public catalog metadata; transfer rows excluded","urls":["https://www.data.go.kr/data/15144947/fileData.do?recommendDataYn=Y"],"declared_field_refs":["performance year field","project year field","program name field","technology transfer contract field","target country field"],"excluded_payload":"technology transfer rows, company names, contract titles"},
  {"source_id":"kr_kiat_ntis_commercialization_catalog","domain":"research_rnd","label":"한국산업기술진흥원 NTIS 사업화 정보 catalog","license":"Data.go.kr public catalog metadata; commercialization rows excluded","urls":["https://www.data.go.kr/data/15144949/fileData.do?recommendDataYn=Y"],"declared_field_refs":["performance year field","project year field","ministry field","commercialization name field","company field"],"excluded_payload":"commercialization rows, company names, product/service details"},
  {"source_id":"kr_msit_science_technology_statistics_analysis_catalog","domain":"research_statistics","label":"과학기술정보통신부 과학기술통계 상세분석 catalog","license":"Data.go.kr public catalog metadata; statistics values excluded","urls":["https://www.data.go.kr/data/15104808/fileData.do?recommendDataYn=Y"],"declared_field_refs":["science technology statistics analysis marker","R&D activity survey marker","national R&D analysis marker"],"excluded_payload":"statistics values, policy report bodies, forecasting/advice"}
]
JSON
python3 - "$OUT" "$UA" <<'PY'
import datetime, hashlib, json, pathlib, subprocess, sys
out=pathlib.Path(sys.argv[1]); ua=sys.argv[2]
sources=json.loads((out/'sources.json').read_text(encoding='utf-8'))
for src in sources:
    d=out/'pages'/src['source_id']; d.mkdir(parents=True, exist_ok=True); results=[]
    for i,u in enumerate(src['urls']):
        path=d/f'{i:02d}.html'; cmd=['curl','-L','--max-time','35','--retry','1','-A',ua,'-sS','-w','\nPNIX_HTTP_STATUS:%{http_code}\n',u]
        try:
            cp=subprocess.run(cmd,text=True,capture_output=True,timeout=45); txt=cp.stdout; status='000'; marker='PNIX_HTTP_STATUS:'
            if marker in txt:
                body,tail=txt.rsplit(marker,1); status=tail.strip().split()[0]; txt=body
            path.write_text(txt,encoding='utf-8',errors='ignore')
            results.append({'url':u,'path':str(path.relative_to(out)),'http_status':status,'curl_exit':cp.returncode,'bytes':path.stat().st_size,'sha256':hashlib.sha256(path.read_bytes()).hexdigest()})
        except Exception as e:
            fail=d/f'{i:02d}.error.txt'; fail.write_text(str(e),encoding='utf-8')
            results.append({'url':u,'path':str(fail.relative_to(out)),'http_status':'000','curl_exit':999,'error':str(e),'bytes':fail.stat().st_size,'sha256':hashlib.sha256(fail.read_bytes()).hexdigest()})
    src['fetch_results']=results
files=[{'path':str(p.relative_to(out)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(out.rglob('*')) if p.is_file() and p.name!='source-manifest.json']
manifest={'schema':'pnix.source_manifest.v1','source_id':'kr-public-culture-classification-transport-rnd-catalogs','retrieved_at_utc':datetime.datetime.now(datetime.UTC).replace(microsecond=0).isoformat().replace('+00:00','Z'),'sources':sources,'files':files,'policy':'Korean culture/classification/transport/RD catalog metadata only; no rows/payloads/reports/precise location/API responses/credentials/guidance/graph wiring.'}
(out/'source-manifest.json').write_text(json.dumps(manifest,indent=2,ensure_ascii=False,sort_keys=True),encoding='utf-8')
print(json.dumps({'ok':True,'sources':len(sources),'files':len(files),'out':str(out)},ensure_ascii=False))
PY
