#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${SLSA_SPEC_SRC:-$ROOT/ingest/supply-chain/slsa-spec}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/slsa-spec.generated.px}"
python3 - "$SRC" "$OUT" <<'PY'
import json,re,sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return json.dumps(v,ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v[k])+';' for k in sorted(v)) + ' }'
    if v is None: return 'null'
source_files=[]; cue_fields=[]; proto_messages=[]; proto_fields=[]; headings=[]; tokens=[]; levels=[]; predicate_types=[]
for rec in receipt['files']:
    source_files.append({'file':rec['source_path'],'sha256':rec['sha256'],'bytes':rec['bytes'],'role':rec['role']})
    text=(src/'raw'/rec['local_file']).read_text(encoding='utf-8',errors='replace')
    if rec['source_path'].endswith('.cue'):
        for m in re.finditer(r'^\s*([A-Za-z_][A-Za-z0-9_@.$-]*)\??:\s*([^\n]+)',text,re.M): cue_fields.append({'file':rec['source_path'],'name':m.group(1),'type_expr':m.group(2).strip()[:120]})
    elif rec['source_path'].endswith('.proto'):
        cur=''
        for line in text.splitlines():
            mm=re.match(r'^message\s+(\w+)\s*\{',line.strip())
            if mm: cur=mm.group(1); proto_messages.append({'name':cur}); continue
            if line.strip()=='}': cur=''; continue
            fm=re.match(r'^(?:optional\s+|repeated\s+)?([A-Za-z0-9_.]+)\s+(\w+)\s*=\s*(\d+)',line.strip())
            if fm and cur: proto_fields.append({'message':cur,'type':fm.group(1),'name':fm.group(2),'number':int(fm.group(3))})
    else:
        for line in text.splitlines():
            hm=re.match(r'^(#{1,6})\s+(.+?)\s*$',line)
            if hm: headings.append({'file':rec['source_path'],'level':len(hm.group(1)),'title':hm.group(2)[:160]})
            for bt in re.findall(r'`([^`]{1,120})`',line):
                if not any(c.isspace() for c in bt): tokens.append({'file':rec['source_path'],'token':bt})
            for lv in re.findall(r'\b(SLSA\s*[0-9]+|Build\s+L[0-9]+|Source\s+L[0-9]+)\b',line): levels.append({'file':rec['source_path'],'level_token':lv})
            for pt in re.findall(r'https://slsa.dev/provenance/[A-Za-z0-9_.:/-]+|https://slsa.dev/[A-Za-z0-9_.:/-]+',line): predicate_types.append({'file':rec['source_path'],'uri':pt})
seen=set(); uniq=[]
for row in tokens:
    k=(row['file'],row['token'])
    if k not in seen: seen.add(k); uniq.append(row)
seen=set(); lv2=[]
for row in levels:
    k=(row['file'],row['level_token'])
    if k not in seen: seen.add(k); lv2.append(row)
seen=set(); pt2=[]
for row in predicate_types:
    k=(row['file'],row['uri'])
    if k not in seen: seen.add(k); pt2.append(row)
obj={'schema':'supply_chain.slsa.specification.v1','source':{'name':'SLSA specification structural metadata','license':'CC-BY-4.0 / repository permissive source','source_urls':['https://github.com/slsa-framework/slsa','https://slsa.dev/spec/'],'receipt':receipt,'generator':'scripts/gen-supply-chain-slsa-spec.sh','scope':'schema and token structure only; prose/examples/real attestations/build logs/secrets/execution/graph wiring excluded'},'summary':{'source_file_count':len(source_files),'cue_field_count':len(cue_fields),'proto_message_count':len(proto_messages),'proto_field_count':len(proto_fields),'heading_count':len(headings),'token_count':len(uniq),'level_token_count':len(lv2),'predicate_uri_count':len(pt2),'prose_body_ingested':False,'examples_ingested':False,'real_attestations_ingested':False,'build_logs_or_secrets_ingested':False,'verification_decisions_ingested':False,'execution_enabled':False,'mirror_graph_wiring':False},'source_files':source_files,'cue_fields':cue_fields[:700],'proto_messages':proto_messages,'proto_fields':proto_fields[:500],'section_headings':headings[:250],'tokens':uniq[:600],'level_tokens':lv2,'predicate_uris':pt2}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/update-supply-chain-slsa-spec.sh && scripts/gen-supply-chain-slsa-spec.sh; do not commit.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: cue={len(cue_fields)} proto_messages={len(proto_messages)} proto_fields={len(proto_fields)} headings={len(headings)} tokens={len(uniq)} bytes={out.stat().st_size}')
PY
