#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/bio/uniprot-field-catalog"
OUT="$ROOT/stdlib/lib/corpus/uniprot-field-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json, pathlib, sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text())
raw=json.loads((src/manifest['files'][0]['path']).read_text())

def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
groups=[]; fields=[]
for g in raw:
    gid=g.get('id') or g.get('groupName','').lower().replace(' ','_')
    groups.append({'id':gid,'name':g.get('groupName',''),'is_database_group':bool(g.get('isDatabaseGroup',False)),'field_count':len(g.get('fields') or [])})
    for f in g.get('fields') or []:
        rec={'group_id':gid,'id':f.get('id',''),'name':f.get('name',''),'label':f.get('label','')}
        if f.get('sortField'): rec['sort_field']=f.get('sortField')
        fields.append(rec)
obj={'schema':'bio.uniprot.field_catalog.v1','source':'UniProtKB result fields configuration metadata','license':'CC-BY-4.0 / UniProt attribution required','policy':'result field/group metadata only; protein records/sequences/annotations/evidence/xref payloads/search results/protein engineering guidance/graph wiring excluded','summary':{'groups':len(groups),'fields':len(fields)},'manifest':manifest,'groups':groups,'fields':fields}
out.write_text('# GENERATED by scripts/gen-bio-uniprot-field-catalog.sh. Do not edit. Gitignored.\n# Source: UniProtKB result field metadata only; protein records/sequences/annotations excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: groups={len(groups)} fields={len(fields)} bytes={out.stat().st_size}')
PY
