#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/transport/fhwa-nbi-catalog"
OUT="$ROOT/stdlib/lib/corpus/fhwa-nbi-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def textify(s): return re.sub(r'\s+',' ',html.unescape(re.sub('<.*?>',' ',s))).strip()
def absurl(h): return urllib.parse.urljoin('https://www.fhwa.dot.gov/bridge/nbi/', h)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for p in [src/'source-manifest.json', src/'ascii.html', src/'format.html']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
ascii_html=(src/'ascii.html').read_text(errors='ignore')
format_html=(src/'format.html').read_text(errors='ignore')
links=[]
for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>', ascii_html, re.I|re.S):
    href=html.unescape(m.group(1)); label=textify(m.group(2))
    if not label: continue
    kind='other'
    year=''
    ym=re.search(r'\b(19\d\d|20\d\d)\b', label)
    if ym and 'Data' in label: kind='annual_data'; year=ym.group(1)
    elif 'Record Format' in label: kind='record_format'
    elif 'Coding Guide' in label or 'Errata' in label or 'Amendment' in label: kind='guide_link'
    elif 'Importing' in label: kind='tooling_note'
    if kind!='other':
        links.append({'kind':kind,'label':label,'year':year,'url':absurl(href)})
format_links=[]
for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>', format_html, re.I|re.S):
    href=html.unescape(m.group(1)); label=textify(m.group(2))
    if label and ('.' in href or 'format' in label.lower()):
        format_links.append({'label':label,'url':absurl(href)})
years=sorted([int(x['year']) for x in links if x['kind']=='annual_data' and x['year']])
obj={'schema':'transport.fhwa_nbi.catalog.v1','source':'FHWA National Bridge Inventory download catalog','license':'US-PD / US federal public information','summary':{'links':len(links),'annual_data_links':sum(1 for x in links if x['kind']=='annual_data'),'year_min':min(years) if years else 0,'year_max':max(years) if years else 0,'format_links':len(format_links)},'policy':'official catalog/link metadata and page hashes only; bridge record payloads, coordinates, condition ratings, structural/safety judgments, coding-guide prose bodies, map/geospatial files, routing/operation decisions, graph wiring excluded','manifest':manifest,'files':files,'nbi_links':links,'format_links':format_links[:80]}
out.write_text('# GENERATED by scripts/gen-transport-fhwa-nbi-catalog.sh. Do not edit. Gitignored.\n# Source: FHWA NBI catalog/link metadata only; bridge payloads excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: links={len(links)} bytes={out.stat().st_size}')
PY
