#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/climate/noaa-ncei-cdo-api-catalog"
OUT="$ROOT/stdlib/lib/corpus/noaa-ncei-cdo-api-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def sig(txt):
    b=txt.encode() if isinstance(txt,str) else txt
    return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
text=(src/'webservices-v2.html').read_text(errors='ignore') if (src/'webservices-v2.html').exists() else ''
mt=re.search(r'<title[^>]*>(.*?)</title>', text, re.I|re.S)
links=[]
for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>', text, re.I|re.S):
    href=html.unescape(m.group(1)); label=clean(re.sub('<.*?>',' ',m.group(2)))[:180]
    if href and not href.startswith('#'):
        low=(href+' '+label).lower()
        if any(k in low for k in ['webservices','api','dataset','datacategories','datatypes','location','station','data']):
            kind='catalog_link'
            if '/api/v2/' in low or 'data' in low: kind='api_ref_payload_excluded'
            links.append({'kind':kind,'label':label,'href':urllib.parse.urljoin('https://www.ncei.noaa.gov/cdo-web/webservices/v2',href)})
endpoints=[]
for name,path in [
    ('datasets','/api/v2/datasets'),
    ('datacategories','/api/v2/datacategories'),
    ('datatypes','/api/v2/datatypes'),
    ('locationcategories','/api/v2/locationcategories'),
    ('locations','/api/v2/locations'),
    ('stations','/api/v2/stations'),
    ('data','/api/v2/data')]:
    endpoints.append({'name':name,'method':'GET','path':path,'requires_token':True,'params':['datasetid','locationid','stationid','startdate','enddate','limit','offset','sortfield','sortorder','units'],'payload_policy':'not called by ingest; response payload and observation values excluded'})
tokens=sorted(set([x.lower() for x in re.findall(r'\b(?:datasets|datacategories|datatypes|locationcategories|locations|stations|data|token|limit|offset|startdate|enddate|datasetid|stationid|locationid)\b',text,re.I)]))
files=[]
for p in [src/'source-manifest.json',src/'webservices-v2.html']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'climate.noaa_ncei_cdo.api_catalog.v1','source':'NOAA NCEI Climate Data Online API catalog metadata','license':'US-PD / US federal public information','summary':{'endpoints':len(endpoints),'links':len(links),'tokens':len(tokens),'files':len(files),'requires_token':True},'policy':'public webservices documentation and endpoint catalog tokens only; tokened API payloads, climate observations, station/location rows, time-series values, forecasts, life-safety decisions, and graph wiring excluded','manifest':manifest,'files':files,'page':{'file':'webservices-v2.html','title':clean(re.sub('<.*?>',' ',mt.group(1)))[:220] if mt else '', 'html_sig':sig(text),'tokens':tokens,'links':links[:120]},'endpoints':endpoints}
out.write_text('# GENERATED by scripts/gen-climate-noaa-ncei-cdo-api-catalog.sh. Do not edit. Gitignored.\n# Source: NOAA NCEI CDO API documentation/catalog only; observations/time-series payloads excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: endpoints={len(endpoints)} links={len(links)} bytes={out.stat().st_size}')
PY
