#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/code/toml-specification"
OUT="$ROOT/stdlib/lib/corpus/toml-specification.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, re, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for p in ['LICENSE','README.md','toml.md','toml.abnf']:
    fp=src/p
    if fp.exists(): files.append({'path':p,'sha256':hashlib.sha256(fp.read_bytes()).hexdigest(),'bytes':fp.stat().st_size})
productions=[]
abnf=src/'toml.abnf'
if abnf.exists():
    for line in abnf.read_text(encoding='utf-8',errors='replace').splitlines():
        if line.strip().startswith(';') or not line.strip(): continue
        m=re.match(r'^([A-Za-z][A-Za-z0-9_-]*)\s*=\s*(.+)$', line)
        if m:
            productions.append({'name':m.group(1),'rule':m.group(2).strip()[:160]})
headings=[]
for fname in ['README.md','toml.md']:
    p=src/fname
    if p.exists():
        for m in re.finditer(r'^(#{1,6})\s+(.+?)\s*$', p.read_text(encoding='utf-8',errors='replace'), re.M):
            headings.append({'file':fname,'level':len(m.group(1)),'title':m.group(2).strip()[:120]})
value_types=[
 {'name':'string'}, {'name':'integer'}, {'name':'float'}, {'name':'boolean'}, {'name':'offset_date_time'}, {'name':'local_date_time'}, {'name':'local_date'}, {'name':'local_time'}, {'name':'array'}, {'name':'inline_table'}, {'name':'table'}, {'name':'array_of_tables'}]
obj={'schema':'config.toml.specification.v1','source':'toml-lang/toml specification','license':'MIT','summary':{'files':len(files),'productions':len(productions),'headings':len(headings),'value_types':len(value_types)},'policy':'ABNF production metadata, headings, and value-type tokens only; prose/examples/logos/config corpora/graph wiring excluded','manifest':manifest,'files':files,'productions':productions,'headings':headings,'value_types':value_types}
out.write_text('# GENERATED by scripts/gen-code-toml-specification.sh. Do not edit. Gitignored.\n# Source: toml-lang/toml ABNF + heading structure.\n# Policy: syntax metadata only; prose/examples/config corpora excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: productions={len(productions)} headings={len(headings)} bytes={out.stat().st_size}')
PY
