#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/license/osi-approved"
OUT="$ROOT/stdlib/lib/corpus/osi-approved.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for name in ['licenses.json','source-manifest.json']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
data=json.loads((src/'licenses.json').read_text())
rows=[]
for r in data:
    links=r.get('_links') or {}
    rows.append({'id':r.get('id',''),'name':r.get('name',''),'spdx_id':r.get('spdx_id',''),'version':r.get('version',''),'approved':bool(r.get('approved',False)),'approval_date':r.get('approval_date',''),'submission_date':r.get('submission_date',''),'keywords':r.get('keywords') or [],'stewards':r.get('stewards') or [],'html_url':(links.get('html') or {}).get('href',''),'api_url':(links.get('self') or {}).get('href','')})
rows=sorted(rows,key=lambda x:(x['spdx_id'] or x['id']))
obj={'schema':'license.osi_approved.v1','source':'OSI Approved License API metadata','license':'OSI public API metadata','summary':{'licenses':len(rows),'approved':sum(1 for r in rows if r['approved']),'with_spdx_id':sum(1 for r in rows if r['spdx_id'])},'policy':'license identifier metadata only; full license text, legal interpretation, compatibility/compliance advice, package-specific judgment, graph wiring excluded; final legal judgment Held','manifest':manifest,'files':files,'licenses':rows}
out.write_text('# GENERATED by scripts/gen-license-osi-approved.sh. Do not edit. Gitignored.\n# Source: OSI Approved License API metadata only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: licenses={len(rows)} bytes={out.stat().st_size}')
PY
