#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/education/nces-ipeds-ccd-catalog"
OUT="$ROOT/stdlib/lib/corpus/nces-ipeds-ccd-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def sig(s):
    t=clean(s)
    return {'bytes':len(t.encode()),'sha256':hashlib.sha256(t.encode()).hexdigest()} if t else {'bytes':0,'sha256':''}
def links_from(path,page_id,base):
    if not path.exists(): return []
    txt=path.read_text(errors='ignore')
    rows=[]
    for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>', txt, re.I|re.S):
        href=html.unescape(m.group(1)); label=clean(re.sub('<.*?>',' ',m.group(2)))[:220]
        if not href or href.startswith('#'): continue
        low=(href+' '+label).lower()
        if any(k in low for k in ['download','data file','flat file','zip','documentation','record layout','access database','custom data','complete data','pubschuniv','pubagency','ipeds']):
            kind='catalog_link'
            if any(k in low for k in ['zip','csv','access database','flat file','data file']): kind='payload_ref'
            if any(k in low for k in ['documentation','record layout','survey form','manual']): kind='documentation_ref'
            rows.append({'page':page_id,'kind':kind,'label':label,'href':urllib.parse.urljoin(base,href)})
    return rows[:160]
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
pages=[]
for name,page_id,base in [
    ('ipeds-use-data.html','ipeds_use_data','https://nces.ed.gov/ipeds/'),
    ('ccd-files.html','ccd_files','https://nces.ed.gov/ccd/'),
    ('ccd-school-universe.html','ccd_school_universe','https://nces.ed.gov/ccd/'),
    ('ccd-agency-universe.html','ccd_agency_universe','https://nces.ed.gov/ccd/')]:
    p=src/name
    if p.exists():
        txt=p.read_text(errors='ignore')
        mt=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
        pages.append({'page':page_id,'file':name,'title':clean(re.sub('<.*?>',' ',mt.group(1)))[:220] if mt else '', 'html_sig':sig(txt), 'links':links_from(p,page_id,base)})
files=[]
for p in [src/'source-manifest.json',src/'ipeds-use-data.html',src/'ccd-files.html',src/'ccd-school-universe.html',src/'ccd-agency-universe.html']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'education.nces_ipeds_ccd.catalog.v1','source':'NCES IPEDS/CCD catalog/download-page metadata','license':'US-PD / US federal public information','summary':{'pages':len(pages),'links':sum(len(x['links']) for x in pages),'files':len(files)},'policy':'official NCES catalog/download-page metadata only; institution/school/agency/student/staff/finance/address/coordinate/statistical payload rows, education advice/ranking/profiling, prose bodies, and graph wiring excluded','manifest':manifest,'files':files,'pages':pages}
out.write_text('# GENERATED by scripts/gen-education-nces-ipeds-ccd-catalog.sh. Do not edit. Gitignored.\n# Source: NCES IPEDS/CCD catalog metadata only; data payload rows excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} links={obj["summary"]["links"]} bytes={out.stat().st_size}')
PY
