#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/catalog/remaining-allowlist-public-catalogs"
OUT="$ROOT/stdlib/lib/corpus/remaining-allowlist-public-catalogs.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib,sys,json,hashlib,re,html,urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(re.sub('<.*?>',' ',str(s or '')))).strip()
def page_meta(base, rel):
    p=base/rel
    raw=p.read_bytes() if p.exists() else b''
    txt=raw.decode('utf-8','ignore')
    mt=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
    title=clean(mt.group(1))[:220] if mt else ''
    links=[]
    for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>',txt,re.I|re.S):
        href=html.unescape(m.group(1)); label=clean(m.group(2))[:120]
        if href and not href.startswith('#'):
            low=(href+' '+label).lower()
            if any(k in low for k in ['api','data','dataset','download','open','search','catalog','통계','자료','데이터','검색','목록','종','품종','리콜','사고']):
                links.append({'label':label,'href':href})
                if len(links)>=60: break
    json_keys=[]
    if p.suffix=='.json':
        try:
            j=json.loads(txt)
            if isinstance(j,dict): json_keys=sorted(map(str,j.keys()))[:80]
            elif isinstance(j,list): json_keys=['list',f'len={len(j)}']
        except Exception: pass
    return {'path':rel,'bytes':len(raw),'sha256':hashlib.sha256(raw).hexdigest(),'title':title,'links':links,'json_keys':json_keys}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {'sources':[]}
records=[]
for s in manifest.get('sources',[]):
    pages=[]
    for fr in s.get('fetch_results',[]):
        meta=page_meta(src,fr.get('path',''))
        meta.update({'url':fr.get('url',''),'http_status':fr.get('http_status',''),'curl_exit':fr.get('curl_exit',0)})
        pages.append(meta)
    records.append({'source_id':s.get('source_id',''),'label':s.get('label',''),'license':s.get('license',''),'urls':s.get('urls',[]),'pages':pages,'ok_pages':sum(1 for p in pages if str(p.get('http_status','')).startswith('2'))})
files=[]
for p in sorted(src.rglob('*')):
    if p.is_file(): files.append({'path':str(p.relative_to(src)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
obj={'schema':'catalog.remaining_allowlist_public_catalogs.v1','source':'Remaining allow-list public catalog/page/API metadata batch','license':'mixed official public catalog metadata only; payload licenses excluded','summary':{'sources':len(records),'ok_sources':sum(1 for r in records if r['ok_pages']>0),'pages':sum(len(r['pages']) for r in records),'files':len(files)},'policy':'Source-level public catalog/page/API metadata only: source_id, URLs, HTTP status, content hash, page title, selected links and JSON top-level keys. Excludes dataset/API payload records, prose bodies/examples, PDF/attachment bodies, personal/sensitive records, credentials, legal/medical/safety/operational advice, and graph/mirror wiring.','manifest':{'retrieved_at_utc':manifest.get('retrieved_at_utc',''),'policy':manifest.get('policy','')},'sources':records,'files':files[:300]}
out.write_text('# GENERATED by scripts/gen-catalog-remaining-allowlist-public-catalogs.sh. Do not edit. Gitignored.\n# Source: remaining allow-list official catalog metadata only; payloads/prose/credentials/graph wiring excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: sources={len(records)} pages={sum(len(r["pages"]) for r in records)} bytes={out.stat().st_size}')
PY
