#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${CENSUS_NAICS_SRC:-$ROOT/ingest/procurement/census-naics}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/census-naics.generated.px}"
python3 - "$SRC" "$OUT" <<'PY'
import json, re, sys, zipfile, xml.etree.ElementTree as ET
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2])
receipt=json.loads((src/'source-receipt.json').read_text())

def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,(int,float)): return repr(v)
    if isinstance(v,str): return json.dumps(v, ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))

def col_name(n):
    s=''
    while n:
        n, r = divmod(n-1, 26)
        s=chr(65+r)+s
    return s

def parent(code):
    if len(code)==6: return code[:5]
    if len(code)==5: return code[:4]
    if len(code)==4: return code[:3]
    if len(code)==3: return code[:2]
    return ''

xlsx=src/'raw/naics-structure.xlsx'
with zipfile.ZipFile(xlsx) as z:
    shared=[]
    if 'xl/sharedStrings.xml' in z.namelist():
        root=ET.fromstring(z.read('xl/sharedStrings.xml'))
        ns={'a':'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
        for si in root.findall('a:si', ns):
            shared.append(''.join(t.text or '' for t in si.findall('.//a:t', ns)))
    sheet_name=next(n for n in z.namelist() if n.startswith('xl/worksheets/sheet') and n.endswith('.xml'))
    root=ET.fromstring(z.read(sheet_name))
    ns={'a':'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
    rows=[]
    for row in root.findall('.//a:row', ns):
        vals={}
        for c in row.findall('a:c', ns):
            ref=c.attrib.get('r','')
            col=re.match(r'[A-Z]+', ref).group(0) if ref else ''
            v=c.find('a:v', ns)
            val='' if v is None else (v.text or '')
            if c.attrib.get('t')=='s' and val:
                val=shared[int(val)]
            vals[col]=val.strip()
        if vals: rows.append(vals)
# 2022_NAICS_Structure.xlsx source schema:
# row 3: A=Change Indicator, B=2022 NAICS Code, C=2022 NAICS Title
# rows 4..: A=change indicator, B=code, C=title.  Keep this source schema directly
# instead of guessing headers from prose cells.
header_idx=2
code_col='B'
title_col='C'
records=[]
for r in rows[header_idx+1:]:
    code=(r.get(code_col,'') or '').strip()
    title=(r.get(title_col,'') or '').strip()
    code=re.sub(r'\D','',code)
    if not re.fullmatch(r'\d{2,6}', code) or not title:
        continue
    records.append({'code':code,'title':title,'level':len(code),'parent_code':parent(code)})
seed={'schema':'procurement.census_naics.v1','source':{'name':'U.S. Census NAICS Structure','license':'US-GOV-PD','year':receipt.get('year'),'retrieved_at':receipt.get('retrieved_at')},'summary':{'record_count':len(records),'description_prose_ingested':False,'examples_ingested':False,'economic_statistics_ingested':False,'business_records_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'records':records}
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('# GENERATED by scripts/gen-procurement-census-naics.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: records={len(records)}')
PY
