#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/doc/grobid-catalog"
OUT="$ROOT/stdlib/lib/corpus/grobid-catalog.generated.px"
LIMIT="${GROBID_CLASS_LIMIT:-800}"
python3 - "$SRC" "$OUT" "$LIMIT" <<'PY'
import pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); limit=int(sys.argv[3])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for name in ['tree.json','LICENSE','source-manifest.json']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
tree=json.loads((src/'tree.json').read_text())
classes=[]; modules={}
for row in tree.get('tree',[]):
    path=row.get('path','')
    if row.get('type')!='blob' or not path.endswith('.java') or '/src/main/java/' not in path: continue
    if '/src/test/' in path or '/src/examples/' in path: continue
    module=path.split('/')[0]
    rel=path.split('/src/main/java/',1)[1]
    pkg='.'.join(rel.split('/')[:-1])
    cls=rel.split('/')[-1][:-5]
    modules[module]=modules.get(module,0)+1
    classes.append({'module':module,'package':pkg,'class':cls,'path':path})
classes=sorted(classes,key=lambda x:(x['module'],x['package'],x['class']))
module_rows=[{'name':k,'class_count':v} for k,v in sorted(modules.items())]
obj={'schema':'doc.grobid.catalog.v1','source':'GROBID repository tree class catalog','license':'Apache-2.0','summary':{'modules':len(module_rows),'classes':min(len(classes),limit),'classes_total_seen':len(classes),'limit':limit},'policy':'Git tree class/package path metadata only; source bodies, docs prose, examples, tests, model/data files, parsed scholarly text, runtime extraction, graph wiring excluded','manifest':manifest,'files':files,'modules':module_rows,'classes':classes[:limit]}
out.write_text('# GENERATED by scripts/gen-doc-grobid-catalog.sh. Do not edit. Gitignored.\n# Source: GROBID Git tree class/package paths only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: modules={len(module_rows)} classes={min(len(classes),limit)}/{len(classes)} bytes={out.stat().st_size}')
PY
