#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/accounting/treasury-fiscaldata-api"
OUT="$ROOT/stdlib/lib/corpus/treasury-fiscaldata-api.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json, sys, pathlib, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('\n',' ').replace('\r','')+'"'
endpoints=[]
for line in (src/'endpoints.txt').read_text().splitlines():
    ep,url,fn=line.split('\t')
    p=src/fn
    d=json.loads(p.read_text())
    meta=d.get('meta',{})
    labels=meta.get('labels',{})
    types=meta.get('dataTypes',{})
    fmts=meta.get('dataFormats',{})
    fields=[]
    for name,label in labels.items():
        fields.append({'name':name,'label':label,'data_type':types.get(name,''),'data_format':fmts.get(name,'')})
    endpoints.append({'endpoint':ep,'url':url,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'field_count':len(fields),'fields':fields})
lines=['''# GENERATED by scripts/gen-accounting-treasury-fiscaldata-api.sh. Do not edit. Gitignored.
# Source: U.S. Treasury Fiscal Data API v2 metadata responses.
# Policy: meta field structure only; data rows/time-series/amounts discarded.
{ schema = "accounting.treasury_fiscaldata_api_metadata.v1";
  source = "U.S. Treasury Fiscal Data API endpoint metadata";
  license = "US-PD";
''']
lines.append(f'  summary = {{ endpoints = {len(endpoints)}; fields = {sum(e["field_count"] for e in endpoints)}; }};\n')
lines.append('  endpoints = [\n')
for e in endpoints:
    lines.append('    { endpoint = '+esc(e['endpoint'])+'; url = '+esc(e['url'])+'; sha256 = '+esc(e['sha256'])+'; field_count = '+str(e['field_count'])+'; fields = [ ')
    lines.append(' '.join('{ name = '+esc(f['name'])+'; label = '+esc(f['label'])+'; data_type = '+esc(f['data_type'])+'; data_format = '+esc(f['data_format'])+'; }' for f in e['fields']))
    lines.append(' ]; }\n')
lines.append('  ];\n}\n')
out.write_text(''.join(lines), encoding='utf-8')
print(f'generated {out}: endpoints={len(endpoints)} fields={sum(e["field_count"] for e in endpoints)} bytes={out.stat().st_size}')
PY
