#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${INTOTO_ATTESTATION_SRC:-$ROOT/ingest/supply-chain/intoto-attestation}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/intoto-attestation.generated.px}"
python3 - "$SRC" "$OUT" <<'PY'
import json,re,sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return json.dumps(v,ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v[k])+';' for k in sorted(v)) + ' }'
    if v is None: return 'null'
source_files=[]; proto_messages=[]; proto_enums=[]; proto_fields=[]; headings=[]; tokens=[]; predicate_uris=[]
for rec in receipt['files']:
    source_files.append({'file':rec['source_path'],'sha256':rec['sha256'],'bytes':rec['bytes'],'role':rec['role']})
    text=(src/'raw'/rec['local_file']).read_text(encoding='utf-8',errors='replace')
    if rec['source_path'].endswith('.proto'):
        cur=''; cur_enum=''
        for line in text.splitlines():
            s=line.strip()
            mm=re.match(r'message\s+(\w+)\s*\{',s)
            if mm: cur=mm.group(1); proto_messages.append({'file':rec['source_path'],'name':cur}); continue
            em=re.match(r'enum\s+(\w+)\s*\{',s)
            if em: cur_enum=em.group(1); proto_enums.append({'file':rec['source_path'],'name':cur_enum}); continue
            if s=='}': cur=''; cur_enum=''; continue
            fm=re.match(r'(?:optional\s+|repeated\s+)?([A-Za-z0-9_.]+)\s+(\w+)\s*=\s*(\d+)',s)
            if fm and cur: proto_fields.append({'file':rec['source_path'],'message':cur,'type':fm.group(1),'name':fm.group(2),'number':int(fm.group(3))})
    else:
        for line in text.splitlines():
            hm=re.match(r'^(#{1,6})\s+(.+?)\s*$',line)
            if hm: headings.append({'file':rec['source_path'],'level':len(hm.group(1)),'title':hm.group(2)[:160]})
            for bt in re.findall(r'`([^`]{1,120})`',line):
                if not any(c.isspace() for c in bt): tokens.append({'file':rec['source_path'],'token':bt})
            for uri in re.findall(r'https://(?:in-toto\.io|slsa\.dev)/[A-Za-z0-9_.:/?=&%#-]+',line): predicate_uris.append({'file':rec['source_path'],'uri':uri})
def uniq(rows, keys):
    seen=set(); out=[]
    for r in rows:
        k=tuple(r[x] for x in keys)
        if k not in seen: seen.add(k); out.append(r)
    return out
tokens=uniq(tokens,('file','token')); predicate_uris=uniq(predicate_uris,('file','uri'))
obj={'schema':'supply_chain.intoto.attestation.v1','source':{'name':'in-toto Attestation official schema metadata','license':'Apache-2.0','source_urls':['https://github.com/in-toto/attestation','https://github.com/in-toto/attestation/tree/'+receipt.get('ref','')],'receipt':receipt,'generator':'scripts/gen-supply-chain-intoto-attestation.sh','scope':'protobuf/spec structural identifiers only; prose/examples/real attestations/signatures/keys/logs/secrets/execution/graph wiring excluded'},'summary':{'source_file_count':len(source_files),'proto_message_count':len(proto_messages),'proto_enum_count':len(proto_enums),'proto_field_count':len(proto_fields),'heading_count':len(headings),'token_count':len(tokens),'predicate_uri_count':len(predicate_uris),'prose_body_ingested':False,'examples_ingested':False,'real_attestations_ingested':False,'signatures_or_keys_ingested':False,'build_logs_or_secrets_ingested':False,'verification_decisions_ingested':False,'execution_enabled':False,'mirror_graph_wiring':False},'source_files':source_files,'proto_messages':proto_messages,'proto_enums':proto_enums,'proto_fields':proto_fields[:800],'section_headings':headings[:300],'tokens':tokens[:800],'predicate_uris':predicate_uris[:300]}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/update-supply-chain-intoto-attestation.sh && scripts/gen-supply-chain-intoto-attestation.sh; do not commit.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: messages={len(proto_messages)} enums={len(proto_enums)} fields={len(proto_fields)} headings={len(headings)} tokens={len(tokens)} bytes={out.stat().st_size}')
PY
