#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${USPTO_DSC_SRC:-$ROOT/ingest/trademark/uspto-design-search-code}"
OUT="${USPTO_DSC_OUT:-$ROOT/stdlib/lib/corpus/uspto-design-search-code.generated.px}"
python3 - <<'PY' "$SRC" "$OUT"
import json,os,pathlib,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
data=json.loads((src/'raw/design-search-codes.json').read_text())
cats=[]; divs=[]; subs=[]; equiv=[]; equiv_cap=int(os.environ.get('USPTO_DSC_EQUIV_CAP','1000'))
for h in data.get('hits',[]):
    c=h.get('_source',{})
    cid=c.get('id'); cats.append({'code':cid,'name':c.get('name')})
    for d in c.get('division') or []:
        did=d.get('id'); dcode=f'{cid}.{did}' if cid and did else did
        divs.append({'code':dcode,'category_code':cid,'division_id':did,'name':d.get('name')})
        for s in d.get('subdivision') or []:
            sid=s.get('id'); scode=f'{cid}.{did}.{sid}' if cid and did and sid else sid
            subs.append({'code':scode,'category_code':cid,'division_code':dcode,'section_id':sid,'name':s.get('name')})
            if equiv_cap == 0 or len(equiv) < equiv_cap:
                for e in (s.get('equivalence') or [])[:80]:
                    if equiv_cap != 0 and len(equiv) >= equiv_cap: break
                    equiv.append({'code':scode,'label':e})
def esc(s): s='' if s is None else str(s); return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'
def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return esc(v)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))
seed={'schema':'trademark.uspto_design_search_code.v1','source':{'name':'USPTO Trademark Design Search Code Manual taxonomy','license':'US-PD / USPTO public taxonomy metadata','retrieved_at_unix':receipt.get('retrieved_at_unix')},'summary':{'category_count':len(cats),'division_count':len(divs),'subdivision_count':len(subs),'equivalence_count':len(equiv),'equivalence_cap':equiv_cap,'guideline_prose_ingested':False,'description_prose_ingested':False,'sample_images_ingested':False,'trademark_records_ingested':False,'legal_judgment_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'categories':sorted(cats,key=lambda x:x['code'] or ''),'divisions':sorted(divs,key=lambda x:x['code'] or ''),'subdivisions':sorted(subs,key=lambda x:x['code'] or ''),'equivalence_labels':sorted(equiv,key=lambda x:(x['code'],x['label']))}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/gen-trademark-uspto-design-search-code.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: categories={len(cats)}, divisions={len(divs)}, subdivisions={len(subs)}, equivalence={len(equiv)}')
PY
