#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${WIKIDATA_SRC:-$ROOT/ingest/authority/wikidata-qp-id-manifest}"
OUT="${WIKIDATA_OUT:-$ROOT/stdlib/lib/corpus/wikidata-qp-id-manifest.generated.px}"
LANG="${WIKIDATA_LANG:-en}"
python3 - <<'PY' "$SRC" "$OUT" "$LANG"
import json, pathlib, sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); lang=sys.argv[3]
site=json.loads((src/'raw/siteinfo.json').read_text())
ents=json.loads((src/'raw/entities.json').read_text())
receipt=json.loads((src/'source-receipt.json').read_text())

def esc(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')+'"'
def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,(int,float)): return str(v)
    if isinstance(v,str): return esc(v)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))
q=site.get('query',{})
g=q.get('general',{})
siteinfo={k:g.get(k) for k in ['sitename','generator','lang','server','scriptpath','articlepath'] if g.get(k) is not None}
ns_rows=[]
for k,v in sorted((q.get('namespaces') or {}).items(), key=lambda kv:int(kv[0])):
    ns_rows.append({
      'id': int(k),
      'name': v.get('name',''),
      'canonical': v.get('canonical'),
      'case': v.get('case'),
      'content': bool(v.get('content', False)),
      'subpages': bool(v.get('subpages', False)),
    })
alias_rows=[]
for a in q.get('namespacealiases') or []:
    alias_rows.append({'id': a.get('id'), 'alias': a.get('alias')})
entity_rows=[]
raw_entities=ents.get('entities') or {}
for eid in sorted(raw_entities):
    e=raw_entities[eid]
    labels=e.get('labels') or {}
    lab=labels.get(lang) or labels.get('en') or {}
    entity_rows.append({
      'id': eid,
      'entity_kind': e.get('type') or ('property' if eid.startswith('P') else 'item'),
      'pageid': e.get('pageid'),
      'ns': e.get('ns'),
      'title': e.get('title'),
      'lastrevid': e.get('lastrevid'),
      'modified': e.get('modified'),
      'label': lab.get('value'),
      'label_lang': lab.get('language') or lang,
      'claims_ingested': False,
      'sitelinks_ingested': False,
      'descriptions_ingested': False,
      'aliases_ingested': False,
    })
seed={
  'schema':'authority.wikidata.qp_id_manifest.v1',
  'source':{
    'name':'Wikidata Q/P id manifest',
    'license':'CC0-1.0',
    'api':'https://www.wikidata.org/w/api.php',
    'retrieved_at_unix':receipt.get('retrieved_at_unix'),
    'language':lang,
  },
  'summary':{
    'entity_count':len(entity_rows),
    'namespace_count':len(ns_rows),
    'namespace_alias_count':len(alias_rows),
    'claims_ingested':False,
    'sitelinks_ingested':False,
    'descriptions_ingested':False,
    'aliases_ingested':False,
    'wikipedia_text_ingested':False,
    'full_dump_ingested':False,
    'sparql_result_ingested':False,
    'mirror_graph_wiring':False,
  },
  'source_receipt':receipt,
  'siteinfo':siteinfo,
  'namespaces':ns_rows,
  'namespace_aliases':alias_rows,
  'entities':entity_rows,
}
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('# GENERATED by scripts/gen-authority-wikidata-qp-id-manifest.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: entities={len(entity_rows)} namespaces={len(ns_rows)} aliases={len(alias_rows)}')
PY
