#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${NWS_ALERTS_API_SRC:-$ROOT/ingest/science/nws-alerts-api}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/nws-alerts-api.generated.px}"
python3 - "$SRC" "$OUT" <<'PY'
import json, sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2])
receipt=json.loads((src/'source-receipt.json').read_text())
openapi=json.loads((src/'raw/openapi.json').read_text())
types_doc=json.loads((src/'raw/alert-types.json').read_text())

def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,(int,float)): return repr(v)
    if isinstance(v,str): return json.dumps(v, ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))
paths=[]
for path, node in sorted((openapi.get('paths') or {}).items()):
    for method, op in sorted((node or {}).items()):
        if method.lower() not in ['get','post','put','delete','patch','head','options']:
            continue
        params=[]
        for p in op.get('parameters') or []:
            params.append({'name':p.get('name',''), 'location':p.get('in',''), 'required':bool(p.get('required',False))})
        responses=sorted((op.get('responses') or {}).keys())
        paths.append({'path':path, 'method':method.upper(), 'operation_id':op.get('operationId',''), 'tags':op.get('tags') or [], 'parameters':params, 'responses':responses})
schemas=[]
for name, schema in sorted(((openapi.get('components') or {}).get('schemas') or {}).items()):
    props=[]
    for pn,pv in sorted((schema.get('properties') or {}).items()):
        item={'name':pn}
        if isinstance(pv,dict):
            if 'type' in pv: item['type']=pv['type']
            if '$ref' in pv: item['ref']=pv['$ref'].rsplit('/',1)[-1]
            if 'enum' in pv: item['enum_count']=len(pv.get('enum') or [])
        props.append(item)
    schemas.append({'name':name, 'type':schema.get('type',''), 'required':schema.get('required') or [], 'properties':props})
alert_types=[]
if isinstance(types_doc,dict):
    raw_types=types_doc.get('eventTypes') or types_doc.get('@graph') or []
    if isinstance(raw_types,list):
        for x in raw_types:
            if isinstance(x,str): alert_types.append({'label':x})
            elif isinstance(x,dict): alert_types.append({'label':x.get('event','') or x.get('title','') or x.get('@id','')})
seed={'schema':'weather.nws_alerts_api.v1','source':{'name':'National Weather Service API OpenAPI / alert type metadata','license':'US-GOV-PD','retrieved_at':receipt.get('retrieved_at')},'summary':{'path_count':len(paths),'schema_count':len(schemas),'alert_type_count':len(alert_types),'live_alerts_ingested':False,'cap_payloads_ingested':False,'forecast_values_ingested':False,'zone_geometry_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'openapi':{'version':openapi.get('openapi',''),'title':(openapi.get('info') or {}).get('title',''),'api_version':(openapi.get('info') or {}).get('version','')},'paths':paths,'schemas':schemas,'alert_types':alert_types}
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('# GENERATED by scripts/gen-science-nws-alerts-api.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: paths={len(paths)}, schemas={len(schemas)}, alert_types={len(alert_types)}')
PY
