#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/finance/cfpb-complaint-taxonomy/aggregations.json"
OUT="$ROOT/stdlib/lib/corpus/cfpb-complaint-taxonomy.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json, sys, pathlib, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); d=json.loads(src.read_text())

def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('\n',' ').replace('\r','')+'"'

def buckets(name):
    agg=d.get('aggregations',{}).get(name,{})
    inner=agg.get(name) or next((v for v in agg.values() if isinstance(v,dict) and 'buckets' in v), {'buckets':[]})
    return inner.get('buckets',[]), inner.get('sum_other_doc_count',0)

def simple_rows(name):
    bs, other=buckets(name)
    return [{'key':str(b.get('key_as_string', b.get('key',''))), 'count':b.get('doc_count',0)} for b in bs], other
products=[]
for b in buckets('product')[0]:
    subs=b.get('sub_product.raw',{}).get('buckets',[])
    products.append({'product':b.get('key',''), 'count':b.get('doc_count',0), 'sub_products':[{'key':s.get('key',''), 'count':s.get('doc_count',0)} for s in subs]})
issues=[]
for b in buckets('issue')[0]:
    subs=b.get('sub_issue.raw',{}).get('buckets',[])
    issues.append({'issue':b.get('key',''), 'count':b.get('doc_count',0), 'sub_issues':[{'key':s.get('key',''), 'count':s.get('doc_count',0)} for s in subs]})
enums=[]
for name in ['timely','company_response','submitted_via','tags','has_narrative']:
    rows, other=simple_rows(name)
    enums.append({'field':name,'sum_other_doc_count':other,'values':rows})
lines=['''# GENERATED by scripts/gen-finance-cfpb-complaint-taxonomy.sh. Do not edit. Gitignored.
# Source: CFPB Consumer Complaint Database API aggregations.
# Policy: taxonomy buckets only; complaint rows, narratives, companies, states/ZIPs, ranking/profiling excluded.
{ schema = "finance.cfpb_complaint_taxonomy.v1";
  source = "CFPB Consumer Complaint Database API aggregations";
  license = "US-PD";
''']
lines.append(f'  source_digest_sha256 = {esc(hashlib.sha256(src.read_bytes()).hexdigest())};\n')
lines.append(f'  summary = {{ total_hits = {d.get("hits",{}).get("total",{}).get("value",0)}; products = {len(products)}; issues = {len(issues)}; enum_fields = {len(enums)}; }};\n')
lines.append('  products = [\n')
for p in products:
    lines.append('    { product = '+esc(p['product'])+'; count = '+str(p['count'])+'; sub_products = [ ' + ' '.join('{ key = '+esc(s['key'])+'; count = '+str(s['count'])+'; }' for s in p['sub_products']) + ' ]; }\n')
lines.append('  ];\n  issues = [\n')
for p in issues:
    lines.append('    { issue = '+esc(p['issue'])+'; count = '+str(p['count'])+'; sub_issues = [ ' + ' '.join('{ key = '+esc(s['key'])+'; count = '+str(s['count'])+'; }' for s in p['sub_issues']) + ' ]; }\n')
lines.append('  ];\n  enum_fields = [\n')
for e in enums:
    lines.append('    { field = '+esc(e['field'])+'; sum_other_doc_count = '+str(e['sum_other_doc_count'])+'; values = [ ' + ' '.join('{ key = '+esc(v['key'])+'; count = '+str(v['count'])+'; }' for v in e['values']) + ' ]; }\n')
lines.append('  ];\n}\n')
out.write_text(''.join(lines), encoding='utf-8')
print(f'generated {out}: products={len(products)} issues={len(issues)} enums={len(enums)} bytes={out.stat().st_size}')
PY
