#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/finance/fdic-bankfind-api"
OUT="$ROOT/stdlib/lib/corpus/fdic-bankfind-api.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def typ(v):
    if isinstance(v,bool): return 'bool'
    if isinstance(v,int): return 'int'
    if isinstance(v,float): return 'float'
    if isinstance(v,str): return 'string'
    if isinstance(v,list): return 'list'
    if isinstance(v,dict): return 'object'
    if v is None: return 'null'
    return type(v).__name__
def field_schema(obj):
    data=obj.get('data') if isinstance(obj,dict) else []
    rec=data[0] if isinstance(data,list) and data else {}
    if isinstance(rec,dict) and 'data' in rec and isinstance(rec['data'],dict): rec=rec['data']
    if not isinstance(rec,dict): rec={}
    return [{'field':k,'type':typ(v)} for k,v in sorted(rec.items())]
def meta_schema(obj):
    meta=obj.get('meta',{}) if isinstance(obj,dict) else {}
    return [{'field':k,'type':typ(v)} for k,v in sorted(meta.items())]
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
endpoints=[]
for name,file,url in [
    ('institutions','institutions-sample.json','https://banks.data.fdic.gov/api/institutions'),
    ('locations','locations-sample.json','https://banks.data.fdic.gov/api/locations'),
    ('summary','summary-sample.json','https://banks.data.fdic.gov/api/summary')]:
    obj=json.loads((src/file).read_text()) if (src/file).exists() else {}
    endpoints.append({'name':name,'method':'GET','url':url,'params':['filters','fields','sort_by','sort_order','limit','offset','format','download'],'response_fields':field_schema(obj),'meta_fields':meta_schema(obj)})
files=[]
for p in [src/'source-manifest.json',src/'docs.html',src/'institutions-sample.json',src/'locations-sample.json',src/'summary-sample.json']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
docs_sig={'bytes':0,'sha256':''}
if (src/'docs.html').exists():
    txt=(src/'docs.html').read_text(errors='ignore'); docs_sig={'bytes':len(txt.encode()),'sha256':hashlib.sha256(txt.encode()).hexdigest()}
obj={'schema':'finance.fdic_bankfind.api_schema.v1','source':'FDIC BankFind Suite API endpoint/schema metadata','license':'US-PD / US federal public information','summary':{'endpoints':len(endpoints),'field_rows':sum(len(e['response_fields']) for e in endpoints),'files':len(files)},'policy':'endpoint catalog and response field/type inventory only; institution payload values, addresses, coordinates, financial amounts, supervisory/risk judgments, legal/financial advice, and graph wiring excluded','manifest':manifest,'files':files,'docs_html_sig':docs_sig,'endpoints':endpoints}
out.write_text('# GENERATED by scripts/gen-finance-fdic-bankfind-api.sh. Do not edit. Gitignored.\n# Source: FDIC BankFind API schema metadata only; institution payload values/addresses/amounts/advice excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: endpoints={len(endpoints)} fields={obj["summary"]["field_rows"]} bytes={out.stat().st_size}')
PY
