#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/ui/uswds-catalog"
OUT="$ROOT/stdlib/lib/corpus/uswds-catalog.generated.px"
LIMIT="${USWDS_COMPONENT_LIMIT:-260}"
python3 - "$SRC" "$OUT" "$LIMIT" <<'PY'
import pathlib, sys, json, hashlib, re
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); limit=int(sys.argv[3])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
tree=json.loads((src/'tree.json').read_text())
release={}
if (src/'release.json').exists(): release=json.loads((src/'release.json').read_text())
files=[]
for name in ['tree.json','release.json','LICENSE.md']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
components={}; content_variants=[]; style_entries=[]; token_files=[]
for row in tree.get('tree',[]):
    path=row.get('path','')
    if row.get('type')!='blob': continue
    if any(bad in path for bad in ['/src/test/','/test/','/img/','/fonts/','/assets/','/dist/','/examples/','/docs/']): continue
    m=re.match(r'^packages/(usa-[^/]+)/', path)
    if m:
        comp=m.group(1); components.setdefault(comp, {'component':comp,'has_twig':False,'has_styles':False,'has_js':False,'content_variants':0})
        if path.endswith('.twig'): components[comp]['has_twig']=True
        if '/styles/' in path or path.endswith('/_index.scss'): components[comp]['has_styles']=True
        if path.endswith('index.js') or path.endswith('.component.js'): components[comp]['has_js']=True
        if '/src/content/' in path and path.endswith('.json'):
            content_variants.append({'component':comp,'file':path.rsplit('/',1)[-1].replace('.json',''),'path':path}); components[comp]['content_variants']+=1
    if path.startswith('packages/uswds-core/src/styles/tokens/') and path.endswith(('.scss','.json')):
        parts=path.split('/'); family=parts[5] if len(parts)>6 else ''
        token_files.append({'family':family,'path':path,'name':path.rsplit('/',1)[-1]})
    if path.startswith('packages/uswds-core/src/styles/') and path.endswith('.scss') and any(seg in path for seg in ['/settings/','/variables/','/mixins/utilities/']):
        style_entries.append({'kind':'scss_index','path':path,'name':path.rsplit('/',1)[-1].replace('.scss','').lstrip('_')})
component_rows=list(sorted(components.values(), key=lambda x:x['component']))[:limit]
obj={'schema':'ui.uswds.catalog.v1','source':'U.S. Web Design System release tree catalog','license':'US-PD/CC0-1.0 with third-party asset exclusions','summary':{'components':len(component_rows),'components_total_seen':len(components),'content_variants':len(content_variants),'token_files':len(token_files),'style_entries':len(style_entries),'component_limit':limit},'policy':'component/token path metadata only; fonts/icons/images/normalize/source bodies/docs prose/examples/runtime JS/trademarks/graph wiring excluded','manifest':manifest,'release':{'tag':release.get('tag_name',''),'name':release.get('name','')},'files':files,'components':component_rows,'content_variants':content_variants[:600],'token_files':token_files[:600],'style_entries':style_entries[:600]}
out.write_text('# GENERATED by scripts/gen-ui-uswds-catalog.sh. Do not edit. Gitignored.\n# Source: USWDS release tree path metadata.\n# Policy: component/token catalog only; assets/source bodies/prose/execution excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: components={len(component_rows)}/{len(components)} tokens={len(token_files)} bytes={out.stat().st_size}')
PY
