#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_DIR="$ROOT/ingest/agriculture/nalt/unpacked"
OUT="$ROOT/stdlib/lib/corpus/agriculture-nal-nalt.generated.px"
MAX_CONCEPTS="${NALT_MAX_CONCEPTS:-5000}"
TTL="$(find "$SRC_DIR" -type f -name '*.ttl' | head -1)"
if [[ -z "${TTL:-}" || ! -f "$TTL" ]]; then
  echo "missing NALT ttl; run scripts/update-agriculture-nal-nalt.sh first" >&2
  exit 1
fi
python3 - "$TTL" "$OUT" "$MAX_CONCEPTS" <<'PY'
import re, sys, pathlib, hashlib
src, out, max_concepts = sys.argv[1], sys.argv[2], int(sys.argv[3])
text = pathlib.Path(src).read_text(encoding='utf-8', errors='replace')

def esc(s):
    return '"' + s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','') + '"'

def split_top(s, sep):
    out=[]; cur=[]; in_str=False; escp=False; angle=0
    for ch in s:
        if in_str:
            cur.append(ch)
            if escp: escp=False
            elif ch=='\\': escp=True
            elif ch=='"': in_str=False
        else:
            if ch=='"': in_str=True; cur.append(ch)
            elif ch=='<': angle+=1; cur.append(ch)
            elif ch=='>': angle=max(0,angle-1); cur.append(ch)
            elif ch==sep and angle==0:
                p=''.join(cur).strip()
                if p: out.append(p)
                cur=[]
            else: cur.append(ch)
    p=''.join(cur).strip()
    if p: out.append(p)
    return out

def tok(v):
    v=v.strip()
    if v.startswith('<') and '>' in v: return v[1:v.index('>')]
    return v.split()[0].strip() if v else ''

def lit_en(v):
    m=re.match(r'"((?:\\.|[^"\\])*)"@en\b', v.strip(), re.S)
    if not m: return None
    return bytes(m.group(1),'utf-8').decode('unicode_escape')

def arr(vals):
    vals=[v for v in vals if v]
    return '[ ' + ' '.join(esc(v) for v in vals) + ' ]'

concepts=[]; skipped_def_blocks=0; prose_fields=0
blocks=[]; cur=[]
for line in text.splitlines():
    if not line or line.startswith('@prefix'):
        continue
    cur.append(line)
    if line.rstrip().endswith('.'):
        blocks.append('\n'.join(cur)); cur=[]

for b in blocks:
    subject=b.split(None,1)[0]
    if subject.endswith('_def') or ' naltv:Definition ' in b or 'rdf:value' in b:
        skipped_def_blocks += 1
        continue
    if not subject.startswith('nalt:') or 'skos:Concept' not in b:
        continue
    body=b[len(subject):].strip()
    if body.endswith('.'): body=body[:-1]
    props={}
    for part in split_top(body, ';'):
        if not part.strip(): continue
        sp=part.strip().split(None,1)
        if len(sp)<2: continue
        pred, obj=sp
        props.setdefault(pred,[]).extend(split_top(obj, ','))
    c={}
    c['id']=subject.split(':',1)[1]
    c['uri']='https://lod.nal.usda.gov/nalt/' + c['id']
    c['types']=[tok(x) for x in props.get('a',[]) if tok(x) != 'skos:Concept'][:8]
    c['pref_en']=[x for x in (lit_en(o) for o in props.get('skos:prefLabel',[])) if x][:3]
    c['alt_en']=[x for x in (lit_en(o) for o in props.get('skos:altLabel',[])) if x][:12]
    c['broader']=[tok(x) for x in props.get('skos:broader',[])][:12]
    c['narrower']=[tok(x) for x in props.get('skos:narrower',[])][:12]
    c['in_scheme']=[tok(x) for x in props.get('skos:inScheme',[])][:8]
    c['exact_match']=[tok(x) for x in props.get('skos:exactMatch',[])][:8]
    c['close_match']=[tok(x) for x in props.get('skos:closeMatch',[])][:8]
    c['taxonomic_rank']=[tok(x) for x in props.get('naltv:taxonomicRank',[])][:3]
    marc=[lit_en(o) for o in props.get('naltv:marc001',[])]
    # marc001 has plain string, not @en
    if not marc:
        marc=[]
        for o in props.get('naltv:marc001',[]):
            m=re.match(r'"((?:\\.|[^"\\])*)"', o.strip(), re.S)
            if m: marc.append(bytes(m.group(1),'utf-8').decode('unicode_escape'))
    c['marc001']=marc[:1]
    if any(k in b for k in ['skos:definition','skos:scopeNote','rdf:value','dcterms:description']):
        prose_fields += 1
    concepts.append(c)
    if len(concepts) >= max_concepts:
        break

prefix='''# GENERATED by scripts/gen-agriculture-nal-nalt.sh. Do not edit. Gitignored.
# Source: NAL Agricultural Thesaurus Full RDF/Turtle (USDA NAL, CC-BY-4.0).
# Policy: structure only; definition/prose blocks and advisory/guidance text excluded.
{ schema = "agriculture.nal_nalt.skos_concepts.v1";
  source = "NAL Agricultural Thesaurus Full";
  license = "CC-BY-4.0";
  attribution = "NAL Agricultural Thesaurus (NALT), USDA National Agricultural Library, CC BY 4.0.";
'''
lines=[prefix]
lines.append(f'  source_digest_sha256 = {esc(hashlib.sha256(pathlib.Path(src).read_bytes()).hexdigest())};\n')
lines.append(f'  summary = {{ concepts = {len(concepts)}; skipped_definition_blocks = {skipped_def_blocks}; prose_fields_excluded = {prose_fields}; max_concepts = {max_concepts}; }};\n')
lines.append('  concepts = [\n')
for c in concepts:
    fields=[]
    for k in ['id','uri']:
        fields.append(f'{k} = {esc(c[k])};')
    for k in ['types','pref_en','alt_en','broader','narrower','in_scheme','exact_match','close_match','taxonomic_rank','marc001']:
        fields.append(f'{k} = {arr(c[k])};')
    lines.append('    { ' + ' '.join(fields) + ' }\n')
lines.append('  ];\n}\n')
pathlib.Path(out).write_text(''.join(lines), encoding='utf-8')
print(f'generated {out}: concepts={len(concepts)} skipped_definition_blocks={skipped_def_blocks} bytes={pathlib.Path(out).stat().st_size}')
PY
