#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/code/rust-reference"
OUT="$ROOT/stdlib/lib/corpus/rust-reference.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json,pathlib,re,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,(int,float)): return str(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
tags=[]
if (src/'tags.ndjson').exists():
    for line in (src/'tags.ndjson').read_text(encoding='utf-8').splitlines():
        if line.strip():
            x=json.loads(line); tags.append({'name':x.get('name'),'commit_sha':x.get('commit_sha')})
rust_release_tags=[]
if (src/'rust-release-tags.ndjson').exists():
    for line in (src/'rust-release-tags.ndjson').read_text(encoding='utf-8').splitlines():
        if line.strip():
            x=json.loads(line); rust_release_tags.append({'name':x.get('name'),'commit_sha':x.get('commit_sha')})
docs=[]; headings=[]; codeblocks=[]
for p in sorted((src/'src').rglob('*.md')):
    rel=str(p.relative_to(src))
    txt=p.read_text(encoding='utf-8',errors='replace')
    docs.append({'path':rel,'bytes':p.stat().st_size,'line_count':txt.count('\n')+1})
    for m in re.finditer(r'^(#{1,6})\s+(.+)$',txt,re.M):
        title=re.sub(r'[`*_#<>]','',m.group(2)).strip()[:160]
        headings.append({'path':rel,'level':len(m.group(1)),'title':title})
    for m in re.finditer(r'^```([^\n`]*)',txt,re.M):
        lang=m.group(1).strip()[:40]
        if lang:
            codeblocks.append({'path':rel,'language':lang})
obj={'schema':'code.rust.reference_metadata.v1','source':'Rust Reference structural metadata','license':'MIT OR Apache-2.0','summary':{'reference_tags':len(tags),'rust_release_tags':len(rust_release_tags),'documents':len(docs),'headings':len(headings),'codeblock_markers':len(codeblocks)},'policy':'Rust Reference tag catalog, document path metadata, headings, and code-block language markers only; prose bodies/examples/compiler source/crates/user code/execution/graph wiring excluded','manifest':manifest,'reference_tags':tags,'rust_release_tags':rust_release_tags,'documents':docs,'headings':headings[:1000],'codeblock_markers':codeblocks[:1000]}
out.write_text('# GENERATED by scripts/gen-code-rust-reference.sh. Do not edit. Gitignored.\n# Source: Rust Reference structural metadata only; prose bodies/examples excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: reference_tags={len(tags)} rust_release_tags={len(rust_release_tags)} docs={len(docs)} headings={len(headings)} codeblocks={len(codeblocks)} bytes={out.stat().st_size}')
PY
