#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/legal/doj-fara-catalog"
OUT="$ROOT/stdlib/lib/corpus/doj-fara-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib,sys,json,hashlib,re,html,urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(re.sub('<.*?>',' ',str(s or '')))).strip()
def sig(txt):
    b=txt.encode() if isinstance(txt,str) else txt
    return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
pages=[]
for p in sorted(src.glob('*.html')):
    txt=p.read_text(errors='ignore')
    mt=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
    links=[]
    for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>',txt,re.I|re.S):
        href=html.unescape(m.group(1)); label=clean(m.group(2))[:160]
        if href and not href.startswith('#') and any(k in (href+' '+label).lower() for k in ['fara','efile','search','document','data.gov','justice.gov']):
            links.append({'label':label,'href':urllib.parse.urljoin('https://www.justice.gov/',href)})
    pages.append({'page':p.stem,'file':p.name,'title':clean(mt.group(1))[:220] if mt else '', 'html_sig':sig(txt),'links':links[:120]})
ckan={}
if (src/'datagov-package.json').exists():
    raw=json.loads((src/'datagov-package.json').read_text())
    ckan=raw.get('result') or raw
resources=[]
for r in ckan.get('resources') or []:
    resources.append({'id':r.get('id',''),'name':r.get('name',''),'format':r.get('format',''),'mimetype':r.get('mimetype',''),'url':r.get('url',''),'created':r.get('created',''),'last_modified':r.get('last_modified','')})
org=ckan.get('organization') or {}
dataset={'id':ckan.get('id',''),'name':ckan.get('name',''),'title':ckan.get('title',''),'license_title':ckan.get('license_title',''),'metadata_created':ckan.get('metadata_created',''),'metadata_modified':ckan.get('metadata_modified',''),'organization':{'name':org.get('name',''),'title':org.get('title','')},'tags':[t.get('name','') for t in ckan.get('tags') or []][:80],'resources':resources[:80]}
if ckan.get('notes'): dataset['notes_hash']={'present':True,'sha256':hashlib.sha256(str(ckan.get('notes')).encode()).hexdigest(),'len':len(str(ckan.get('notes')))}
files=[]
for p in sorted(src.iterdir()):
    if p.is_file(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'legal.doj_fara.catalog.v1','source':'DOJ FARA / Data.gov catalog metadata','license':'US federal public catalog metadata; FARA payloads excluded','summary':{'pages':len(pages),'links':sum(len(x['links']) for x in pages),'resources':len(resources),'files':len(files)},'policy':'Catalog/page/resource metadata only. Excludes registrant records, foreign-principal records, filings, document PDFs, disclosure narratives, legal guidance/advice prose, search-result payloads, credentials, and graph/mirror wiring.','manifest':manifest,'files':files,'pages':pages,'datagov_dataset':dataset}
out.write_text('# GENERATED by scripts/gen-legal-doj-fara-catalog.sh. Do not edit. Gitignored.\n# Source: DOJ FARA/Data.gov catalog metadata only; filing/search/document payloads excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} resources={len(resources)} bytes={out.stat().st_size}')
PY
