#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${NIST_LEGAL_METROLOGY_SRC:-$ROOT/ingest/units/nist-legal-metrology-handbooks}"
OUT="${NIST_LEGAL_METROLOGY_OUT:-$ROOT/stdlib/lib/corpus/nist-legal-metrology-handbooks.generated.px}"
python3 - <<'PY' "$SRC" "$OUT"
import json,pathlib,re,sys,urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
def clean(s): return re.sub(r'\s+',' ', re.sub(r'<[^>]+>',' ',s)).strip()
def links(html):
    out=[]
    for m in re.finditer(r'href="([^"]+)"', html):
        href=m.group(1)
        if any(x in href.lower() for x in ['pdf','docx','publication','get_pdf','handbook']):
            out.append(urllib.parse.urljoin('https://www.nist.gov/', href))
    return sorted(set(out))[:120]
def page_record(path,hid):
    html=path.read_text(errors='replace')
    version=None
    m=re.search(r'Current Version\s*-\s*(\d{4})', clean(html), re.I)
    if m: version=m.group(1)
    title='NIST Handbook '+hid
    if hid=='44': title='NIST Handbook 44: Specifications, Tolerances, and Other Technical Requirements for Weighing and Measuring Devices'
    if hid=='130': title='NIST Handbook 130: Uniform Laws and Regulations in the Areas of Legal Metrology and Fuel Quality'
    return {'handbook':hid,'title':title,'current_version':version,'source_file':path.name,'document_links':links(html),'body_text_ingested':False,'legal_advice_ingested':False,'device_judgment_ingested':False}
records=[page_record(src/'raw/handbook-44-current.html','44'), page_record(src/'raw/handbook-130-current.html','130')]
index_html=(src/'raw/handbooks-index.html').read_text(errors='replace')
def esc(s): s='' if s is None else str(s); return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'
def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return esc(v)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))
seed={'schema':'units.nist_legal_metrology_handbooks.v1','source':{'name':'NIST Handbooks 44/130 current-edition metadata catalog','license':'US-PD / NIST public publication metadata','retrieved_at_unix':receipt.get('retrieved_at_unix')},'summary':{'handbook_count':len(records),'document_link_count':sum(len(r['document_links']) for r in records),'index_has_handbook_44':'Handbook 44' in index_html,'index_has_handbook_130':'Handbook 130' in index_html,'pdf_body_ingested':False,'docx_body_ingested':False,'legal_advice_ingested':False,'device_pass_fail_judgment_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'handbooks':records}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/gen-units-nist-legal-metrology-handbooks.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: handbooks={len(records)}, document_links={seed["summary"]["document_link_count"]}')
PY
