#!/usr/bin/env bash
set -euo pipefail
ROOT="${PNIX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
SRC="${CALCITE_SOURCE:-$ROOT/ingest/code/calcite/unpacked}"
VERSION="${CALCITE_VERSION:-1.42.0}"
JAR="$ROOT/ingest/code/calcite/calcite-core-$VERSION.jar"
OUT="${CALCITE_OUT:-$ROOT/stdlib/lib/corpus/calcite.generated.px}"
LIMIT="${CALCITE_CLASS_LIMIT:-1000}"
if [ ! -d "$SRC/org/apache/calcite" ]; then
  echo "missing Calcite unpacked source: $SRC" >&2
  echo "run: scripts/update-code-calcite.sh" >&2
  exit 1
fi
mkdir -p "$(dirname "$OUT")"
python3 - "$SRC" "$JAR" "$OUT" "$VERSION" "$LIMIT" <<'PY'
import hashlib, sys
from pathlib import Path
src=Path(sys.argv[1]); jar=Path(sys.argv[2]); out=Path(sys.argv[3]); version=sys.argv[4]; limit=int(sys.argv[5])

def q(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')+'"'

def lit(v, indent=0):
    sp=' '*indent
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if v is None: return 'null'
    if isinstance(v,str): return q(v)
    if isinstance(v,list):
        if not v: return '[ ]'
        return '[\n'+''.join(' '*(indent+2)+lit(x, indent+2)+'\n' for x in v)+sp+']'
    if isinstance(v,dict):
        if not v: return '{ }'
        lines=['{']
        for k in v:
            lines.append(' '*(indent+2)+k+' = '+lit(v[k], indent+2)+';')
        lines.append(sp+'}')
        return '\n'.join(lines)
    raise TypeError(type(v))

def cat(rel):
    if '/sql/' in rel: return 'sql'
    if '/rel/' in rel: return 'rel'
    if '/rex/' in rel: return 'rex'
    if '/adapter/' in rel: return 'adapter'
    if '/schema/' in rel: return 'schema'
    if '/plan/' in rel: return 'plan'
    return 'other'
classes=[]; total=0
for fp in sorted((src/'org/apache/calcite').rglob('*.class')):
    rel=str(fp.relative_to(src)).replace('\\','/')
    if '$' in rel: continue
    total += 1
    if len(classes) >= limit: continue
    name=rel[:-6].replace('/','.')
    simple=name.rsplit('.',1)[-1]
    classes.append({'class':name, 'simple':simple, 'category':cat(rel)})
sha=hashlib.sha256(jar.read_bytes()).hexdigest() if jar.exists() else ''
value={
  'schema':'code.calcite.taxonomy.v1',
  'source':'Apache Calcite core Maven artifact class taxonomy',
  'license':'Apache-2.0',
  'source_url':'https://repo1.maven.org/maven2/org/apache/calcite/calcite-core/<version>/',
  'source_sha256':sha,
  'version':version,
  'class_limit':limit,
  'total_classes_seen':total,
  'classes':classes,
}
out.write_text('# GENERATED by scripts/gen-code-calcite.sh; do not commit.\n'+lit(value)+'\n', encoding='utf-8')
print(f"generated {out}: classes={len(classes)} total_classes={total} version={version} sha256={sha}")
PY
