#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/science/usgs-ngmdb-catalog"
OUT="$ROOT/stdlib/lib/corpus/usgs-ngmdb-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def sig(txt):
    b=txt.encode() if isinstance(txt,str) else txt
    return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def page_meta(path,page_id):
    txt=path.read_text(errors='ignore')
    mt=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
    links=[]
    for m in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>', txt, re.I|re.S):
        href=html.unescape(m.group(1)); label=clean(re.sub('<.*?>',' ',m.group(2)))[:180]
        if href and not href.startswith('#'):
            low=(href+' '+label).lower()
            if any(k in low for k in ['ngmdb','mapview','prodesc','catalog','lexicon','geologic','download','search']):
                kind='catalog_link'
                if any(k in low for k in ['download','.pdf','.zip','.tif','.shp','.gis','.kmz','.jpg']): kind='payload_ref_excluded'
                links.append({'kind':kind,'label':label,'href':urllib.parse.urljoin('https://ngmdb.usgs.gov/',href)})
    tokens=sorted(set([x.lower() for x in re.findall(r'\b(?:NGMDB|geologic map|mapview|catalog|product|publisher|lexicon|stratigraphy|download)\b',txt,re.I)]))
    return {'page':page_id,'file':path.name,'title':clean(re.sub('<.*?>',' ',mt.group(1)))[:220] if mt else '', 'html_sig':sig(txt),'tokens':tokens,'links':links[:160]}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
pages=[]
for name,page_id in [('ngmdb-home.html','home'),('mapview.html','mapview'),('product-sample.html','product_sample')]:
    p=src/name
    if p.exists(): pages.append(page_meta(p,page_id))
files=[]
for p in [src/'source-manifest.json',src/'ngmdb-home.html',src/'mapview.html',src/'product-sample.html']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'science.usgs_ngmdb.catalog.v1','source':'USGS National Geologic Map Database catalog metadata','license':'US-PD index/catalog metadata; map payloads per-publisher excluded','summary':{'pages':len(pages),'links':sum(len(x['links']) for x in pages),'files':len(files)},'policy':'official NGMDB index/catalog page metadata only; actual geologic map sheets, publisher-owned map payloads, images/PDFs/GIS files, detailed map features, construction/site stability judgments, geohazard advice, and graph wiring excluded','manifest':manifest,'files':files,'pages':pages}
out.write_text('# GENERATED by scripts/gen-science-usgs-ngmdb-catalog.sh. Do not edit. Gitignored.\n# Source: USGS NGMDB catalog metadata only; map payloads/stability/geohazard judgments excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} links={obj["summary"]["links"]} bytes={out.stat().st_size}')
PY
