#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${GHA_WORKFLOW_SYNTAX_SRC:-$ROOT/ingest/devops/github-actions-workflow-syntax}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/github-actions-workflow-syntax.generated.px}"
python3 - "$SRC" "$OUT" <<'PY'
import json, re, sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2])
receipt=json.loads((src/'source-receipt.json').read_text())
text=(src/'raw/workflow-syntax.md').read_text(encoding='utf-8', errors='replace')

def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,(int,float)): return repr(v)
    if isinstance(v,str): return json.dumps(v, ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))

def anchor(s):
    s=re.sub(r'<[^>]+>','',s).strip().lower()
    s=re.sub(r'[`{}]', '', s)
    s=re.sub(r'[^a-z0-9 _.-]+','',s)
    return re.sub(r'[\s.]+','-',s).strip('-')
headings=[]; tokens=set()
for line in text.splitlines():
    m=re.match(r'^(#{2,5})\s+(.+?)\s*$', line)
    if not m: continue
    level=len(m.group(1)); title=m.group(2).strip()
    if not any(x in title.lower() for x in ['workflow', 'jobs', 'steps', 'runs-on', 'permissions', 'env', 'defaults', 'strategy', 'matrix', 'needs', 'if', 'uses', 'with', 'secrets', 'on', 'concurrency', 'run-name', 'timeout-minutes', 'continue-on-error', 'container', 'services']):
        continue
    code_tokens=re.findall(r'`([^`]+)`', title)
    rec={'level':level,'title':re.sub(r'`','',title),'anchor':anchor(title)}
    if code_tokens:
        rec['tokens']=code_tokens
        for t in code_tokens:
            if re.fullmatch(r'[A-Za-z0-9_.<>{}\[\]-]+', t): tokens.add(t)
    headings.append(rec)
# Add stable top-level workflow keys even if docs heading wording changes.
for t in ['name','run-name','on','permissions','env','defaults','concurrency','jobs','jobs.<job_id>','jobs.<job_id>.name','jobs.<job_id>.needs','jobs.<job_id>.if','jobs.<job_id>.runs-on','jobs.<job_id>.permissions','jobs.<job_id>.env','jobs.<job_id>.defaults','jobs.<job_id>.steps','jobs.<job_id>.timeout-minutes','jobs.<job_id>.strategy','jobs.<job_id>.continue-on-error','jobs.<job_id>.container','jobs.<job_id>.services','steps[*].name','steps[*].id','steps[*].if','steps[*].uses','steps[*].run','steps[*].with','steps[*].env','steps[*].shell','steps[*].working-directory']:
    tokens.add(t)
seed={'schema':'devops.github_actions.workflow_syntax.v1','source':{'name':'GitHub Actions workflow syntax reference','license':'CC-BY-4.0','retrieved_at':receipt.get('retrieved_at')},'summary':{'heading_count':len(headings),'token_count':len(tokens),'prose_body_ingested':False,'examples_ingested':False,'real_workflows_ingested':False,'secrets_ingested':False,'logs_artifacts_ingested':False,'deployment_execution_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'headings':headings,'tokens':[{'token':t} for t in sorted(tokens)]}
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('# GENERATED by scripts/gen-devops-github-actions-workflow-syntax.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: headings={len(headings)}, tokens={len(tokens)}')
PY
