#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/ui/govuk-design-system-catalog"
OUT="$ROOT/stdlib/lib/corpus/govuk-design-system-catalog.generated.px"
LIMIT="${GOVUK_DESIGN_SYSTEM_LIMIT:-400}"
python3 - "$SRC" "$OUT" "$LIMIT" <<'PY'
import pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); limit=int(sys.argv[3])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
tree=json.loads((src/'tree.json').read_text())
files=[]
for name in ['tree.json','LICENSE']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
components={}; patterns={}; style_pages=[]; variants=[]
for row in tree.get('tree',[]):
    path=row.get('path','')
    if row.get('type')!='blob': continue
    if any(path.endswith(ext) for ext in ['.png','.jpg','.jpeg','.gif','.mp4','.svg','.ico']): continue
    parts=path.split('/')
    if len(parts)>=3 and parts[0]=='src' and parts[1]=='components':
        name=parts[2]; entry=components.setdefault(name, {'name':name,'has_markdown':False,'template_variants':0,'style_files':0})
        if path.endswith('index.md'): entry['has_markdown']=True
        if path.endswith('.njk'):
            entry['template_variants']+=1
            if len(parts)>=5: variants.append({'kind':'component','name':name,'variant':parts[3],'path':path})
        if path.endswith('.scss'): entry['style_files']+=1
    elif len(parts)>=3 and parts[0]=='src' and parts[1]=='patterns':
        name=parts[2]; entry=patterns.setdefault(name, {'name':name,'has_markdown':False,'template_variants':0,'style_files':0})
        if path.endswith('index.md'): entry['has_markdown']=True
        if path.endswith('.njk'):
            entry['template_variants']+=1
            if len(parts)>=5: variants.append({'kind':'pattern','name':name,'variant':parts[3],'path':path})
        if path.endswith('.scss'): entry['style_files']+=1
    elif path.startswith('src/styles/') and path.endswith(('.md','.njk','.scss')):
        style_pages.append({'path':path,'name':'/'.join(parts[2:-1]) or parts[-1].split('.')[0],'kind':parts[-1].rsplit('.',1)[-1]})
component_rows=list(sorted(components.values(), key=lambda x:x['name']))[:limit]
pattern_rows=list(sorted(patterns.values(), key=lambda x:x['name']))[:limit]
obj={'schema':'ui.govuk_design_system.catalog.v1','source':'GOV.UK Design System repository tree catalog','license':'MIT','summary':{'components':len(component_rows),'components_total_seen':len(components),'patterns':len(pattern_rows),'patterns_total_seen':len(patterns),'variants':len(variants),'style_pages':len(style_pages),'limit':limit},'policy':'path/name catalog metadata only; docs prose, templates/style/script bodies, assets, examples, runtime rendering, graph wiring excluded','manifest':manifest,'files':files,'components':component_rows,'patterns':pattern_rows,'variants':variants[:800],'style_pages':style_pages[:600]}
out.write_text('# GENERATED by scripts/gen-ui-govuk-design-system-catalog.sh. Do not edit. Gitignored.\n# Source: GOV.UK Design System repository tree path metadata.\n# Policy: component/pattern/style catalog only; prose/assets/code bodies/execution excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: components={len(component_rows)}/{len(components)} patterns={len(pattern_rows)}/{len(patterns)} bytes={out.stat().st_size}')
PY
