#!/usr/bin/env bash
set -euo pipefail
ROOT="${PNIX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
SRC="${LEAN_MATHLIB4_SOURCE:-$ROOT/ingest/math/proof/lean-mathlib4/src}"
OUT="${LEAN_MATHLIB4_OUT:-$ROOT/stdlib/lib/corpus/lean-mathlib4.generated.px}"
LIMIT="${LEAN_MATHLIB4_DECL_LIMIT:-500}"
if [ ! -d "$SRC/Mathlib" ]; then
  echo "missing mathlib4 source: $SRC" >&2
  echo "run: scripts/update-math-proof-lean-mathlib4.sh" >&2
  exit 1
fi
mkdir -p "$(dirname "$OUT")"
python3 - "$SRC" "$OUT" "$LIMIT" <<'PY'
import hashlib, json, re, subprocess, sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2]); limit=int(sys.argv[3])
release_path=src.parent/'release.json'
release=json.load(release_path.open()) if release_path.exists() else {}

def q(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')+'"'

def lit(v, indent=0):
    sp=' '*indent
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if v is None: return 'null'
    if isinstance(v,str): return q(v)
    if isinstance(v,list):
        if not v: return '[ ]'
        return '[\n'+''.join(' '*(indent+2)+lit(x, indent+2)+'\n' for x in v)+sp+']'
    if isinstance(v,dict):
        if not v: return '{ }'
        lines=['{']
        for k in v:
            lines.append(' '*(indent+2)+k+' = '+lit(v[k], indent+2)+';')
        lines.append(sp+'}')
        return '\n'.join(lines)
    raise TypeError(type(v))

decl_re=re.compile(r'^\s*(?:@[A-Za-z0-9_`.,\[\]\s:=(){}!?.+-]+\s+)?(?:(?:private|protected|noncomputable|unsafe|partial)\s+)*(theorem|lemma|def|abbrev|instance|class|structure|inductive|axiom)\s+([^\s(:{]+)')
imports=[]; decls=[]; files_seen=0
for fp in sorted((src/'Mathlib').rglob('*.lean')):
    rel=str(fp.relative_to(src))
    files_seen += 1
    try:
        lines=fp.read_text(encoding='utf-8', errors='replace').splitlines()
    except Exception:
        continue
    file_imports=[]
    for i,line in enumerate(lines,1):
        if line.startswith('import '):
            target=line.split(None,1)[1].strip()
            file_imports.append(target)
            if len(imports) < limit:
                imports.append({'file':rel, 'target':target})
        m=decl_re.match(line)
        if m and len(decls) < limit:
            decls.append({'file':rel, 'line':i, 'kind':m.group(1), 'name':m.group(2)})
    if len(decls) >= limit and len(imports) >= limit:
        break
sha=''
# cheap source fingerprint: release tag+first file paths, not full tree hash.
sha=hashlib.sha256((release.get('tag_name','')+'\n'+str(files_seen)).encode()).hexdigest()
value={
  'schema':'math.proof.lean_mathlib4.v1',
  'source':'leanprover-community/mathlib4 source metadata',
  'license':'Apache-2.0',
  'source_url':'https://github.com/leanprover-community/mathlib4',
  'release_tag':release.get('tag_name',''),
  'release_id':release.get('id',''),
  'source_fingerprint':sha,
  'decl_limit':limit,
  'files_seen':files_seen,
  'declarations':decls,
  'imports':imports,
}
out.write_text('# GENERATED by scripts/gen-math-proof-lean-mathlib4.sh; do not commit.\n'+lit(value)+'\n', encoding='utf-8')
print(f"generated {out}: declarations={len(decls)} imports={len(imports)} files_seen={files_seen} tag={release.get('tag_name','')}")
PY
