#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/election/eac-eavs-resource-catalog"
OUT="$ROOT/stdlib/lib/corpus/eac-eavs-resource-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import html, json, pathlib, re, sys, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text())
base=manifest['files'][0]['url']
text=(src/manifest['files'][0]['path']).read_text(encoding='utf-8',errors='replace')

def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))

def clean(s): return html.unescape(re.sub(r'\s+',' ',re.sub('<[^>]+>',' ',s))).strip()
# Limit to EAVS reports/materials section; keep only link metadata around reporting years.
resources=[]; current_year=None
for m in re.finditer(r'(?is)<h[34][^>]*>(.*?)</h[34]>|<a\s+[^>]*href="([^"]+)"[^>]*>(.*?)</a>', text):
    if m.group(1) is not None:
        heading=clean(m.group(1))
        ym=re.search(r'\b(20\d{2})\b', heading)
        if ym: current_year=ym.group(1)
        continue
    href=html.unescape(m.group(2)); label=clean(m.group(3))
    if not label or len(label) > 180: continue
    if not re.search(r'EAVS|Election Administration|Policy Survey|NVRA|UOCAVA|Data Codebook|Dataset|CSV|Excel|SPSS|Stata|SAS|Instrument|Glossary|Errata', label, re.I):
        continue
    url=urllib.parse.urljoin(base,href)
    fmt='html'
    low=(label+' '+url).lower()
    for f in ['csv','excel','xlsx','pdf','spss','stata','sas','powerbi']:
        if f in low: fmt=f
    resources.append({'year':current_year or '', 'label':label, 'url':url, 'format_hint':fmt})
# de-dup stable
seen=set(); dedup=[]
for r in resources:
    key=(r['year'],r['label'],r['url'])
    if key in seen: continue
    seen.add(key); dedup.append(r)
obj={'schema':'election.eac_eavs.resource_catalog.v1','source':'U.S. Election Assistance Commission EAVS reports/materials page','license':'US-PD / US federal public information','policy':'resource-link catalog metadata only; EAVS data rows/report bodies/state-local values/voter files/election-operation advice/graph wiring excluded','summary':{'resources':len(dedup),'years':sorted({r['year'] for r in dedup if r['year']}, reverse=True)},'manifest':manifest,'resources':dedup}
out.write_text('# GENERATED by scripts/gen-election-eac-eavs-resource-catalog.sh. Do not edit. Gitignored.\n# Source: EAC EAVS resource-link catalog metadata only; data/report payloads excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: resources={len(dedup)} bytes={out.stat().st_size}')
PY
