#!/usr/bin/env bash
set -euo pipefail
ROOT="${PNIX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
SRC="${TZDB_SOURCE:-$ROOT/ingest/time/tzdb/src}"
TAR="$ROOT/ingest/time/tzdb/tzdata-latest.tar.gz"
OUT="${TZDB_OUT:-$ROOT/stdlib/lib/corpus/tzdb.generated.px}"
if [ ! -f "$SRC/zone1970.tab" ]; then
  echo "missing TZDB source: $SRC" >&2
  echo "run: scripts/update-time-tzdb.sh" >&2
  exit 1
fi
mkdir -p "$(dirname "$OUT")"
python3 - "$SRC" "$TAR" "$OUT" <<'PY'
import hashlib, sys
from pathlib import Path
src=Path(sys.argv[1]); tar=Path(sys.argv[2]); out=Path(sys.argv[3])

def q(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')+'"'

def lit(v, indent=0):
    sp=' '*indent
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if v is None: return 'null'
    if isinstance(v,str): return q(v)
    if isinstance(v,list):
        if not v: return '[ ]'
        return '[\n'+''.join(' '*(indent+2)+lit(x, indent+2)+'\n' for x in v)+sp+']'
    if isinstance(v,dict):
        if not v: return '{ }'
        lines=['{']
        for k in v:
            lines.append(' '*(indent+2)+k+' = '+lit(v[k], indent+2)+';')
        lines.append(sp+'}')
        return '\n'.join(lines)
    raise TypeError(type(v))

def rows(path, cols):
    out=[]
    for line in path.read_text(encoding='utf-8', errors='replace').splitlines():
        if not line or line.startswith('#'): continue
        parts=line.split('\t')
        rec={}
        for i,c in enumerate(cols):
            if i < len(parts) and parts[i]: rec[c]=parts[i]
        if rec: out.append(rec)
    return out
zones=rows(src/'zone1970.tab', ['countries','coordinates','tzid','comments'])
legacy=rows(src/'zone.tab', ['country','coordinates','tzid','comments']) if (src/'zone.tab').exists() else []
countries=rows(src/'iso3166.tab', ['country','name']) if (src/'iso3166.tab').exists() else []
version=(src/'version').read_text().strip() if (src/'version').exists() else ''
sha=hashlib.sha256(tar.read_bytes()).hexdigest() if tar.exists() else ''
value={
  'schema':'time.tzdb.v1',
  'source':'IANA Time Zone Database tzdata',
  'license':'Public Domain / public-domain style TZDB notice',
  'source_url':'https://www.iana.org/time-zones/repository/tzdata-latest.tar.gz',
  'source_sha256':sha,
  'tzdb_version':version,
  'zones':zones,
  'legacy_zones':legacy,
  'countries':countries,
}
out.write_text('# GENERATED by scripts/gen-time-tzdb.sh; do not commit.\n'+lit(value)+'\n', encoding='utf-8')
print(f"generated {out}: zones={len(zones)} legacy_zones={len(legacy)} countries={len(countries)} version={version} sha256={sha}")
PY
