#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/bio/ncbi-gene-reference-catalog"
OUT="$ROOT/stdlib/lib/corpus/ncbi-gene-reference-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import gzip, json, os, pathlib, sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text())
limit=int(os.environ.get('NCBI_GENE_ROWS_PER_SPECIES','200'))

def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
records=[]; species=[]
for f in manifest.get('files',[]):
    rows=[]; total_seen=0; header=None
    with gzip.open(src/f['path'],'rt',encoding='utf-8',errors='replace') as fh:
        for line in fh:
            line=line.rstrip('\n')
            if line.startswith('#'):
                header=line.lstrip('#').split('\t'); continue
            total_seen += 1
            if len(rows) >= limit: continue
            vals=line.split('\t')
            if header and len(vals) >= len(header):
                d=dict(zip(header,vals))
            else: continue
            rows.append({'species_key':f.get('key'),'tax_id':d.get('tax_id',''),'gene_id':d.get('GeneID',''),'symbol':d.get('Symbol',''),'type_of_gene':d.get('type_of_gene',''),'chromosome':d.get('chromosome',''),'modification_date':d.get('Modification_date','')})
    species.append({'key':f.get('key'),'source_url':f.get('url'),'rows_stored':len(rows),'rows_available_in_file':total_seen})
    records.extend(rows)
obj={'schema':'genome.ncbi_gene.reference_catalog.v1','source':'NCBI Gene organism-specific gene_info identifier metadata','license':'US-PD / NCBI public data caveats','policy':'bounded gene identifier metadata only; full all-species bulk, sequences, phenotypes, interactions, expression data, GeneRIF/publication text, clinical interpretation, genetic engineering/design guidance and graph wiring excluded','summary':{'species_files':len(manifest.get('files',[])),'rows':len(records),'rows_per_species_limit':limit},'manifest':manifest,'species':species,'genes':records}
out.write_text('# GENERATED by scripts/gen-bio-ncbi-gene-reference-catalog.sh. Do not edit. Gitignored.\n# Source: NCBI Gene identifier metadata only; sequence/phenotype/design payloads excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: species={len(species)} genes={len(records)} bytes={out.stat().st_size}')
PY
