#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/demography/census-cvap-resource-catalog"
OUT="$ROOT/stdlib/lib/corpus/census-cvap-resource-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import html, json, pathlib, re, sys, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text())

def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))

def clean(s): return html.unescape(re.sub(r'\s+',' ',re.sub('<[^>]+>',' ',s))).strip()
resources=[]
for f in manifest.get('files',[]):
    base=f['url']; text=(src/f['path']).read_text(encoding='utf-8',errors='replace')
    ym=re.search(r'(20\d{2})-CVAP|/(20\d{2})-CVAP|\b(20\d{2})\b', base)
    year=next((g for g in (ym.groups() if ym else []) if g), '')
    for m in re.finditer(r'(?is)<a\s+[^>]*href="([^"]+)"[^>]*>(.*?)</a>', text):
        href=html.unescape(m.group(1)); label=clean(m.group(2))
        if not label or len(label)>180: continue
        low=(label+' '+href).lower()
        if not any(tok in low for tok in ['cvap','citizen voting','csv','sas','technical documentation','general notes']):
            continue
        url=urllib.parse.urljoin(base,href)
        fmt='html'
        for x in ['zip','csv','sas','pdf','xlsx']:
            if x in low: fmt=x
        y=year
        my=re.search(r'20\d{2}', label+' '+url)
        if my: y=my.group(0)
        resources.append({'year':y,'label':label,'url':url,'format_hint':fmt,'source_page':base})
seen=set(); dedup=[]
for r in resources:
    k=(r['year'],r['label'],r['url'])
    if k in seen: continue
    seen.add(k); dedup.append(r)
obj={'schema':'demography.census_cvap.resource_catalog.v1','source':'U.S. Census Bureau CVAP resource pages','license':'US-PD / US federal public information','policy':'resource-link catalog metadata only; CVAP data ZIP/CSV/SAS/PDF payload rows/bodies, statistical values, voting-rights legal analysis and graph wiring excluded','summary':{'resources':len(dedup),'source_pages':len(manifest.get('files',[])),'years':sorted({r['year'] for r in dedup if r['year']}, reverse=True)},'manifest':manifest,'resources':dedup}
out.write_text('# GENERATED by scripts/gen-demography-census-cvap-resource-catalog.sh. Do not edit. Gitignored.\n# Source: Census CVAP resource-link catalog metadata only; data/PDF payloads excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: resources={len(dedup)} bytes={out.stat().st_size}')
PY
