#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/agriculture/usda-plants-api-catalog"
OUT="$ROOT/stdlib/lib/corpus/usda-plants-api-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def sig_bytes(b): return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
config=json.loads((src/'config.json').read_text()) if (src/'config.json').exists() else {}
service_urls=[]
for k,v in sorted((config.get('serviceUrls') or {}).items()):
    service_urls.append({'name':k,'url':v,'payload_policy':'catalog only; do not fetch payload rows'})
main=(src/'main.js').read_text(errors='ignore') if (src/'main.js').exists() else ''
endpoint_tokens=sorted(set(re.findall(r'(?:serviceUrl\s*\+\s*|\$\{[^}]*serviceUrl[^}]*\})([A-Za-z][A-Za-z0-9_-]{2,80})', main)))
route_tokens=sorted(set(re.findall(r'\["(/[^"?]{2,80})"\]', main)))
endpoints=[{'token':x,'method':'unknown','payload_policy':'not called by ingest; response payload excluded'} for x in endpoint_tokens[:120]]
routes=[{'route':x} for x in route_tokens[:120] if any(k in x.lower() for k in ['search','download','plants','cover','rarity','duration','group','image','noxious','invasive'])]
files=[]
for p in [src/'source-manifest.json',src/'home.html',src/'config.json',src/'main.js']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
home_sig={'bytes':0,'sha256':''}
if (src/'home.html').exists(): home_sig=sig_bytes((src/'home.html').read_bytes())
obj={'schema':'agriculture.usda_plants.api_catalog.v1','source':'USDA PLANTS Database application/API catalog metadata','license':'US-PD / US federal public information','summary':{'service_urls':len(service_urls),'endpoint_tokens':len(endpoints),'routes':len(routes),'files':len(files)},'policy':'official application shell/config and endpoint token metadata only; plant taxon/search result payloads, images, document library files, maps/geometries, pesticide/control/breeding/growing guidance, conservation/range judgments, and graph wiring excluded','manifest':manifest,'files':files,'home_html_sig':home_sig,'env':config.get('env',{}),'service_urls':service_urls,'endpoint_tokens':endpoints,'routes':routes}
out.write_text('# GENERATED by scripts/gen-agriculture-usda-plants-api-catalog.sh. Do not edit. Gitignored.\n# Source: USDA PLANTS app/API catalog metadata only; plant payloads/maps/documents/guidance excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: service_urls={len(service_urls)} endpoints={len(endpoints)} routes={len(routes)} bytes={out.stat().st_size}')
PY
