#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/license/clearlydefined-definitions"
OUT="$ROOT/stdlib/lib/corpus/clearlydefined-definitions.generated.px"
LIMIT="${CLEARLYDEFINED_LIMIT:-250}"
python3 - "$SRC" "$OUT" "$LIMIT" <<'PY'
import pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); limit=int(sys.argv[3])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for p in [src/'source-manifest.json']+sorted((src/'pages').glob('*.json')):
    if p.exists(): files.append({'path':str(p.relative_to(src)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
rows=[]; type_counts={}; provider_counts={}; declared_counts={}
for p in sorted((src/'pages').glob('*.json')):
    page=json.loads(p.read_text())
    for d in page.get('data') or []:
        c=d.get('coordinates') or {}
        lic=d.get('licensed') or {}
        desc=d.get('described') or {}
        sl=desc.get('sourceLocation') or {}
        facets=lic.get('facets') or {}
        exprs=[]
        for f in facets.values():
            disc=(f or {}).get('discovered') or {}
            for e in disc.get('expressions') or []:
                if e not in exprs: exprs.append(e)
        typ=c.get('type',''); prov=c.get('provider',''); decl=lic.get('declared','')
        type_counts[typ]=type_counts.get(typ,0)+1
        provider_counts[prov]=provider_counts.get(prov,0)+1
        declared_counts[decl]=declared_counts.get(decl,0)+1
        rows.append({'type':typ,'provider':prov,'namespace':c.get('namespace',''),'name':c.get('name',''),'revision':c.get('revision',''),'declared':decl,'discovered_expressions':exprs[:8],'score_total':int((lic.get('score') or {}).get('total') or 0),'source_type':sl.get('type',''),'source_provider':sl.get('provider',''),'source_namespace':sl.get('namespace',''),'source_name':sl.get('name',''),'source_revision':sl.get('revision',''),'tools':desc.get('tools') or []})
rows=rows[:limit]
def counts_obj(m): return [{'name':k,'count':v} for k,v in sorted(m.items(), key=lambda x:(-x[1],x[0]))[:80]]
obj={'schema':'license.clearlydefined.definitions.v1','source':'ClearlyDefined definitions API bounded metadata','license':'CC0-1.0 curated data','summary':{'records':len(rows),'records_total_downloaded':sum(type_counts.values()),'type_kinds':len(type_counts),'provider_kinds':len(provider_counts),'limit':limit,'pages_downloaded':manifest.get('pages_downloaded',0),'has_next_continuation_token':bool(manifest.get('next_continuation_token',''))},'policy':'bounded component license metadata only; file-level findings, attribution/copyright text bodies, notices, source archives, package artifacts, legal interpretation, compliance advice, final judgment, graph wiring excluded; final legal judgment Held','manifest':manifest,'files':files,'type_counts':counts_obj(type_counts),'provider_counts':counts_obj(provider_counts),'declared_license_counts':counts_obj(declared_counts),'definitions':rows}
out.write_text('# GENERATED by scripts/gen-license-clearlydefined-definitions.sh. Do not edit. Gitignored.\n# Source: ClearlyDefined definitions API bounded metadata only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: records={len(rows)}/{sum(type_counts.values())} bytes={out.stat().st_size}')
PY
