#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/legal/uslm-schema-catalog"
OUT="$ROOT/stdlib/lib/corpus/uslm-schema-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json, pathlib, re, sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text())
repo=json.loads((src/'raw/repo.json').read_text())
tree=json.loads((src/'raw/tree.json').read_text())

def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
paths=[]; categories={}
for item in tree.get('tree') or []:
    p=item.get('path','')
    if not p: continue
    ext='dir' if item.get('type')=='tree' else (p.rsplit('.',1)[-1].lower() if '.' in p else '')
    if item.get('type')!='blob': continue
    cat='other'
    if ext in {'xsd','dtd'}: cat='schema'
    elif ext in {'md'}: cat='guide_markdown'
    elif ext in {'pdf','docx'}: cat='guide_binary'
    elif ext in {'xml'} or 'sample' in p.lower(): cat='sample_payload_excluded'
    elif ext in {'png','jpg','gif','svg'}: cat='asset_excluded'
    categories[cat]=categories.get(cat,0)+1
    if cat in {'schema','guide_markdown','guide_binary','sample_payload_excluded'}:
        paths.append({'path':p,'category':cat,'size':item.get('size',0),'sha':item.get('sha','')})
obj={'schema':'legal.uslm_schema_catalog.v1','source':'USGPO USLM repository tree metadata','license':'US-PD/public metadata; repo license NOASSERTION; path metadata only','policy':'repository tree/path/schema-file catalog metadata only; U.S. Code statutory text, XSD/schema bodies, guide prose/PDF/DOCX bodies, sample XML bodies, legal interpretation/advice and graph wiring excluded','summary':{'repo':repo.get('full_name',''),'default_branch':repo.get('default_branch',''),'paths_stored':len(paths),'tree_items':len(tree.get('tree') or []),'categories':categories},'manifest':manifest,'repo':{'full_name':repo.get('full_name',''),'html_url':repo.get('html_url',''),'default_branch':repo.get('default_branch',''),'license_spdx':(repo.get('license') or {}).get('spdx_id','')},'paths':paths}
out.write_text('# GENERATED by scripts/gen-legal-uslm-schema-catalog.sh. Do not edit. Gitignored.\n# Source: USGPO USLM repo/tree metadata only; file bodies/statutory text excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: paths={len(paths)} bytes={out.stat().st_size}')
PY
