#!/usr/bin/env bash
set -euo pipefail
ROOT="${PNIX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
SRC="${SQLITE_SOURCE:-$ROOT/ingest/code/sqlite/sqlite-runtime-metadata.json}"
OUT="${SQLITE_OUT:-$ROOT/stdlib/lib/corpus/sqlite.generated.px}"
FUNC_LIMIT="${SQLITE_FUNCTION_LIMIT:-300}"
if [ ! -f "$SRC" ]; then
  echo "missing SQLite metadata source: $SRC" >&2
  echo "run: scripts/update-code-sqlite.sh" >&2
  exit 1
fi
mkdir -p "$(dirname "$OUT")"
python3 - "$SRC" "$OUT" "$FUNC_LIMIT" <<'PY'
import hashlib, json, sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2]); limit=int(sys.argv[3])

def q(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')+'"'

def lit(v, indent=0):
    sp=' '*indent
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if v is None: return 'null'
    if isinstance(v,str): return q(v)
    if isinstance(v,list):
        if not v: return '[ ]'
        return '[\n'+''.join(' '*(indent+2)+lit(x, indent+2)+'\n' for x in v)+sp+']'
    if isinstance(v,dict):
        if not v: return '{ }'
        lines=['{']
        for k in v:
            lines.append(' '*(indent+2)+k+' = '+lit(v[k], indent+2)+';')
        lines.append(sp+'}')
        return '\n'.join(lines)
    raise TypeError(type(v))

d=json.load(src.open())
funcs=[]
for f in d.get('functions',[])[:limit]:
    funcs.append({k.replace('-','_'):v for k,v in f.items() if k in ['name','builtin','type','narg','flags']})
value={
  'schema':'code.sqlite.metadata.v1',
  'source':'SQLite public-domain runtime metadata snapshot',
  'license':'Public-Domain',
  'source_url':'https://sqlite.org/',
  'source_sha256':hashlib.sha256(src.read_bytes()).hexdigest(),
  'sqlite_version':d.get('sqlite_version',''),
  'keywords':d.get('keywords',[]),
  'compile_options':d.get('compile_options',[]),
  'function_limit':limit,
  'total_functions_seen':len(d.get('functions',[])),
  'functions':funcs,
}
out.write_text('# GENERATED by scripts/gen-code-sqlite.sh; do not commit.\n'+lit(value)+'\n', encoding='utf-8')
print(f"generated {out}: keywords={len(value['keywords'])} functions={len(funcs)} total_functions={value['total_functions_seen']} version={value['sqlite_version']}")
PY
