#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/procurement/psc-naics-codes"
OUT="$ROOT/stdlib/lib/corpus/psc-naics-codes.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import datetime, json, os, pathlib, re, sys, zipfile, xml.etree.ElementTree as ET
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text())
ns={'a':'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}

def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))

def norm_num(s):
    if s is None: return ''
    s=str(s).strip()
    if re.fullmatch(r'\d+\.0',s): return s[:-2]
    return s

def excel_date(s):
    s=norm_num(s)
    if not s or not s.isdigit(): return ''
    n=int(s)
    if n < 20000: return ''
    return (datetime.date(1899,12,30)+datetime.timedelta(days=n)).isoformat()

def xlsx_rows(path):
    z=zipfile.ZipFile(path)
    shared=[]
    if 'xl/sharedStrings.xml' in z.namelist():
        root=ET.fromstring(z.read('xl/sharedStrings.xml'))
        for si in root.findall('a:si',ns):
            shared.append(''.join(t.text or '' for t in si.findall('.//a:t',ns)))
    sheet='xl/worksheets/sheet1.xml'
    root=ET.fromstring(z.read(sheet))
    rows=[]
    for row in root.findall('.//a:sheetData/a:row',ns):
        vals={}
        for c in row.findall('a:c',ns):
            ref=c.get('r',''); col=re.sub(r'\d+','',ref)
            t=c.get('t'); v=c.find('a:v',ns); val='' if v is None else v.text or ''
            if t=='s' and str(val).isdigit(): val=shared[int(val)]
            vals[col]=str(val).strip()
        rows.append(vals)
    return rows
psc_file=next((src/f['path'] for f in manifest.get('files',[]) if f.get('kind')=='psc_xlsx'),None)
naics_file=next((src/f['path'] for f in manifest.get('files',[]) if f.get('kind')=='naics_xlsx'),None)
psc=[]; psc_total=0
include_inactive=os.environ.get('PSC_INCLUDE_INACTIVE','0') == '1'
psc_limit=int(os.environ.get('PSC_CODE_LIMIT','2500'))
for r in xlsx_rows(psc_file)[1:]:
    code=norm_num(r.get('A',''))
    if not code: continue
    name=norm_num(r.get('B',''))
    rec={'code':code,'name':name,'start_date':excel_date(r.get('C','')),'end_date':excel_date(r.get('D','')),'active':not bool(excel_date(r.get('D','')))}
    psc_total += 1
    if (not include_inactive) and (not rec['active']): continue
    psc.append(rec)
    if psc_limit > 0 and len(psc) >= psc_limit: break
include_naics_rows=os.environ.get('PSC_NAICS_INCLUDE_NAICS_ROWS','0') == '1'
naics=[]; naics_total=0
if include_naics_rows:
    for r in xlsx_rows(naics_file)[3:]:
        code=norm_num(r.get('B',''))
        title=(r.get('C','') or '').strip()
        if not code or not title: continue
        trilateral=title.endswith('T')
        title=title[:-1].strip() if trilateral else title.strip()
        rec={'code':code,'title':title,'level':len(code),'trilateral':trilateral}
        ind=(r.get('A','') or '').strip()
        if ind: rec['change_indicator']=ind
        naics.append(rec)
        naics_total += 1
else:
    # NAICS code rows are already materialized in `procurement.census_naics.v1`.
    # Keep the source manifest and reference only; avoid duplicate 300KB+ row bloat.
    naics_total = 0
obj={'schema':'procurement.psc_naics_codes.v1','source':'Acquisition.gov PSC XLSX + U.S. Census Bureau NAICS Structure XLSX','license':'US-PD / US federal public information','policy':'PSC code-title-date metadata only; NAICS rows are referenced through existing procurement.census_naics.v1 by default; manual prose/includes/excludes/notes/full descriptions, contract award rows, business/statistical payloads, legal/procurement advice and graph wiring excluded','summary':{'psc_rows':len(psc),'psc_total_available_rows':psc_total,'psc_active_rows':sum(1 for r in psc if r.get('active')),'psc_include_inactive':include_inactive,'psc_limit':psc_limit,'naics_rows':len(naics),'naics_rows_included':include_naics_rows,'naics_reference_schema':'procurement.census_naics.v1'},'manifest':manifest,'psc_codes':psc,'naics_codes':naics,'naics_reference':{'schema':'procurement.census_naics.v1','policy':'NAICS code/title hierarchy is already stored separately; this row does not duplicate it by default.'}}
out.write_text('# GENERATED by scripts/gen-procurement-psc-naics-codes.sh. Do not edit. Gitignored.\n# Source: PSC/NAICS code-title metadata only; prose/manuals/contract/statistical payloads excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: psc={len(psc)} naics={len(naics)} bytes={out.stat().st_size}')
PY
