#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/doc-layout/page-xml-schema-catalog"
OUT="$ROOT/stdlib/lib/corpus/page-xml-schema-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import hashlib, json, pathlib, sys, xml.etree.ElementTree as ET
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
XS='{http://www.w3.org/2001/XMLSchema}'
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
def attrs(e,*names):
    return {n:e.attrib.get(n) for n in names if e.attrib.get(n) is not None}
def child_tokens(root, tag, attr='name', limit=400):
    vals=[]
    for e in root.iter(XS+tag):
        v=e.attrib.get(attr) or e.attrib.get('ref')
        if v and v not in vals:
            vals.append(v)
        if len(vals)>=limit: break
    return vals
files=[]
for p in sorted((src/'raw').rglob('*.xsd')):
    rel=str(p.relative_to(src/'raw'))
    data=p.read_bytes()
    rec={'path':rel,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()}
    try:
        root=ET.fromstring(data)
        rec.update({
            'target_namespace':root.attrib.get('targetNamespace'),
            'version':root.attrib.get('version'),
            'element_form_default':root.attrib.get('elementFormDefault'),
            'attribute_form_default':root.attrib.get('attributeFormDefault'),
            'imports':[attrs(e,'namespace','schemaLocation') for e in root.findall(XS+'import')][:80],
            'includes':[attrs(e,'schemaLocation') for e in root.findall(XS+'include')][:80],
            'elements':child_tokens(root,'element'),
            'complex_types':child_tokens(root,'complexType'),
            'simple_types':child_tokens(root,'simpleType'),
            'attributes':child_tokens(root,'attribute'),
            'groups':child_tokens(root,'group'),
            'attribute_groups':child_tokens(root,'attributeGroup'),
            'enumerations':child_tokens(root,'enumeration','value',300)
        })
    except Exception as ex:
        rec['parse_error']=str(ex)[:240]
    files.append(rec)
obj={'schema':'doc.page_xml.schema_catalog.v1','source':'PRImA PAGE-XML XSD structural metadata','license':'Apache-2.0','policy':'schema structure only; documentation prose/examples/instance XML/OCR text/image payloads/graph wiring excluded','summary':{'xsd_files':len(files),'total_bytes':sum(f['bytes'] for f in files),'parse_errors':sum(1 for f in files if 'parse_error' in f)},'manifest':manifest,'files':files}
out.write_text('# GENERATED by scripts/gen-doc-page-xml-schema-catalog.sh. Do not edit. Gitignored.\n# Source: PRImA PAGE-XML XSD structural metadata only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: files={len(files)} bytes={out.stat().st_size}')
PY
