#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${KUSTOMIZE_API_TYPES_SRC:-$ROOT/ingest/code/kustomize-api-types}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/kustomize-api-types.generated.px}"
python3 - "$SRC" "$OUT" <<'PY'
import json,re,sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return json.dumps(v,ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v[k])+';' for k in sorted(v)) + ' }'
    if v is None: return 'null'
source_files=[]; structs=[]; fields=[]; consts=[]; funcs=[]
for rec in receipt['files']:
    source_files.append({'file':rec['source_path'],'sha256':rec['sha256'],'bytes':rec['bytes']})
    text=(src/'raw'/rec['local_file']).read_text(encoding='utf-8',errors='replace')
    cur=''; depth=0
    for line in text.splitlines():
        m=re.match(r'^type\s+(\w+)\s+struct\s*\{',line)
        if m:
            cur=m.group(1); depth=1; structs.append({'file':rec['source_path'],'name':cur}); continue
        if cur:
            if '}' in line and line.strip()=='}': cur=''; depth=0; continue
            fm=re.match(r'^\s*([A-Z][A-Za-z0-9_]*)\s+([^`\n]+?)(?:\s+`([^`]+)`)?.*$',line)
            if fm:
                tag=fm.group(3) or ''
                row={'file':rec['source_path'],'struct':cur,'name':fm.group(1),'type':fm.group(2).strip(),'json_tag':'','yaml_tag':''}
                jm=re.search(r'json:"([^"]+)"',tag); ym=re.search(r'yaml:"([^"]+)"',tag)
                if jm: row['json_tag']=jm.group(1)
                if ym: row['yaml_tag']=ym.group(1)
                fields.append(row)
        cm=re.match(r'^\s*([A-Z][A-Za-z0-9_]*)\s+(?:[A-Za-z0-9_.*\[\]]+\s*)?=\s*(?:"([^"]*)"|iota|[0-9]+)',line)
        if cm: consts.append({'file':rec['source_path'],'name':cm.group(1),'string_value':cm.group(2) or ''})
        fn=re.match(r'^func\s+(?:\([^)]*\)\s*)?([A-Z][A-Za-z0-9_]*)\s*\(',line)
        if fn: funcs.append({'file':rec['source_path'],'name':fn.group(1)})
obj={'schema':'deploy.kustomize.api_types.v1','source':{'name':'Kustomize API types structural metadata','license':'Apache-2.0','source_urls':['https://github.com/kubernetes-sigs/kustomize','https://github.com/kubernetes-sigs/kustomize/tree/'+receipt.get('ref','')+'/api/types'],'receipt':receipt,'generator':'scripts/gen-code-kustomize-api-types.sh','scope':'Go model struct/tag identifiers only; source bodies/tests/real overlays/patches/manifests/cluster secrets/execution/graph wiring excluded'},'summary':{'source_file_count':len(source_files),'struct_count':len(structs),'field_count':len(fields),'const_count':len(consts),'exported_func_count':len(funcs),'source_bodies_ingested':False,'real_overlays_ingested':False,'patches_or_values_ingested':False,'rendered_manifests_ingested':False,'cluster_config_or_secrets_ingested':False,'execution_enabled':False,'mirror_graph_wiring':False},'source_files':source_files,'structs':structs,'fields':fields,'consts':consts[:300],'exported_funcs':funcs[:200]}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/update-code-kustomize-api-types.sh && scripts/gen-code-kustomize-api-types.sh; do not commit.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: structs={len(structs)} fields={len(fields)} consts={len(consts)} funcs={len(funcs)} bytes={out.stat().st_size}')
PY
