#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/code/go-spec"
OUT="$ROOT/stdlib/lib/corpus/go-spec.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def clean(s): return re.sub(r'\s+',' ',html.unescape(re.sub('<[^>]+>',' ',s))).strip()
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for name in ['spec.html','LICENSE']:
    p=src/name
    if p.exists(): files.append({'path':name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
text=(src/'spec.html').read_text(errors='ignore')
headings=[]
for m in re.finditer(r'<h([23])[^>]*(?:id="([^"]+)")?[^>]*>(.*?)</h\1>', text, re.S):
    title=clean(m.group(3))
    if title: headings.append({'level':int(m.group(1)),'id':m.group(2) or '', 'title':title})
productions=[]
for block_i,m in enumerate(re.finditer(r'<pre[^>]*class="ebnf"[^>]*>(.*?)</pre>', text, re.S)):
    raw=html.unescape(re.sub('<[^>]+>','',m.group(1))).strip()
    cur=None
    for line in raw.splitlines():
        line=line.strip()
        if not line: continue
        mm=re.match(r'^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$', line)
        if mm:
            if cur: productions.append(cur)
            cur={'lhs':mm.group(1),'rhs':mm.group(2).strip(),'block':block_i}
        elif cur:
            cur['rhs']=(cur['rhs']+' '+line).strip()
    if cur: productions.append(cur)
for p in productions:
    p['rhs']=re.sub(r'\s+',' ',p['rhs']).strip()
    p['terminal'] = p['rhs'].endswith('.')
obj={'schema':'code.go.specification.v1','source':'Go Language Specification','license':'BSD-3-Clause-style Go license','summary':{'headings':len(headings),'productions':len(productions),'ebnf_blocks':len(re.findall(r'<pre[^>]*class="ebnf"', text))},'policy':'official spec headings and EBNF grammar productions only; prose/examples/source corpora/execution/graph wiring excluded','manifest':manifest,'files':files,'headings':headings,'productions':productions}
out.write_text('# GENERATED by scripts/gen-code-go-spec.sh. Do not edit. Gitignored.\n# Source: https://go.dev/ref/spec structural headings + EBNF grammar only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: headings={len(headings)} productions={len(productions)} bytes={out.stat().st_size}')
PY
