#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/bio/gencode-release-catalog"
OUT="$ROOT/stdlib/lib/corpus/gencode-release-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import html, json, pathlib, re, sys, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text())

def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))

def clean(s): return html.unescape(re.sub(r'\s+',' ',re.sub('<[^>]+>',' ',s))).strip()
records=[]
for f in manifest.get('files',[]):
    base=f['url']; text=(src/f['path']).read_text(encoding='utf-8',errors='replace')
    for m in re.finditer(r'(?is)<a\s+[^>]*href="([^"]+)"[^>]*>(.*?)</a>', text):
        href=html.unescape(m.group(1)); label=clean(m.group(2))
        if not label or len(label)>160: continue
        if not re.search(r'release|GENCODE|Gencode|M\d+|\bv\d+\b|GRCh|GRCm', label): continue
        url=urllib.parse.urljoin(base,href)
        if any(ext in url.lower() for ext in ['.gtf','.gff','.fa','.fasta','.gz','.zip']):
            # keep link metadata only if it appears on page, never download payload.
            pass
        rel=re.search(r'(Release\s+\w+|M\d+|v\d+)', label, re.I)
        records.append({'species':f.get('kind'),'label':label,'url':url,'release_hint':rel.group(1) if rel else ''})
seen=set(); dedup=[]
for r in records:
    k=(r['species'],r['label'],r['url'])
    if k in seen: continue
    seen.add(k); dedup.append(r)
obj={'schema':'genome.gencode.release_catalog.v1','source':'GENCODE human/mouse release history metadata','license':'GENCODE open release metadata / attribution required','policy':'release/link catalog metadata only; GTF/GFF/FASTA annotation files, gene/transcript/exon rows, sequence strings, genetic design guidance and graph wiring excluded','summary':{'resources':len(dedup),'source_pages':len(manifest.get('files',[]))},'manifest':manifest,'resources':dedup}
out.write_text('# GENERATED by scripts/gen-bio-gencode-release-catalog.sh. Do not edit. Gitignored.\n# Source: GENCODE release catalog metadata only; annotation payload files excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: resources={len(dedup)} bytes={out.stat().st_size}')
PY
