#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/science/kigam-geodata-catalog"
OUT="$ROOT/stdlib/lib/corpus/kigam-geodata-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(re.sub('<.*?>',' ',str(s or '')))).strip()
def sig(txt):
    b=txt.encode() if isinstance(txt,str) else txt
    return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
pages=[]
for p in sorted(src.glob('*.html')):
    txt=p.read_text(errors='ignore')
    mt=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
    tags=sorted(set([clean(x) for x in re.findall(r'#([^<,\s]+)',txt) if clean(x)]))[:40]
    doi=''
    dm=re.search(r'10\.22747/data\.[A-Za-z0-9._/-]+',txt)
    if dm: doi=dm.group(0)
    links=[]
    for lm in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>',txt,re.I|re.S):
        href=html.unescape(lm.group(1)); label=clean(lm.group(2))[:140]
        if href and not href.startswith('#') and any(k in (href+' '+label) for k in ['data','search','guide','openapi','map','kigam']):
            links.append({'label':label,'href':urllib.parse.urljoin('https://data.kigam.re.kr/',href)})
    fields=[]
    for tr in re.findall(r'<tr[^>]*>(.*?)</tr>',txt,re.I|re.S):
        ths=re.findall(r'<th[^>]*>(.*?)</th>',tr,re.I|re.S)
        tds=re.findall(r'<td[^>]*>(.*?)</td>',tr,re.I|re.S)
        for th,td in zip(ths,tds):
            k=clean(th); v=clean(td)
            if k and v and any(key in k for key in ['자료','태그','DOI','품질','등록','수정','제공','확장자','분류','기관','유형','포맷','제목']):
                if len(v)>180: fields.append({'name':k,'value_present':True,'value_sha256':hashlib.sha256(v.encode()).hexdigest(),'value_len':len(v)})
                else: fields.append({'name':k,'value':v})
    pages.append({'page':p.stem,'file':p.name,'title':clean(mt.group(1))[:220] if mt else '', 'html_sig':sig(txt),'doi':doi,'tags':tags,'fields':fields[:80],'links':links[:80]})
coarse_datasets=[
 {'scale':'1:250000','name':'수치지질도_25만축척_전국','source_page':'geologic_250k.html','payload_policy':'SHP/ZIP/GIS rows excluded'},
 {'scale':'1:1000000','name':'한국지질도(1:1,000,000)','source_page':'geologic_1000k.html','payload_policy':'SHP/ZIP/GIS rows excluded'}
]
files=[]
for p in sorted(src.iterdir()):
    if p.is_file(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'science.kigam_geodata.catalog.v1','source':'KIGAM Geo Big Data Open Platform geodata catalog metadata','license':'KIGAM public catalog metadata; GIS payload licenses not ingested','summary':{'pages':len(pages),'coarse_datasets':len(coarse_datasets),'files':len(files)},'policy':'KIGAM public catalog/search/detail/OpenAPI guide metadata only; GIS/SHP/ZIP files, map tiles, feature geometries, coordinate/attribute payloads, report bodies, request forms, credentials, geohazard advice, and graph/mirror wiring excluded','manifest':manifest,'pages':pages,'coarse_datasets':coarse_datasets,'files':files}
out.write_text('# GENERATED by scripts/gen-science-kigam-geodata-catalog.sh. Do not edit. Gitignored.\n# Source: KIGAM Geo Big Data catalog metadata only; GIS/map payloads excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} coarse_datasets={len(coarse_datasets)} bytes={out.stat().st_size}')
PY
