#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${SPDX_LICENSE_LIST_SRC:-$ROOT/ingest/sbom/spdx-license-list}"
OUT="${SPDX_LICENSE_LIST_OUT:-$ROOT/stdlib/lib/corpus/spdx-license-list.generated.px}"
python3 - <<'PY' "$SRC" "$OUT"
import json,pathlib,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
lic=json.loads((src/'raw/licenses.json').read_text())
exc=json.loads((src/'raw/exceptions.json').read_text())
licenses=[]
for r in lic.get('licenses',[]):
    licenses.append({'id':r.get('licenseId'),'name':r.get('name'),'reference':r.get('reference'),'is_osi_approved':r.get('isOsiApproved'),'is_fsf_libre':r.get('isFsfLibre'),'is_deprecated':r.get('isDeprecatedLicenseId'),'see_also':r.get('seeAlso') or []})
exceptions=[]
for r in exc.get('exceptions',[]):
    exceptions.append({'id':r.get('licenseExceptionId'),'name':r.get('name'),'reference':r.get('reference'),'is_deprecated':r.get('isDeprecatedLicenseId'),'see_also':r.get('seeAlso') or []})
def esc(s): s='' if s is None else str(s); return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'
def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return esc(v)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))
seed={'schema':'sbom.spdx_license_list.v1','source':{'name':'SPDX License List identifier metadata','license':'CC-BY / SPDX project terms','retrieved_at_unix':receipt.get('retrieved_at_unix')},'summary':{'license_count':len(licenses),'exception_count':len(exceptions),'license_list_version':lic.get('licenseListVersion'),'release_date':lic.get('releaseDate'),'full_license_text_ingested':False,'matching_templates_ingested':False,'legal_judgment_ingested':False,'customer_sbom_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'licenses':licenses,'exceptions':exceptions}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/gen-sbom-spdx-license-list.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: licenses={len(licenses)}, exceptions={len(exceptions)}, version={lic.get("licenseListVersion")}')
PY
