#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/bio/reactome-contentservice-api-catalog"
OUT="$ROOT/stdlib/lib/corpus/reactome-contentservice-api-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json, pathlib, re, sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text())
spec=json.loads((src/manifest['files'][0]['path']).read_text())

def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,int): return str(x)
    if isinstance(x,float): return repr(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))

def collect_refs(x, acc):
    if isinstance(x, dict):
        ref=x.get('$ref')
        if isinstance(ref,str): acc.add(ref)
        for v in x.values(): collect_refs(v, acc)
    elif isinstance(x, list):
        for v in x: collect_refs(v, acc)
paths=[]
for path, methods in sorted((spec.get('paths') or {}).items()):
    if not isinstance(methods,dict): continue
    for method, op in sorted(methods.items()):
        if method.lower() not in {'get','post','put','delete','patch','head','options'}: continue
        if not isinstance(op,dict): op={}
        refs=set(); collect_refs(op.get('requestBody'), refs); collect_refs(op.get('responses'), refs)
        params=op.get('parameters') or []
        tags=op.get('tags') or []
        paths.append({'path':path,'method':method.upper(),'operation_id':op.get('operationId',''),'tags':[str(t) for t in tags], 'parameter_count':len(params), 'response_codes':sorted([str(k) for k in (op.get('responses') or {}).keys()]), 'schema_refs':sorted(refs)[:80]})
schemas=[]
components=(spec.get('components') or {}).get('schemas') or {}
for name, schema in sorted(components.items()):
    refs=set(); collect_refs(schema, refs)
    props=schema.get('properties') if isinstance(schema,dict) else None
    schemas.append({'name':name,'type':schema.get('type','') if isinstance(schema,dict) else '', 'property_count':len(props or {}), 'schema_refs':sorted(refs)[:80]})
info=spec.get('info') or {}
servers=[s.get('url','') for s in (spec.get('servers') or []) if isinstance(s,dict)]
obj={'schema':'bio.reactome.contentservice_api_catalog.v1','source':'Reactome ContentService OpenAPI endpoint/schema metadata','license':'CC-BY-4.0 / Reactome attribution required','policy':'OpenAPI route/schema-key metadata only; pathway/reaction/event payloads, graph dumps, analysis submitted identifiers/results, prose/examples, biological design guidance and graph wiring excluded','summary':{'openapi':spec.get('openapi',''),'title':info.get('title',''),'version':info.get('version',''),'paths':len(paths),'component_schemas':len(schemas)},'manifest':manifest,'info':{'title':info.get('title',''),'version':info.get('version',''),'terms_of_service':info.get('termsOfService',''),'contact_url':(info.get('contact') or {}).get('url','')},'servers':servers,'paths':paths,'component_schemas':schemas}
out.write_text('# GENERATED by scripts/gen-bio-reactome-contentservice-api-catalog.sh. Do not edit. Gitignored.\n# Source: Reactome ContentService OpenAPI route/schema metadata only; pathway payloads excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: paths={len(paths)} schemas={len(schemas)} bytes={out.stat().st_size}')
PY
