#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${JGIT_SRC:-$ROOT/ingest/vcs/jgit}"
OUT="${JGIT_OUT:-$ROOT/stdlib/lib/corpus/jgit-catalog.generated.px}"
PACKAGE_LIMIT="${JGIT_PACKAGE_LIMIT:-400}"
python3 - <<'PY' "$SRC" "$OUT" "$PACKAGE_LIMIT"
import json,pathlib,re,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); limit=int(sys.argv[3])
receipt=json.loads((src/'source-receipt.json').read_text())
tags=json.loads((src/'raw/tags.json').read_text())
tree=json.loads((src/'raw/latest-tree.json').read_text()) if (src/'raw/latest-tree.json').exists() else {'tree':[]}
def esc(s):
 s='' if s is None else str(s); return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'
def atom(v):
 if v is None: return 'null'
 if isinstance(v,bool): return 'true' if v else 'false'
 if isinstance(v,int): return str(v)
 if isinstance(v,str): return esc(v)
 if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
 if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
 raise TypeError(type(v))
tag_rows=[{'name':t.get('name'), 'commit_sha':(t.get('commit') or {}).get('sha'), 'tarball_url':t.get('tarball_url'), 'zipball_url':t.get('zipball_url'), 'pre_release_like': bool(re.search(r'-(rc|m)\d*', t.get('name',''), re.I))} for t in tags]
paths=[x.get('path','') for x in tree.get('tree',[]) if x.get('path')]
modules=sorted({p.split('/')[0] for p in paths if p.startswith('org.eclipse.jgit')})
packages=set()
for p in paths:
 if not p.endswith('.java'): continue
 parts=p.split('/')
 if 'src' in parts:
  i=parts.index('src')+1
  pkg='/'.join(parts[i:-1])
  if pkg.startswith('org/eclipse/jgit'):
   packages.add(pkg.replace('/','.'))
package_rows=[{'package':p} for p in sorted(packages)[:limit]]
seed={'schema':'vcs.jgit.catalog.v1','source':{'name':'Eclipse JGit repository catalog','license':'EDL-1.0/BSD-3-Clause','repo':receipt.get('repo'),'retrieved_at_unix':receipt.get('retrieved_at_unix')},'summary':{'tag_count':len(tag_rows),'module_count':len(modules),'package_count':len(package_rows),'package_limit':limit,'java_source_bodies_ingested':False,'vcs_operation_execution':False,'mirror_graph_wiring':False},'source_receipt':receipt,'tags':tag_rows,'modules':[{'path':m} for m in modules],'packages':package_rows}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/gen-vcs-jgit-catalog.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: tags={len(tag_rows)} modules={len(modules)} packages={len(package_rows)}')
PY
