#!/usr/bin/env bash
set -euo pipefail

# Tree-sitter node-types.json → pnix attrset source 생성.
# 각 grammar의 공개 node-types schema를 유지하되 raw grammar.js/prose는 저장하지 않는다.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IN="$ROOT/ingest/code/tree-sitter"
OUT="$ROOT/stdlib/lib/corpus/tree-sitter-grammars.generated.px"
NODE_LIMIT="${PNIX_TREE_SITTER_NODE_LIMIT:-30}"
TYPE_REF_LIMIT="${PNIX_TREE_SITTER_TYPE_REF_LIMIT:-16}"

python3 - "$IN" "$OUT" "$NODE_LIMIT" "$TYPE_REF_LIMIT" <<'PY'
import hashlib, json, pathlib, re, sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
node_limit=int(sys.argv[3]); type_ref_limit=int(sys.argv[4])
manifest=json.loads((src/'source-manifest.json').read_text(encoding='utf-8'))

def pnix(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return json.dumps(v, ensure_ascii=False).replace('${','\\${')
    if isinstance(v,list): return '[ ' + ' '.join(pnix(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {pnix(v[k])};' for k in sorted(v.keys())) + ' }'
    raise TypeError(type(v))

def type_names(obj):
    arr = obj.get('types') or []
    names=[]
    seen=set()
    for x in arr:
        name=x.get('type','')
        if name and name not in seen and len(names) < type_ref_limit:
            seen.add(name); names.append(name)
    return names

def field_names(fields):
    if not isinstance(fields, dict): return []
    return sorted(fields.keys())[:type_ref_limit]

def child_type_names(children):
    if not isinstance(children, dict): return []
    return type_names(children)

grammars=[]
for g in manifest.get('included', []):
    repo_dir=src/g['repo']
    nodes=[]; total_nodes=0; total_fields=0; total_child_refs=0; files=[]
    for nf in g.get('node_type_files', []):
        rel=nf['path']; p=repo_dir/rel
        data=json.loads(p.read_text(encoding='utf-8'))
        files.append({'path': rel, 'sha256': hashlib.sha256(p.read_bytes()).hexdigest(), 'bytes': p.stat().st_size, 'node_count': len(data)})
        total_nodes += len(data)
        for n in data[:max(0, node_limit-len(nodes))]:
            fields=field_names(n.get('fields'))
            children=child_type_names(n.get('children'))
            subtypes=type_names({'types': n.get('subtypes') or []})
            total_fields += len(fields)
            total_child_refs += len(children)
            nodes.append({'type': n.get('type',''), 'named': bool(n.get('named', False)), 'fields': fields, 'children': children, 'subtypes': subtypes})
    grammars.append({
        'language': g['language'],
        'repo': g['repo'],
        'record_schema': g['record_schema'],
        'source': {'repo_url': g['repo_url'], 'commit_sha': g['commit_sha'], 'license_id': g['license_id'], 'default_branch': g['default_branch']},
        'node_type_files': files,
        'node_types': nodes,
        'counts': {'node_types': len(nodes), 'total_node_types': total_nodes, 'fields': total_fields, 'child_type_refs': total_child_refs},
    })

payload={
    'schema':'code.tree_sitter.grammars.v1',
    'source': {'project':'Tree-sitter official grammar node-types','retrieved_at': manifest.get('retrieved_at','2026-06-19'),'license_policy': manifest.get('license_policy','')},
    'attribution':'Tree-sitter official grammar repositories; per-grammar permissive license recorded in each grammar source row.',
    'grammars': grammars,
    'skipped': manifest.get('skipped', []),
    'counts': {'grammars': len(grammars), 'skipped': len(manifest.get('skipped', [])), 'node_types': sum(g['counts']['node_types'] for g in grammars), 'total_node_types': sum(g['counts']['total_node_types'] for g in grammars)},
    'limits': {'node_types_per_grammar': node_limit, 'type_refs_per_field': type_ref_limit},
}
out.write_text('# GENERATED by scripts/gen-code-tree-sitter-grammars.sh. Do not edit.\n'+pnix(payload)+'\n',encoding='utf-8')
print('generated '+str(out)+': '+', '.join(f'{k}={v}' for k,v in payload['counts'].items()))
PY
