#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${CENSUS_TIGER_SRC:-$ROOT/ingest/place/census-tiger-geocoder}"
OUT="${CENSUS_TIGER_OUT:-$ROOT/stdlib/lib/corpus/census-tiger-geocoder-catalog.generated.px}"
python3 - <<'PY' "$SRC" "$OUT"
import json,os,pathlib,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); receipt=json.loads((src/'source-receipt.json').read_text())
def load(p): return json.loads(p.read_text())
def slim_layer(x):
    keep=['id','name','parentLayerId','defaultVisibility','subLayerIds','minScale','maxScale','type','geometryType','supportsDynamicLegends','displayField','description','copyrightText']
    return {k:x.get(k) for k in keep if k in x}
def slim_table(x):
    keep=['id','name','type','displayField','description','copyrightText']
    return {k:x.get(k) for k in keep if k in x}
def slim_service(p):
    d=load(p); name=p.name.replace('__','/').replace('.mapserver.json','')
    keep=['currentVersion','serviceDescription','mapName','description','copyrightText','supportsDynamicLayers','supportedQueryFormats','maxRecordCount','units']
    return {'service':name,'api_file':p.name,**{k:d.get(k) for k in keep if k in d},'layers':[slim_layer(x) for x in d.get('layers',[])],'tables':[slim_table(x) for x in d.get('tables',[])]}
bench_data=load(src/'raw/geocoder/benchmarks.json').get('benchmarks',[])
benchmarks=[]; excluded=[]
for b in bench_data:
    name=(b.get('benchmarkName') or '')
    row={k:b.get(k) for k in ['id','benchmarkName','benchmarkDescription','isDefault'] if k in b}
    if 'LUCA' in name.upper():
        row['excluded_reason']='LUCA benchmark excluded fail-closed (Title-13/LUCA address-source boundary)'; excluded.append(row)
    else:
        benchmarks.append(row)
vintages=[]
for p in sorted((src/'raw/geocoder').glob('vintages-*.json')):
    for v in load(p).get('vintages',[]):
        vintages.append({'api_file':p.name,**{k:v.get(k) for k in ['id','vintageName','vintageDescription','isDefault'] if k in v}})
folder_listings=[]
for p in sorted((src/'raw/tigerweb').glob('*-services.json')):
    d=load(p)
    folder_listings.append({'api_file':p.name,'folders':d.get('folders',[]),'services':d.get('services',[])})
def service_prio(p):
    n=p.name
    preferred=['tigerWMS_Current','tigerWMS_ACS2025','tigerWMS_Census2020','State_County','Tracts_Blocks','Places_CouSub_ConCity_SubMCD','Transportation','School','CBSA','Legislative','Region_Division','PUMA_TAD_TAZ_UGA_ZCTA']
    for i,s in enumerate(preferred):
        if s in n: return (0,i,n)
    return (1,0,n)
map_files=sorted((src/'raw/tigerweb').glob('*.mapserver.json'), key=service_prio)
cap=int(os.environ.get('CENSUS_TIGER_SERVICE_CAP','12'))
if cap > 0:
    map_files=map_files[:cap]
services=[slim_service(p) for p in map_files]
def esc(s): s='' if s is None else str(s); return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'
def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int) or isinstance(v,float): return str(v)
    if isinstance(v,str): return esc(v)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))
seed={'schema':'place.census_tiger_geocoder_catalog.v1','source':{'name':'U.S. Census TIGERweb + Geocoder public metadata catalog','license':'US-PD / U.S. Census Bureau public information','retrieved_at_unix':receipt.get('retrieved_at_unix')},'summary':{'service_count':len(services),'available_service_file_count':len(list((src/'raw/tigerweb').glob('*.mapserver.json'))),'service_cap':cap,'layer_count':sum(len(s.get('layers',[])) for s in services),'table_count':sum(len(s.get('tables',[])) for s in services),'benchmark_count':len(benchmarks),'vintage_count':len(vintages),'excluded_benchmark_count':len(excluded),'geometry_payloads_ingested':False,'coordinates_ingested':False,'address_queries_ingested':False,'luca_ingested':False,'mirror_graph_wiring':False},'source_receipt':receipt,'folder_listings':folder_listings,'tigerweb_services':services,'geocoder_benchmarks':benchmarks,'geocoder_vintages':vintages,'excluded_benchmarks':excluded}
out.parent.mkdir(parents=True,exist_ok=True); out.write_text('# GENERATED by scripts/gen-place-census-tiger-geocoder-catalog.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: services={len(services)}, layers={seed["summary"]["layer_count"]}, benchmarks={len(benchmarks)}, vintages={len(vintages)}, excluded_benchmarks={len(excluded)}')
PY
