#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/maritime/usace-waterborne-commerce-catalog"
OUT="$ROOT/stdlib/lib/corpus/usace-waterborne-commerce-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def sig_bytes(b): return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
search=json.loads((src/'search.json').read_text()) if (src/'search.json').exists() else {}
items=[]
for r in (search.get('items') or search.get('results') or search.get('searchResults') or [])[:80]:
    item_id=r.get('itemLink','') or r.get('item','') or r.get('itemId','') or r.get('dmrecord','') or r.get('id','')
    if isinstance(item_id,dict): item_id=item_id.get('id','')
    title=clean(r.get('title','') or r.get('title_search','') or r.get('name',''))[:240]
    items.append({
        'title': title,
        'collection_alias': r.get('collectionAlias','') or r.get('alias',''),
        'item_id': str(item_id),
        'date': clean(r.get('date','') or r.get('date_published',''))[:80],
        'creator': clean(r.get('creato','') or r.get('creator','') or r.get('organization',''))[:160],
        'item_url': r.get('itemLink','') or (('https://usace.contentdm.oclc.org/digital/api/singleitem/collection/p16021coll2/id/'+str(item_id)) if item_id else ''),
        'payload_policy': 'catalog reference only; report/PDF/statistics payload excluded'
    })
files=[]
for p in [src/'source-manifest.json',src/'search.json',src/'sample-page.html']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
page_sig={'bytes':0,'sha256':''}
if (src/'sample-page.html').exists(): page_sig=sig_bytes((src/'sample-page.html').read_bytes())
sort_fields=[]
for f in search.get('sortFields',[])[:20]:
    sort_fields.append({'name':clean(f.get('name',''))[:80],'order':f.get('order',''),'ad':f.get('ad','')})
obj={'schema':'maritime.usace_waterborne_commerce.catalog.v1','source':'USACE Waterborne Commerce catalog metadata via CONTENTdm','license':'US-PD / US federal public information','summary':{'total_results':search.get('totalResults',len(items)),'items':len(items),'sort_fields':len(sort_fields),'files':len(files)},'policy':'official catalog search result metadata only; PDF/report payloads, tonnage/statistics table values, vessel/port operational rows, port security guidance, navigation/operation decisions, and graph wiring excluded','manifest':manifest,'files':files,'sample_page_sig':page_sig,'sort_fields':sort_fields,'items':items}
out.write_text('# GENERATED by scripts/gen-maritime-usace-waterborne-commerce-catalog.sh. Do not edit. Gitignored.\n# Source: USACE Waterborne Commerce catalog metadata only; reports/statistics/security/operations excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: items={len(items)} total={obj["summary"]["total_results"]} bytes={out.stat().st_size}')
PY
