#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${IVOA_VOCAB_SRC:-$ROOT/ingest/science/ivoa-vocabularies}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/ivoa-vocabularies.generated.px}"
TERM_LIMIT="${IVOA_TERM_LIMIT:-1200}"
python3 - "$SRC" "$OUT" "$TERM_LIMIT" <<'PY'
import json, re, sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2]); term_limit=int(sys.argv[3])
receipt=json.loads((src/'source-receipt.json').read_text())

def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,(int,float)): return repr(v)
    if isinstance(v,str): return json.dumps(v, ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict):
        return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))

def local_id(s):
    s=s.strip()
    m=re.match(r'<#([^>]+)>', s)
    if m: return m.group(1)
    m=re.match(r':([A-Za-z0-9_.-]+)', s)
    if m: return m.group(1)
    return s

def objects(stmt, pred):
    out=[]
    for m in re.finditer(re.escape(pred)+r'\s+([^.;]+)', stmt):
        chunk=m.group(1)
        for x in re.findall(r'<#([^>]+)>|:([A-Za-z0-9_.-]+)', chunk):
            out.append(x[0] or x[1])
    return out

def literal(stmt, pred):
    m=re.search(re.escape(pred)+r'\s+"([^"\\]*(?:\\.[^"\\]*)*)"(?:@[A-Za-z-]+)?', stmt)
    if not m: return None
    return bytes(m.group(1), 'utf-8').decode('unicode_escape')

def statements(txt):
    acc=[]
    in_triple=False
    for line in txt.splitlines():
        if not line or line.startswith('@prefix') or line.startswith('@base'):
            continue
        acc.append(line)
        if line.rstrip().endswith('.') and line.count('"""') % 2 == 0:
            yield '\n'.join(acc)
            acc=[]
    if acc: yield '\n'.join(acc)

vocabularies=[]; terms=[]; total_term_count=0
for f in receipt['files']:
    txt=(src/f['path']).read_text(errors='replace')
    vocab={'id':f['id'], 'title':f.get('title',''), 'status':f.get('status',''), 'date':f.get('date',''), 'url':f.get('url',''), 'sha256':f.get('sha256',''), 'size_bytes':f.get('size_bytes',0)}
    for stmt in statements(txt):
        if stmt.lstrip().startswith('<>'):
            lab=literal(stmt, 'rdfs:label') or literal(stmt, 'dc:title')
            created=literal(stmt, 'dc:created')
            if lab: vocab['label']=lab
            if created: vocab['created']=created
            vocab['license_cc0']='creativecommons.org/publicdomain/zero/1.0' in stmt
            continue
        if not stmt.lstrip().startswith('<#'):
            continue
        sid=local_id(stmt.lstrip().split(None,1)[0])
        if not sid:
            continue
        is_term=any(k in stmt for k in ['skos:Concept','rdfs:Class','owl:Class'])
        if not is_term:
            continue
        typ=[]
        if 'skos:Concept' in stmt: typ.append('skos:Concept')
        if 'rdfs:Class' in stmt: typ.append('rdfs:Class')
        if 'owl:Class' in stmt: typ.append('owl:Class')
        label=literal(stmt,'skos:prefLabel') or literal(stmt,'rdfs:label') or sid
        term={'vocabulary':f['id'], 'id':sid, 'label':label, 'types':typ}
        br=objects(stmt,'skos:broader')
        if br: term['broader']=br
        rel=objects(stmt,'skos:related')
        if rel: term['related']=rel
        exact=objects(stmt,'skos:exactMatch')
        if exact: term['exact_match_local']=exact
        if 'ivoasem:preliminary' in stmt: term['preliminary']=True
        if 'owl:deprecated true' in stmt or 'owl:deprecated "true"' in stmt: term['deprecated']=True
        total_term_count += 1
        if term_limit <= 0 or len(terms) < term_limit:
            terms.append(term)
    vocabularies.append(vocab)
seed={
  'schema':'astro.ivoa_vocabularies.v1',
  'source':{'name':'IVOA Vocabularies','license':'CC0-1.0','url':receipt.get('index_url'),'retrieved_at':receipt.get('retrieved_at')},
  'summary':{'vocabulary_count':len(vocabularies),'term_count':len(terms),'total_available_term_count':total_term_count,'term_limit':term_limit,'definition_prose_ingested':False,'description_prose_ingested':False,'examples_ingested':False,'mirror_graph_wiring':False},
  'source_receipt':receipt,
  'vocabularies':vocabularies,
  'terms':terms,
}
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('# GENERATED by scripts/gen-science-ivoa-vocabularies.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: vocabularies={len(vocabularies)}, terms={len(terms)}')
PY
