#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/web/whatwg-mime-url"
OUT="$ROOT/stdlib/lib/corpus/whatwg-mime-url.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import json,pathlib,re,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,(int,float)): return str(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
def parse_doc(name, path):
    txt=path.read_text(encoding='utf-8',errors='replace')
    headings=[]; dfns=[]; idl=[]; code_markers=[]
    for m in re.finditer(r'^(#{1,6})\s+(.+)$',txt,re.M):
        title=re.sub(r'<[^>]+>|[`*_#]','',m.group(2)).strip()[:180]
        if title: headings.append({'spec':name,'level':len(m.group(1)),'title':title})
    for m in re.finditer(r'<dfn\b([^>]*)>(.*?)</dfn>',txt,re.I|re.S):
        attrs=m.group(1); body=re.sub(r'<[^>]+>','',m.group(2)).strip()[:120]
        im=re.search(r'\bid=["\']([^"\']+)',attrs)
        ex=re.search(r'\bexport\b',attrs)
        dfns.append({'spec':name,'id':im.group(1) if im else None,'term':body,'exported':bool(ex)})
    for m in re.finditer(r'<pre\s+class=["\']idl["\'][^>]*>(.*?)</pre>',txt,re.I|re.S):
        block=m.group(1)
        names=re.findall(r'\b(?:interface|dictionary|enum|typedef|callback)\s+([A-Za-z][A-Za-z0-9_]*)',block)
        idl.append({'spec':name,'names':sorted(set(names))})
    for m in re.finditer(r'<pre\s+class=["\']([^"\']+)["\']',txt,re.I):
        cls=m.group(1)
        if cls != 'idl': code_markers.append({'spec':name,'class':cls})
    return {'file':path.name,'bytes':path.stat().st_size,'headings':headings,'dfns':dfns[:1200],'idl_blocks':idl,'code_markers':code_markers[:500]}
docs=[parse_doc('url',src/'url.bs'), parse_doc('mimesniff',src/'mimesniff.bs')]
obj={'schema':'web.whatwg.mime_url_metadata.v1','source':'WHATWG URL and MIME Sniffing structural metadata','license':'CC-BY-4.0 / BSD-3-Clause','summary':{'documents':len(docs),'headings':sum(len(d['headings']) for d in docs),'dfns':sum(len(d['dfns']) for d in docs),'idl_blocks':sum(len(d['idl_blocks']) for d in docs),'code_markers':sum(len(d['code_markers']) for d in docs)},'policy':'Bikeshed structural identifiers only; algorithm prose, examples, conformance narrative, runtime parsing/sniffing, browser/user payloads, and graph wiring excluded','manifest':manifest,'documents':docs}
out.write_text('# GENERATED by scripts/gen-web-whatwg-mime-url.sh. Do not edit. Gitignored.\n# Source: WHATWG URL/MIME Sniffing structural metadata only.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: docs={len(docs)} bytes={out.stat().st_size}')
PY
