#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/ml/openml-api-schema"
OUT="$ROOT/stdlib/lib/corpus/openml-api-schema.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def typ(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'bool'
    if isinstance(v,int): return 'int'
    if isinstance(v,float): return 'float'
    if isinstance(v,str): return 'string'
    if isinstance(v,list): return 'list'
    if isinstance(v,dict): return 'object'
    return type(v).__name__
def walk(v,path,out):
    out.setdefault(path or '$',set()).add(typ(v))
    if isinstance(v,dict):
        for k,val in v.items(): walk(val,(path+'.' if path else '')+str(k),out)
    elif isinstance(v,list):
        out.setdefault((path or '$')+'[]',set()).add('item')
        for item in v[:4]: walk(item,(path or '$')+'[]',out)
def row_count(j):
    # first list below root is response row slice
    best=0
    def rec(v):
        nonlocal best
        if isinstance(v,list):
            best=max(best,len(v))
            for x in v[:1]: rec(x)
        elif isinstance(v,dict):
            for x in v.values(): rec(x)
    rec(j); return best
manifest={}
if (src/'source-manifest.json').exists(): manifest=json.loads((src/'source-manifest.json').read_text())
files=[]
for p in [src/'source-manifest.json']+sorted(src.glob('*_list.json')):
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
endpoints=[]; total_paths=0
for p in sorted(src.glob('*_list.json')):
    j=json.loads(p.read_text())
    paths={}
    walk(j,'',paths)
    key_rows=[{'path':k,'types':sorted(v)} for k,v in sorted(paths.items())]
    total_paths+=len(key_rows)
    endpoints.append({'name':p.stem,'response_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'response_bytes':p.stat().st_size,'row_count_observed':row_count(j),'key_paths':key_rows})
obj={'schema':'ml.openml.api_schema.v1','source':'OpenML API bounded schema inventory','license':'CC-BY / OpenML public metadata','summary':{'endpoints':len(endpoints),'key_paths':total_paths,'limit':manifest.get('limit',0)},'policy':'API schema key/type inventory only; dataset contents, feature values, quality values, task/run/study values, user/person values, names/descriptions/prose, API harvest values, model artifacts, leaderboard/evaluation judgments, graph wiring excluded','manifest':manifest,'files':files,'endpoints':endpoints}
out.write_text('# GENERATED by scripts/gen-ml-openml-api-schema.sh. Do not edit. Gitignored.\n# Source: OpenML API bounded schema/key inventory only; values excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: endpoints={len(endpoints)} key_paths={total_paths} bytes={out.stat().st_size}')
PY
