#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/science/kasa-spaceweather-api-catalog"
OUT="$ROOT/stdlib/lib/corpus/kasa-spaceweather-api-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html, urllib.parse
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(re.sub('<.*?>',' ',str(s or '')))).strip()
def sig(txt):
    b=txt.encode() if isinstance(txt,str) else txt
    return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
list_txt=(src/'openapi-list.html').read_text(errors='ignore') if (src/'openapi-list.html').exists() else ''
items=[]
for m in re.finditer(r"fnDetail\('([^']+)'\).*?class=\"titleLink\">(.*?)</a>\s*</div>\s*<p>(.*?)</p>", list_txt, re.S):
    code,title,desc=m.group(1),clean(m.group(2)),clean(m.group(3))
    items.append({'api_cd':code,'title':title,'description_present':bool(desc),'description_sha256':hashlib.sha256(desc.encode()).hexdigest() if desc else ''})
by_code={x['api_cd']:x for x in items}
api_pages=[]
for p in sorted(src.glob('API*.html')):
    txt=p.read_text(errors='ignore')
    code=p.stem
    title=by_code.get(code,{}).get('title','')
    if not title:
        mt=re.search(r'<h4[^>]*>(.*?)</h4>',txt,re.I|re.S)
        title=clean(mt.group(1)) if mt else code
    fields=[]
    for tr in re.findall(r'<tr[^>]*>(.*?)</tr>',txt,re.I|re.S):
        ths=re.findall(r'<th[^>]*>(.*?)</th>',tr,re.I|re.S)
        tds=re.findall(r'<td[^>]*>(.*?)</td>',tr,re.I|re.S)
        if ths and tds:
            for th,td in zip(ths,tds):
                k=clean(th); v=clean(td)
                if k and v:
                    # short table metadata only; long prose values are hashed, not copied.
                    if len(v)>220:
                        fields.append({'name':k,'value_present':True,'value_sha256':hashlib.sha256(v.encode()).hexdigest(),'value_len':len(v)})
                    else:
                        fields.append({'name':k,'value':v})
    links=[]
    for lm in re.finditer(r'<a\s+[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>',txt,re.I|re.S):
        href=html.unescape(lm.group(1)); label=clean(lm.group(2))[:140]
        if href and not href.startswith('#') and any(k in (href+' '+label) for k in ['api','openApi','dataset','data.go.kr','spaceweather']):
            links.append({'label':label,'href':urllib.parse.urljoin('https://spaceweather.kasa.go.kr/',href)})
    tags=sorted(set([clean(x) for x in re.findall(r'#([^<,\s]+)',txt) if clean(x)]))
    api_pages.append({'api_cd':code,'title':title,'detail_file':p.name,'html_sig':sig(txt),'fields':fields[:80],'tags':tags[:20],'links':links[:80]})
files=[]
for p in sorted(src.iterdir()):
    if p.is_file(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
obj={'schema':'science.kasa_spaceweather.api_catalog.v1','source':'KASA Korea Space Weather Center Open API catalog metadata','license':'KASA public Open API catalog metadata; payload licenses not ingested','summary':{'apis':len(api_pages),'list_items':len(items),'files':len(files)},'policy':'KASA/KSWC Open API list/detail metadata only; real-time observations, forecast/warning payloads, API response values, credentials, prose bodies/examples, life-safety guidance, and graph/mirror wiring excluded','manifest':manifest,'list_page':{'file':'openapi-list.html','html_sig':sig(list_txt),'items':items},'api_pages':api_pages,'files':files}
out.write_text('# GENERATED by scripts/gen-science-kasa-spaceweather-api-catalog.sh. Do not edit. Gitignored.\n# Source: KASA/KSWC Open API catalog metadata only; payloads/life-safety guidance excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: apis={len(api_pages)} bytes={out.stat().st_size}')
PY
