#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/regulatory/govinfo-api"
OUT="$ROOT/stdlib/lib/corpus/govinfo-api.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import pathlib, sys, json, hashlib, re, html
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
def esc(s): return '"'+str(s).replace('\\','\\\\').replace('"','\\"').replace('$','DOLLAR_SIGN').replace('\n',' ').replace('\r','')+'"'
def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {lit(val)};' for k,val in v.items()) + ' }'
    return esc('' if v is None else v)
def clean(s): return re.sub(r'\s+',' ',html.unescape(str(s or ''))).strip()
def sig(s):
    t=clean(s)
    return {'bytes':len(t.encode()),'sha256':hashlib.sha256(t.encode()).hexdigest()} if t else {'bytes':0,'sha256':''}
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
repo=json.loads((src/'github-repo.json').read_text()) if (src/'github-repo.json').exists() else {}
pages=[]
for name,page_id in [('api-docs.html','api_docs'),('feature-api.html','feature_api')]:
    p=src/name
    if p.exists():
        txt=p.read_text(errors='ignore')
        mt=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
        pages.append({'page':page_id,'file':name,'title':clean(re.sub('<.*?>',' ',mt.group(1)))[:180] if mt else '', 'html_sig':sig(txt)})
endpoints=[
    {'name':'collections','method':'GET','path':'/collections','requires_api_key':True,'payload_policy':'metadata listing only; no package payload stored'},
    {'name':'packages','method':'GET','path':'/packages/{packageId}/summary','requires_api_key':True,'payload_policy':'not called by ingest; package summary payload excluded'},
    {'name':'granules','method':'GET','path':'/packages/{packageId}/granules','requires_api_key':True,'payload_policy':'not called by ingest; granule payload excluded'},
    {'name':'related','method':'GET','path':'/related/{packageId}','requires_api_key':True,'payload_policy':'not called by ingest; relation payload excluded'},
    {'name':'published','method':'GET','path':'/published/{date}','requires_api_key':True,'payload_policy':'not called by ingest; publication payload excluded'},
    {'name':'search','method':'POST','path':'/search','requires_api_key':True,'payload_policy':'not called by ingest; result payload excluded'}
]
files=[]
for p in [src/'source-manifest.json',src/'api-docs.html',src/'feature-api.html',src/'github-repo.json']:
    if p.exists(): files.append({'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
repo_meta={'full_name':repo.get('full_name',''),'html_url':repo.get('html_url',''),'license_key':(repo.get('license') or {}).get('key',''),'default_branch':repo.get('default_branch',''),'updated_at':repo.get('updated_at','')}
obj={'schema':'regulatory.govinfo.api_schema.v1','source':'GovInfo API documentation/endpoint metadata','license':'US-PD / US federal public information','summary':{'endpoints':len(endpoints),'pages':len(pages),'files':len(files),'requires_api_key':True},'policy':'documentation shell and endpoint catalog tokens only; package/granule/document payloads, full text, MODS/PREMIS, API keys, legal advice, official-version judgment, and graph wiring excluded','manifest':manifest,'files':files,'repo_meta':repo_meta,'pages':pages,'endpoints':endpoints}
out.write_text('# GENERATED by scripts/gen-regulatory-govinfo-api.sh. Do not edit. Gitignored.\n# Source: GovInfo API documentation metadata only; live package/document payloads excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: endpoints={len(endpoints)} pages={len(pages)} bytes={out.stat().st_size}')
PY
