#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${OM_SRC:-$ROOT/ingest/units/om}"
OUT="${OM_OUT:-$ROOT/stdlib/lib/corpus/om-ontology.generated.px}"
LIMIT="${OM_RECORD_LIMIT:-300}"
python3 - <<'PY' "$SRC" "$OUT" "$LIMIT"
import json, pathlib, sys, xml.etree.ElementTree as ET
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); limit=int(sys.argv[3])
receipt=json.loads((src/'source-receipt.json').read_text())
rdf_path=src/'raw/om-2.0.rdf'
RDF='{http://www.w3.org/1999/02/22-rdf-syntax-ns#}'
NS={
 'rdf':'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
 'rdfs':'http://www.w3.org/2000/01/rdf-schema#',
 'owl':'http://www.w3.org/2002/07/owl#',
 'om':'http://www.ontology-of-units-of-measure.org/resource/om-2/',
 'skos':'http://www.w3.org/2004/02/skos/core#',
 'dc':'http://purl.org/dc/elements/1.1/',
 'dcterms':'http://purl.org/dc/terms/',
}
URI_TO_PREFIX={v:k for k,v in NS.items()}
PROSE={'comment','description','definition','example','editorialNote','scopeNote','historyNote','note','abstract'}

def qname(tag):
    if tag.startswith('{'):
        uri,local=tag[1:].split('}',1)
        return URI_TO_PREFIX.get(uri, uri)+'/'+local if uri not in URI_TO_PREFIX else URI_TO_PREFIX[uri]+':'+local
    return tag

def local_from_uri(u):
    if not u: return None
    for sep in ['#','/']:
        if sep in u: u=u.rsplit(sep,1)[-1]
    return u

def esc(s):
    s='' if s is None else str(s)
    return '"'+s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')+'"'
def atom(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return esc(v)
    if isinstance(v,list): return '[ ' + ' '.join(atom(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(f'{k} = {atom(v[k])};' for k in sorted(v)) + ' }'
    raise TypeError(type(v))

tree=ET.parse(rdf_path); root=tree.getroot()
rows=[]; total_subjects=0; skipped_prose=0; predicate_counts={}
for child in list(root):
    uri=child.attrib.get(RDF+'about') or child.attrib.get(RDF+'ID') or child.attrib.get(RDF+'nodeID')
    if not uri: continue
    total_subjects += 1
    row={'uri':uri, 'local_id':local_from_uri(uri), 'element_type':qname(child.tag), 'types':[], 'properties':[]}
    if qname(child.tag) != 'rdf:Description':
        row['types'].append(qname(child.tag))
    for c in list(child):
        pred=qname(c.tag); local=pred.split(':')[-1].split('/')[-1]
        if local in PROSE:
            skipped_prose += 1
            continue
        if pred == 'rdf:type':
            obj=c.attrib.get(RDF+'resource')
            if obj: row['types'].append(obj)
            continue
        item={'predicate':pred}
        lang=c.attrib.get('{http://www.w3.org/XML/1998/namespace}lang')
        obj=c.attrib.get(RDF+'resource')
        if obj:
            item['object_uri']=obj; item['object_local_id']=local_from_uri(obj)
        else:
            txt=(c.text or '').strip()
            if not txt:
                continue
            item['literal']=txt
            if lang: item['lang']=lang
        row['properties'].append(item)
        predicate_counts[pred]=predicate_counts.get(pred,0)+1
    if row['types'] or row['properties']:
        rows.append(row)
rows=rows[:limit]
seed={
 'schema':'units.om.ontology.v1',
 'source':{'name':'OM — Ontology of units of Measure', 'license':'CC-BY-4.0', 'url':receipt.get('url'), 'retrieved_at_unix':receipt.get('retrieved_at_unix')},
 'summary':{'record_count':len(rows), 'record_limit':limit, 'total_subjects_seen':total_subjects, 'prose_properties_skipped':skipped_prose, 'ucum_mapping_ingested':False, 'mirror_graph_wiring':False},
 'source_receipt':receipt,
 'predicate_counts_sample':[{'predicate':k, 'count':v} for k,v in sorted(predicate_counts.items())[:200]],
 'records':rows,
}
out.parent.mkdir(parents=True,exist_ok=True)
out.write_text('# GENERATED by scripts/gen-units-om.sh; do not commit.\n'+atom(seed)+'\n')
print(f'generated {out}: records={len(rows)} total_subjects={total_subjects} skipped_prose={skipped_prose}')
PY
