#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/ingest/security/nist-cmvp-cavp-catalog"
OUT="$ROOT/stdlib/lib/corpus/nist-cmvp-cavp-catalog.generated.px"
python3 - "$SRC" "$OUT" <<'PY'
import html,json,pathlib,re,sys
src=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2])
manifest=json.loads((src/'source-manifest.json').read_text()) if (src/'source-manifest.json').exists() else {}
def lit(x):
    if x is None: return 'null'
    if x is True: return 'true'
    if x is False: return 'false'
    if isinstance(x,(int,float)): return str(x)
    if isinstance(x,str): return json.dumps(x,ensure_ascii=False)
    if isinstance(x,list): return '[ ' + ' '.join(lit(v) for v in x) + ' ]'
    if isinstance(x,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v)+';' for k,v in sorted(x.items())) + ' }'
    raise TypeError(type(x))
def clean(s):
    s=html.unescape(re.sub(r'<[^>]+>',' ',s))
    return re.sub(r'\s+',' ',s).strip()
urlmap={}
if (src/'urls.tsv').exists():
    for line in (src/'urls.tsv').read_text().splitlines():
        f,u=line.split('\t',1); urlmap[f]=u
pages=[]
for p in sorted(src.glob('page-*.html')):
    txt=p.read_text(encoding='utf-8',errors='replace')
    title=''
    m=re.search(r'<title[^>]*>(.*?)</title>',txt,re.I|re.S)
    if m: title=clean(m.group(1))[:180]
    links=[]
    for href in re.findall(r'href=["\']([^"\']+)["\']',txt,re.I):
        low=href.lower()
        if any(t in low for t in ['cryptographic', 'validation', 'cmvp', 'cavp', 'fips', 'acvp', 'module']):
            links.append(href[:260])
    forms=[]
    for name in re.findall(r'<(?:input|select|textarea)\b[^>]*\bname=["\']([^"\']+)',txt,re.I):
        if not re.search(r'(token|csrf|auth|password|email)',name,re.I):
            forms.append(name[:120])
    endpoints=[]
    for m in re.findall(r'["\']([^"\']*(?:CMVP|CAVP|Validation|Validated|Module|Algorithm)[^"\']*)["\']',txt,re.I):
        if len(m) < 240 and not m.startswith('<'):
            endpoints.append(m)
    pages.append({'file':p.name,'url':urlmap.get(p.name),'title':title,'bytes':p.stat().st_size,'links':sorted(set(links))[:80],'form_fields':sorted(set(forms))[:80],'endpoint_hints':sorted(set(endpoints))[:80]})
obj={'schema':'security.nist_cmvp_cavp.catalog.v1','source':'NIST CMVP/CAVP catalog metadata','license':'US-PD / NIST public information','summary':{'pages':len(pages),'links':sum(len(x['links']) for x in pages),'form_fields':sum(len(x['form_fields']) for x in pages),'endpoint_hints':sum(len(x['endpoint_hints']) for x in pages)},'policy':'official NIST CSRC catalog metadata only; certificate/module/vendor rows, algorithm validation values, test vectors, security-level/compliance judgments, security advice, and graph wiring excluded','manifest':manifest,'pages':pages,'accepted_truth':False}
out.write_text('# GENERATED by scripts/gen-security-nist-cmvp-cavp-catalog.sh. Do not edit. Gitignored.\n# Source: NIST CMVP/CAVP catalog metadata only; cert rows/security judgments excluded.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: pages={len(pages)} bytes={out.stat().st_size}')
PY
