#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${OCI_RUNTIME_SPEC_SRC:-$ROOT/ingest/code/oci-runtime-spec}"
OUT="${OUT:-$ROOT/stdlib/lib/corpus/oci-runtime-spec.generated.px}"
python3 - "$SRC" "$OUT" <<'PY'
import json, os, sys
from pathlib import Path
src=Path(sys.argv[1]); out=Path(sys.argv[2])
receipt=json.loads((src/'source-receipt.json').read_text())

def lit(v):
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,int): return str(v)
    if isinstance(v,str): return json.dumps(v,ensure_ascii=False)
    if isinstance(v,list): return '[ ' + ' '.join(lit(x) for x in v) + ' ]'
    if isinstance(v,dict): return '{ ' + ' '.join(json.dumps(str(k),ensure_ascii=False)+' = '+lit(v[k])+';' for k in sorted(v)) + ' }'
    if v is None: return 'null'
    raise TypeError(type(v))

schema_files=[]; definitions=[]; properties=[]; required=[]; refs=[]; enums=[]

def walk(node, file, path):
    if isinstance(node,dict):
        if '$ref' in node:
            refs.append({'file':file,'path':path,'ref':node['$ref']})
        if 'enum' in node and isinstance(node['enum'],list):
            for x in node['enum'][:80]:
                if isinstance(x,(str,int,bool)):
                    enums.append({'file':file,'path':path,'value':str(x)})
        if 'required' in node and isinstance(node['required'],list):
            for x in node['required']:
                if isinstance(x,str): required.append({'file':file,'path':path,'field':x})
        defs=node.get('definitions') or node.get('$defs') or {}
        if isinstance(defs,dict):
            for name,val in sorted(defs.items()):
                definitions.append({'file':file,'name':name,'type':val.get('type','') if isinstance(val,dict) else ''})
        props=node.get('properties')
        if isinstance(props,dict):
            for name,val in sorted(props.items()):
                p=(path+'.'+name).strip('.')
                row={'file':file,'path':p,'name':name}
                if isinstance(val,dict):
                    row['type']=val.get('type','') if isinstance(val.get('type',''),str) else ''
                    row['ref']=val.get('$ref','')
                properties.append(row)
                walk(val,file,p)
        for k,v in node.items():
            if k in ('properties','definitions','$defs','description','examples','title'):
                continue
            walk(v,file,path)
    elif isinstance(node,list):
        for v in node: walk(v,file,path)

for rec in receipt['files']:
    file=rec['file']
    data=json.loads((src/'raw'/file).read_text())
    schema_files.append({'file':file,'id':data.get('$id',''),'schema':data.get('$schema',''),'title':data.get('title',''),'root_type':data.get('type',''),'sha256':rec['sha256'],'bytes':rec['bytes']})
    walk(data,file,'')
obj={'schema':'container.oci.runtime_spec.v1','source':{'name':'OCI Runtime Specification official JSON schemas','license':'Apache-2.0','source_urls':['https://github.com/opencontainers/runtime-spec','https://github.com/opencontainers/runtime-spec/tree/'+receipt.get('ref','')+'/schema'],'receipt':receipt,'generator':'scripts/gen-code-oci-runtime-spec.sh','scope':'official JSON Schema structure only; real runtime configs/state/host paths/devices/env/hooks/execution/mutation/graph wiring excluded'},'summary':{'schema_file_count':len(schema_files),'definition_count':len(definitions),'property_count':len(properties),'required_count':len(required),'ref_count':len(refs),'enum_count':len(enums),'real_runtime_configs_ingested':False,'host_paths_or_devices_ingested':False,'credentials_or_hooks_ingested':False,'runtime_execution_or_mutation_enabled':False,'mirror_graph_wiring':False},'schema_files':schema_files,'definitions':definitions,'properties':properties[:1200],'required_fields':required,'refs':refs[:800],'enums':enums[:500]}
out.parent.mkdir(parents=True,exist_ok=True)
out.write_text('# GENERATED by scripts/update-code-oci-runtime-spec.sh && scripts/gen-code-oci-runtime-spec.sh; do not commit.\n'+lit(obj)+'\n',encoding='utf-8')
print(f'generated {out}: files={len(schema_files)} definitions={len(definitions)} properties={len(properties)} refs={len(refs)} enums={len(enums)} bytes={out.stat().st_size}')
PY
