#!/usr/bin/env bash
set -euo pipefail
ROOT="${PNIX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
OUT_DIR="$ROOT/ingest/doc/tika"
VERSION="${TIKA_VERSION:-3.3.1}"
BASE="https://repo1.maven.org/maven2/org/apache/tika/tika-parsers-standard-package/$VERSION"
URL="${TIKA_URL:-$BASE/tika-parsers-standard-package-$VERSION.jar}"
JAR="$OUT_DIR/tika-parsers-standard-package-$VERSION.jar"
TMP="$JAR.tmp.$$"
mkdir -p "$OUT_DIR/unpacked"
echo "download: $URL"
curl -fL --retry 3 --retry-delay 2 "$URL" -o "$TMP"
mv "$TMP" "$JAR"
shasum -a 256 "$JAR" > "$JAR.sha256"
rm -rf "$OUT_DIR/unpacked" && mkdir -p "$OUT_DIR/unpacked"
unzip -q "$JAR" -d "$OUT_DIR/unpacked"
{
  echo "source_url=$URL"
  echo "version=$VERSION"
  echo "retrieved_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "sha256=$(cut -d' ' -f1 "$JAR.sha256")"
} > "$JAR.meta"
echo "wrote: $JAR"
cat "$JAR.sha256"
