[package]
name = "pnix-query-runtime"
version.workspace = true
edition = "2021"
description = "Standalone pnix ontology REPL kernel"
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "pnix-query-repl"
path = "src/bin/pnix-query-repl.rs"

[[bin]]
name = "pnix-query-px-eval"
path = "src/bin/pnix-query-px-eval.rs"

[dependencies]
anyhow.workspace = true
pnix-core = { path = "../pnix-core" }
pnix-eval = { path = "../pnix-eval" }
