//! Self-hosting Codegen: MetaFx → Rust Source 생성
//!
//! Meta-circular Stage 2: pnix로 pnix의 meta 계층을 생성
//!
//! 규칙:
//! - 타입 정의만 생성 (인스턴스 데이터 ❌)
//! - std + serde만 의존
//! - core 타입 참조 ❌
//! - lowering / verify 호출 ❌

/// Self-hosting용 Rust 소스 생성: MetaFx IR 타입 정의를 Rust 소스 코드로 생성
///
/// meta_ir_gen.rs용으로 사용되며, MetaFxModule, MetaFxInput 등의 구조체 정의를 생성합니다.
///
/// ## 헌법 준수 (P0-1, C1)
///
/// 텍스트 생성만, 파일 I/O 없음
pub fn generate_meta_ir_source() -> String {
  let mut out = String::new();

  // 헤더
  out.push_str(HEADER);
  out.push('\n');

  // imports
  out.push_str("use serde::{Deserialize, Serialize};\n");
  out.push('\n');

  // MetaFxModule
  out.push_str(&generate_meta_fx_module_struct());
  out.push('\n');

  // MetaFxInput
  out.push_str(&generate_meta_fx_input_struct());
  out.push('\n');

  // MetaFxMorphismPort
  out.push_str(&generate_meta_fx_morphism_port_struct());
  out.push('\n');

  // MetaFxMorphism
  out.push_str(&generate_meta_fx_morphism_struct());
  out.push('\n');

  // MetaExecutionContract
  out.push_str(&generate_meta_execution_contract_struct());
  out.push('\n');

  // MetaFxNode
  out.push_str(&generate_meta_fx_node_struct());
  out.push('\n');

  // MetaFxPortInfo
  out.push_str(&generate_meta_fx_port_info_struct());
  out.push('\n');

  // MetaFxEdge
  out.push_str(&generate_meta_fx_edge_struct());
  out.push('\n');

  // MetaFxScope
  out.push_str(&generate_meta_fx_scope_struct());
  out.push('\n');

  // MetaFxStats
  out.push_str(&generate_meta_fx_stats_struct());

  out
}

const HEADER: &str = r#"// ============================================================
//  AUTO-GENERATED BY pnix (Stage 2: Partial Self-Hosting)
//  SOURCE OF TRUTH: pnix DSL
//  DO NOT EDIT MANUALLY
// ============================================================
"#;

fn generate_meta_fx_module_struct() -> String {
  r#"/// MetaFx 모듈: FxCore의 구조적 자기 기술 (Generated)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct MetaFxModule {
    pub name: String,
    pub stage: u8,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub replay_hash: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub types: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub inputs: Vec<MetaFxInput>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub morphisms: Vec<MetaFxMorphism>,
    pub nodes: Vec<MetaFxNode>,
    pub edges: Vec<MetaFxEdge>,
    pub scopes: Vec<MetaFxScope>,
    pub stats: MetaFxStats,
}
"#
  .to_string()
}

fn generate_meta_fx_input_struct() -> String {
  r#"/// MetaFx 입력: Stage-2 입력 선언 (Generated)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct MetaFxInput {
    pub name: String,
    pub ty: String,
}
"#
  .to_string()
}

fn generate_meta_fx_morphism_port_struct() -> String {
  r#"/// MetaFx 포트: morphism 입출력 포트 (Generated)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct MetaFxMorphismPort {
    pub name: String,
    pub ty: String,
}
"#
  .to_string()
}

fn generate_meta_fx_morphism_struct() -> String {
  r#"/// MetaFx Morphism: extern 선언의 구조적 기술 (Generated)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct MetaFxMorphism {
    pub name: String,
    pub input: String,
    pub output: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub inputs: Vec<MetaFxMorphismPort>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub outputs: Vec<MetaFxMorphismPort>,
    pub effect: String,
}
"#
  .to_string()
}

fn generate_meta_execution_contract_struct() -> String {
  r#"/// MetaFx 실행 계약 (Generated)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct MetaExecutionContract {
    pub required_inputs: Vec<String>,
    pub may_skip: bool,
    pub skip_policy: String,
}
"#
  .to_string()
}

fn generate_meta_fx_node_struct() -> String {
  r#"/// MetaFx 노드: 노드의 구조적 기술 (Generated)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct MetaFxNode {
    pub name: String,
    pub uses: String,
    pub kind: String,
    pub optional: bool,
    pub scope: String,
    pub cost: String,
    pub priority: i32,
    pub contract: MetaExecutionContract,
}
"#
  .to_string()
}

fn generate_meta_fx_port_info_struct() -> String {
  r#"/// MetaFx 포트 정보 (Generated)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct MetaFxPortInfo {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from_port: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub to_port: Option<String>,
}
"#
  .to_string()
}

fn generate_meta_fx_edge_struct() -> String {
  r#"/// MetaFx 엣지: 엣지의 구조적 기술 (Generated)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct MetaFxEdge {
    pub from: String,
    pub to: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cond: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub port_info: Option<MetaFxPortInfo>,
}
"#
  .to_string()
}

fn generate_meta_fx_scope_struct() -> String {
  r#"/// MetaFx 스코프: 스코프의 구조적 기술 (Generated)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct MetaFxScope {
    pub name: String,
    pub node_count: usize,
    pub policy: String,
}
"#
  .to_string()
}

fn generate_meta_fx_stats_struct() -> String {
  r#"/// MetaFx 통계 (Generated)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct MetaFxStats {
    pub node_count: usize,
    pub edge_count: usize,
    pub scope_count: usize,
    pub gate_count: usize,
    pub optional_count: usize,
    pub conditional_edge_count: usize,
}
"#
  .to_string()
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn meta_ir_source_contains_all_structs() {
    let source = generate_meta_ir_source();

    assert!(source.contains("pub struct MetaFxModule"));
    assert!(source.contains("pub struct MetaFxInput"));
    assert!(source.contains("pub struct MetaFxMorphism"));
    assert!(source.contains("pub struct MetaFxMorphismPort"));
    assert!(source.contains("pub struct MetaExecutionContract"));
    assert!(source.contains("pub struct MetaFxNode"));
    assert!(source.contains("pub struct MetaFxEdge"));
    assert!(source.contains("pub struct MetaFxPortInfo"));
    assert!(source.contains("pub struct MetaFxScope"));
    assert!(source.contains("pub struct MetaFxStats"));
  }

  #[test]
  fn meta_ir_source_contains_header() {
    let source = generate_meta_ir_source();

    assert!(source.contains("AUTO-GENERATED BY pnix"));
    assert!(source.contains("Stage 2: Partial Self-Hosting"));
    assert!(source.contains("DO NOT EDIT MANUALLY"));
  }

  #[test]
  fn generated_source_is_deterministic() {
    let source1 = generate_meta_ir_source();
    let source2 = generate_meta_ir_source();
    assert_eq!(source1, source2);
  }
}
